REG_BAY = {
    "DJ_LINHA_FECHADO": "SE_COMUNICACAO.RELE_BAY.DNP.BI_00", # bit00 IN102
    "DJ_MOLA_CARREGADA": "SE_COMUNICACAO.RELE_BAY.DNP.BI_01", # bit01 IN102

    "BT_ABRE_DJ": "SE_COMUNICACAO.RELE_BAY.DNP.BI_02", # bit 02 IN103
    "BT_FECHA_DJ": "SE_COMUNICACAO.RELE_BAY.DNP.BI_03", # bit 03 IN104

    "SECC_FECHADA": "SE_COMUNICACAO.RELE_BAY.DNP.BI_04", # bit 04 IN105
    
    "FECHA_DJ": "SE_COMUNICACAO.RELE_BAY.DNP.BI_06", # bit 06 OUT101
    "ABRE_DJ": "SE_COMUNICACAO.RELE_BAY.DNP.BI_07", # bit 07 OUT102
    "FALHA_ABERTURA_DJL": "SE_COMUNICACAO.RELE_BAY.DNP.BI_20", # bit 20 50BFX

    "SOBRECORR_INST_FASE_Z1": "SE_COMUNICACAO.RELE_BAY.DNP.BI_13", # bit 13 67P1T
    "SOBRECORR_INST_FASE_Z2": "SE_COMUNICACAO.RELE_BAY.DNP.BI_14", # bit 14 67P2T
    "SOBRECORR_INST_FASE_Z3": "SE_COMUNICACAO.RELE_BAY.DNP.BI_15", # bit 15 67P3T
    "SOBRECORR_INST_SEQ_NEGATIVA_Z1": "SE_COMUNICACAO.RELE_BAY.DNP.BI_16", # bit 16 67Q1T
    "SOBRECORR_INST_SEQ_NEGATIVA_Z2": "SE_COMUNICACAO.RELE_BAY.DNP.BI_17", # bit 17 67Q2T
    "SOBRECORR_INST_SEQ_NEGATIVA_Z3": "SE_COMUNICACAO.RELE_BAY.DNP.BI_18", # bit 18 67Q3T
    "SOBRECORR_TEMP_FASE": "SE_COMUNICACAO.RELE_BAY.DNP.BI_19", # bit 19 51PT
    "SOBRECORR_RESID_TEMP": "SE_COMUNICACAO.RELE_BAY.DNP.BI_21", # bit 21 51GT
    "SOBRECORR_RESID_INST": "SE_COMUNICACAO.RELE_BAY.DNP.BI_22", # bit 22 67G1T

    "ENVIO_TRANSFER_TRIP_RELE_SE": "SE_COMUNICACAO.RELE_BAY.DNP.BI_23", # bit 23 50P1 OU 50Q1
    "RECEB_TRANSFER_TRIP_RELE_SE": "SE_COMUNICACAO.RELE_BAY.DNP.BI_24", # bit 24 - BF DISJUNTOR
    "RECEB_TRANSFER_TRIP_RELE_SE": "SE_COMUNICACAO.RELE_BAY.DNP.BI_25", # bit 25 + 67P2 LOCAL
    "RECEB_TRANSFER_TRIP_RELE_BAY": "SE_COMUNICACAO.RELE_BAY.DNP.BI_26", # bit 26 + 67Q2 LOCAL

    "ID_BARRA_MORTA": "SE_COMUNICACAO.RELE_BAY.DNP.BI_27", # bit 27
    "ID_BARRA_VIVA": "SE_COMUNICACAO.RELE_BAY.DNP.BI_28", # bit 28
    "ID_LINHA_MORTA": "SE_COMUNICACAO.RELE_BAY.DNP.BI_29", # bit 29 27SP
    "ID_LINHA_VIVA": "SE_COMUNICACAO.RELE_BAY.DNP.BI_30", # bit 30 59S1P
    
    "CMD_FECHA_DJ": "SE_COMUNICACAO.RELE_BAY.DNP.BO_00", 
    "CMD_ABRE_DJ": "SE_COMUNICACAO.RELE_BAY.DNP.BO_01", 

    "RESERVA": "SE_COMUNICACAO.RELE_BAY.DNP.BI_05", # bit 05 IN106
    "RESERVA": "SE_COMUNICACAO.RELE_BAY.DNP.BI_08", # bit 08 OUT103
    "RESERVA": "SE_COMUNICACAO.RELE_BAY.DNP.BI_09", # bit 09 OUT104
    "RESERVA": "SE_COMUNICACAO.RELE_BAY.DNP.BI_10", # bit 10 OUT105
    "RESERVA": "SE_COMUNICACAO.RELE_BAY.DNP.BI_11", # bit 11 OUT106
    "RESERVA": "SE_COMUNICACAO.RELE_BAY.DNP.BI_12", # bit 12 OUT107
}