# Generated by Django 2.2.12 on 2024-02-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='valor_ie_inicial',
            new_name='ie_inicial',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='pot_minima',
            new_name='pot_minima_ugs',
        ),
        migrations.RemoveField(
            model_name='parametrosusina',
            name='pot_nominal',
        ),
        migrations.RemoveField(
            model_name='parametrosusina',
            name='pot_nominal_ug',
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ad_ki',
            field=models.DecimalField(decimal_places=3, default=0.5, max_digits=15),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ad_kp',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=15),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ad_nv_alvo',
            field=models.DecimalField(decimal_places=3, default=818.1, max_digits=15),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='pot_maxima_ugs',
            field=models.DecimalField(decimal_places=1, default=5650, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='pot_maxima_usina',
            field=models.DecimalField(decimal_places=1, default=22600, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='margem_pot_critica',
            field=models.DecimalField(decimal_places=5, default=0.05, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='nv_alvo',
            field=models.DecimalField(decimal_places=3, default=817, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='nv_minimo',
            field=models.DecimalField(decimal_places=3, default=816, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='nv_montante',
            field=models.DecimalField(decimal_places=3, default=817, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='nv_religamento',
            field=models.DecimalField(decimal_places=3, default=816.3, max_digits=10),
        ),
    ]
