# Generated by Django 4.2 on 2023-06-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleEstados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(default=0)),
                ('ultimo_estado_ug1', models.TextField(default='')),
                ('ultimo_estado_ug2', models.TextField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='comando',
            name='executavel_em_autmoatico',
        ),
        migrations.AddField(
            model_name='comando',
            name='executavel_em_automatico',
            field=models.BooleanField(default=True),
        ),
    ]
