# Generated by Django 2.2.12 on 2024-03-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleEstados',
            fields=[
                ('ts', models.DateTimeField(default=0, primary_key=True, serialize=False)),
                ('ultimo_estado_ug1', models.TextField(default='')),
                ('ultimo_estado_ug2', models.TextField(default='')),
                ('ultimo_estado_ug3', models.TextField(default='')),
            ],
        ),
        migrations.RenameField(
            model_name='comando',
            old_name='executavel_em_autmoatico',
            new_name='executavel_em_automatico',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='valor_ie_inicial',
            new_name='ie_inicial',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='pot_nominal_ug',
            new_name='pot_maxima_ugs',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='pot_minima',
            new_name='pot_minima_ugs',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='press_cx_alvo',
            new_name='ug1_pressao_alvo',
        ),
        migrations.RemoveField(
            model_name='parametrosusina',
            name='pot_nominal',
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='aviso_caixa_espiral_ug1',
            field=models.DecimalField(decimal_places=2, default=16.5, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='aviso_caixa_espiral_ug2',
            field=models.DecimalField(decimal_places=2, default=16.5, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='aviso_caixa_espiral_ug3',
            field=models.DecimalField(decimal_places=2, default=16.5, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='pot_maxima_usina',
            field=models.DecimalField(decimal_places=0, default=10800, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ug1_ultimo_estado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ug2_pressao_alvo',
            field=models.DecimalField(decimal_places=2, default=16.3, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ug2_ultimo_estado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ug3_pressao_alvo',
            field=models.DecimalField(decimal_places=2, default=16.3, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ug3_ultimo_estado',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='clp_moa_ip',
            field=models.CharField(default='192.168.50.116', max_length=15),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='clp_sa_ip',
            field=models.CharField(default='192.168.50.50', max_length=15),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='clp_sa_porta',
            field=models.IntegerField(default=5002),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='clp_tda_ip',
            field=models.CharField(default='192.168.50.54', max_length=15),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='clp_tda_porta',
            field=models.IntegerField(default=5002),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='clp_ug1_ip',
            field=models.CharField(default='192.168.50.51', max_length=15),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='clp_ug1_porta',
            field=models.IntegerField(default=5002),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='clp_ug2_ip',
            field=models.CharField(default='192.168.50.52', max_length=15),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='clp_ug2_porta',
            field=models.IntegerField(default=5002),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='clp_ug3_ip',
            field=models.CharField(default='192.168.50.53', max_length=15),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='clp_ug3_porta',
            field=models.IntegerField(default=503),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
