# Generated by Django 4.2.3 on 2023-09-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0002_rename_alerta_temperatura_fase_r_ug3_parametrosusina_alerta_temperatura_enrolamento_trafo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrosusina',
            name='valor_ie_inicial',
            field=models.DecimalField(decimal_places=3, default=0.5, max_digits=10),
        ),
    ]
