# Generated by Django 4.2 on 2023-06-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0002_parametrosusina_ug1_ultimo_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controleestados',
            name='ultimo_estado_ug1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='controleestados',
            name='ultimo_estado_ug2',
            field=models.IntegerField(default=0),
        ),
    ]
