# Generated by Django 2.2.12 on 2024-03-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0002_controleestados_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controleestados',
            name='id',
        ),
        migrations.AddField(
            model_name='controleestados',
            name='ultimo_estado_ug3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ug1_ultimo_estado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ug2_ultimo_estado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ug3_ultimo_estado',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='controleestados',
            name='ts',
            field=models.DateTimeField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='controleestados',
            name='ultimo_estado_ug1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='controleestados',
            name='ultimo_estado_ug2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='clp_moa_ip',
            field=models.CharField(default='192.168.50.116', max_length=15),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='clp_sa_ip',
            field=models.CharField(default='192.168.50.50', max_length=15),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='clp_sa_porta',
            field=models.IntegerField(default=5002),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='clp_tda_ip',
            field=models.CharField(default='192.168.50.54', max_length=15),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='clp_tda_porta',
            field=models.IntegerField(default=5002),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='clp_ug1_ip',
            field=models.CharField(default='192.168.50.51', max_length=15),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='clp_ug1_porta',
            field=models.IntegerField(default=5002),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='clp_ug2_ip',
            field=models.CharField(default='192.168.50.52', max_length=15),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='clp_ug2_porta',
            field=models.IntegerField(default=5002),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='clp_ug3_ip',
            field=models.CharField(default='192.168.50.53', max_length=15),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='clp_ug3_porta',
            field=models.IntegerField(default=503),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
