# Generated by Django 4.2.5 on 2023-12-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0002_rename_valor_ie_inicial_parametrosusina_ie_inicial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosusina',
            name='ad_ki',
            field=models.DecimalField(decimal_places=3, default=0.5, max_digits=15),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ad_kp',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=15),
        ),
    ]
