# Generated by Django 4.2 on 2023-06-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0002_controleestados_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controleestados',
            name='id',
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ug1_ultimo_estado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ug2_ultimo_estado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ug3_ultimo_estado',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='controleestados',
            name='ts',
            field=models.DateTimeField(default=0, primary_key=True, serialize=False),
        ),
    ]
