# Generated by Django 4.2 on 2023-06-23 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0003_alter_controleestados_ultimo_estado_ug1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametrosusina',
            name='ug1_ultimo_estado',
        ),
        migrations.RemoveField(
            model_name='parametrosusina',
            name='ug2_ultimo_estado',
        ),
    ]
