# Generated by Django 4.2.3 on 2023-10-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0003_alter_parametrosusina_valor_ie_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosusina',
            name='ug1_ultima_etapa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ug2_ultima_etapa',
            field=models.IntegerField(default=0),
        ),
    ]
