# Generated by Django 4.2 on 2023-06-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0002_controleestados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controleestados',
            name='ultimo_estado_ug3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='controleestados',
            name='ultimo_estado_ug1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='controleestados',
            name='ultimo_estado_ug2',
            field=models.IntegerField(default=0),
        ),
    ]
