# Generated by Django 4.2.5 on 2023-09-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0003_alter_parametrosusina_valor_ie_inicial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='alerta_temperatura_enrolamento_trafo',
            new_name='alerta_temperatura_fase_r_ug3',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='alerta_temperatura_mancal_casq_comb_ug1',
            new_name='alerta_temperatura_fase_r_ug4',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='alerta_temperatura_mancal_casq_comb_ug2',
            new_name='alerta_temperatura_fase_s_ug3',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='alerta_temperatura_mancal_contra_esc_comb_ug1',
            new_name='alerta_temperatura_fase_s_ug4',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='alerta_temperatura_mancal_contra_esc_comb_ug2',
            new_name='alerta_temperatura_fase_t_ug3',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='alerta_temperatura_mancal_guia_interno_1_ug1',
            new_name='alerta_temperatura_fase_t_ug4',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='alerta_temperatura_mancal_guia_interno_1_ug2',
            new_name='alerta_temperatura_gaxeteiro_lado_jus_ug1',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='alerta_temperatura_mancal_guia_interno_2_ug1',
            new_name='alerta_temperatura_gaxeteiro_lado_jus_ug2',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='alerta_temperatura_mancal_guia_interno_2_ug2',
            new_name='alerta_temperatura_gaxeteiro_lado_jus_ug3',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='alerta_temperatura_mancal_guia_ug1',
            new_name='alerta_temperatura_gaxeteiro_lado_jus_ug4',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='alerta_temperatura_mancal_guia_ug2',
            new_name='alerta_temperatura_gaxeteiro_lado_mont_ug1',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='alerta_temperatura_nucleo_gerador_1_ug1',
            new_name='alerta_temperatura_gaxeteiro_lado_mont_ug2',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='alerta_temperatura_nucleo_gerador_1_ug2',
            new_name='alerta_temperatura_gaxeteiro_lado_mont_ug3',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='alerta_temperatura_oleo_trafo',
            new_name='alerta_temperatura_gaxeteiro_lado_mont_ug4',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='alerta_temperatura_patins_mancal_comb_1_ug1',
            new_name='alerta_temperatura_mancal_comb_bucha_rad_ug1',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='alerta_temperatura_patins_mancal_comb_1_ug2',
            new_name='alerta_temperatura_mancal_comb_bucha_rad_ug2',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='alerta_temperatura_patins_mancal_comb_2_ug1',
            new_name='alerta_temperatura_mancal_comb_bucha_rad_ug3',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='alerta_temperatura_patins_mancal_comb_2_ug2',
            new_name='alerta_temperatura_mancal_comb_bucha_rad_ug4',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='clp_sa_porta',
            new_name='clp_adufas_porta',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='limite_temperatura_enrolamento_trafo',
            new_name='limite_temperatura_fase_r_ug3',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='limite_temperatura_mancal_casq_comb_ug1',
            new_name='limite_temperatura_fase_r_ug4',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='limite_temperatura_mancal_casq_comb_ug2',
            new_name='limite_temperatura_fase_s_ug3',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='limite_temperatura_mancal_contra_esc_comb_ug1',
            new_name='limite_temperatura_fase_s_ug4',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='limite_temperatura_mancal_contra_esc_comb_ug2',
            new_name='limite_temperatura_fase_t_ug3',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='limite_temperatura_mancal_guia_interno_1_ug1',
            new_name='limite_temperatura_fase_t_ug4',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='limite_temperatura_mancal_guia_interno_1_ug2',
            new_name='limite_temperatura_gaxeteiro_lado_jus_ug1',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='limite_temperatura_mancal_guia_interno_2_ug1',
            new_name='limite_temperatura_gaxeteiro_lado_jus_ug2',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='limite_temperatura_mancal_guia_interno_2_ug2',
            new_name='limite_temperatura_gaxeteiro_lado_jus_ug3',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='limite_temperatura_mancal_guia_ug1',
            new_name='limite_temperatura_gaxeteiro_lado_jus_ug4',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='limite_temperatura_mancal_guia_ug2',
            new_name='limite_temperatura_gaxeteiro_lado_mont_ug1',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='limite_temperatura_nucleo_gerador_1_ug1',
            new_name='limite_temperatura_gaxeteiro_lado_mont_ug2',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='limite_temperatura_nucleo_gerador_1_ug2',
            new_name='limite_temperatura_gaxeteiro_lado_mont_ug3',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='limite_temperatura_oleo_trafo',
            new_name='limite_temperatura_gaxeteiro_lado_mont_ug4',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='limite_temperatura_patins_mancal_comb_1_ug1',
            new_name='limite_temperatura_mancal_comb_bucha_rad_ug1',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='limite_temperatura_patins_mancal_comb_1_ug2',
            new_name='limite_temperatura_mancal_comb_bucha_rad_ug2',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='limite_temperatura_patins_mancal_comb_2_ug1',
            new_name='limite_temperatura_mancal_comb_bucha_rad_ug3',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='limite_temperatura_patins_mancal_comb_2_ug2',
            new_name='limite_temperatura_mancal_comb_bucha_rad_ug4',
        ),
        migrations.RemoveField(
            model_name='parametrosusina',
            name='clp_sa_ip',
        ),
        migrations.AddField(
            model_name='controleestados',
            name='ultimo_estado_ug3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='controleestados',
            name='ultimo_estado_ug4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='alerta_perda_grade_ug3',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='alerta_perda_grade_ug4',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='alerta_pressao_turbina_ug3',
            field=models.DecimalField(decimal_places=2, default=1.4, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='alerta_pressao_turbina_ug4',
            field=models.DecimalField(decimal_places=2, default=1.4, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='alerta_temperatura_mancal_comb_sa_contr_esc_ug1',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='alerta_temperatura_mancal_comb_sa_contr_esc_ug2',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='alerta_temperatura_mancal_comb_sa_contr_esc_ug3',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='alerta_temperatura_mancal_comb_sa_contr_esc_ug4',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='alerta_temperatura_mancal_comb_sa_esc_ug1',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='alerta_temperatura_mancal_comb_sa_esc_ug2',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='alerta_temperatura_mancal_comb_sa_esc_ug3',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='alerta_temperatura_mancal_comb_sa_esc_ug4',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='alerta_temperatura_mancal_la_casq_1_ug1',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='alerta_temperatura_mancal_la_casq_1_ug2',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='alerta_temperatura_mancal_la_casq_1_ug3',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='alerta_temperatura_mancal_la_casq_1_ug4',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='alerta_temperatura_mancal_la_casq_2_ug1',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='alerta_temperatura_mancal_la_casq_2_ug2',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='alerta_temperatura_mancal_la_casq_2_ug3',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='alerta_temperatura_mancal_la_casq_2_ug4',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='alerta_temperatura_mancal_lna_casq_1_ug1',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='alerta_temperatura_mancal_lna_casq_1_ug2',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='alerta_temperatura_mancal_lna_casq_1_ug3',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='alerta_temperatura_mancal_lna_casq_1_ug4',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='alerta_temperatura_mancal_lna_casq_2_ug1',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='alerta_temperatura_mancal_lna_casq_2_ug2',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='alerta_temperatura_mancal_lna_casq_2_ug3',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='alerta_temperatura_mancal_lna_casq_2_ug4',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='alerta_temperatura_oleo_uhct_ug1',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='alerta_temperatura_oleo_uhct_ug2',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='alerta_temperatura_oleo_uhct_ug3',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='alerta_temperatura_oleo_uhct_ug4',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='alerta_temperatura_oleo_uhlm_ug1',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='alerta_temperatura_oleo_uhlm_ug2',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='alerta_temperatura_oleo_uhlm_ug3',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='alerta_temperatura_oleo_uhlm_ug4',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='clp_adufas_ip',
            field=models.CharField(default='192.168.68.30', max_length=15),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='clp_se_ip',
            field=models.CharField(default='192.168.68.22', max_length=15),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='clp_se_porta',
            field=models.IntegerField(default=502),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='clp_ug3_ip',
            field=models.CharField(default='192.168.68.16', max_length=15),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='clp_ug3_porta',
            field=models.IntegerField(default=502),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='clp_ug4_ip',
            field=models.CharField(default='192.168.68.19', max_length=15),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='clp_ug4_porta',
            field=models.IntegerField(default=502),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_perda_grade_ug3',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_perda_grade_ug4',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_pressao_turbina_ug3',
            field=models.DecimalField(decimal_places=2, default=1.4, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_pressao_turbina_ug4',
            field=models.DecimalField(decimal_places=2, default=1.4, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_mancal_comb_sa_contr_esc_ug1',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_mancal_comb_sa_contr_esc_ug2',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_mancal_comb_sa_contr_esc_ug3',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_mancal_comb_sa_contr_esc_ug4',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_mancal_comb_sa_esc_ug1',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_mancal_comb_sa_esc_ug2',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_mancal_comb_sa_esc_ug3',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_mancal_comb_sa_esc_ug4',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_mancal_la_casq_1_ug1',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_mancal_la_casq_1_ug2',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_mancal_la_casq_1_ug3',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_mancal_la_casq_1_ug4',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_mancal_la_casq_2_ug1',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_mancal_la_casq_2_ug2',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_mancal_la_casq_2_ug3',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_mancal_la_casq_2_ug4',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_mancal_lna_casq_1_ug1',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_mancal_lna_casq_1_ug2',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_mancal_lna_casq_1_ug3',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_mancal_lna_casq_1_ug4',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_mancal_lna_casq_2_ug1',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_mancal_lna_casq_2_ug2',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_mancal_lna_casq_2_ug3',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_mancal_lna_casq_2_ug4',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_oleo_uhct_ug1',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_oleo_uhct_ug2',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_oleo_uhct_ug3',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_oleo_uhct_ug4',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_oleo_uhlm_ug1',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_oleo_uhlm_ug2',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_oleo_uhlm_ug3',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_oleo_uhlm_ug4',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ug3_disp',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ug3_nv_pos_grade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ug3_perda_grade_maxima',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ug3_pos_comporta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ug3_pot',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ug3_prioridade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ug3_setpot',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ug3_ultimo_estado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ug4_disp',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ug4_nv_pos_grade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ug4_perda_grade_maxima',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ug4_pos_comporta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ug4_pot',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ug4_prioridade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ug4_setpot',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ug4_ultimo_estado',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='clp_tda_ip',
            field=models.CharField(default='192.168.68.29', max_length=15),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='clp_ug1_ip',
            field=models.CharField(default='192.168.68.10', max_length=15),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='clp_ug2_ip',
            field=models.CharField(default='192.168.68.13', max_length=15),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='limite_pressao_turbina_ug1',
            field=models.DecimalField(decimal_places=2, default=1.4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='limite_pressao_turbina_ug2',
            field=models.DecimalField(decimal_places=2, default=1.4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='nv_alvo',
            field=models.DecimalField(decimal_places=3, default=816.9, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='nv_maximo',
            field=models.DecimalField(decimal_places=3, default=818, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='nv_minimo',
            field=models.DecimalField(decimal_places=3, default=816.8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='nv_montante',
            field=models.DecimalField(decimal_places=3, default=816.9, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='nv_religamento',
            field=models.DecimalField(decimal_places=3, default=816.85, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='pot_minima',
            field=models.DecimalField(decimal_places=0, default=1700, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='pot_nominal',
            field=models.DecimalField(decimal_places=1, default=5600, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='pot_nominal_ug',
            field=models.DecimalField(decimal_places=1, default=5600, max_digits=10),
        ),
    ]
