# Generated by Django 4.2.5 on 2023-12-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0003_parametrosusina_ad_ki_parametrosusina_ad_kp'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosusina',
            name='ad_nv_alvo',
            field=models.DecimalField(decimal_places=3, default=818.1, max_digits=15),
        ),
    ]
