# Generated by Django 4.2 on 2023-06-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0004_controleestados_ultimo_estado_ug3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrosusina',
            name='clp_moa_ip',
            field=models.CharField(default='192.168.50.116', max_length=15),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='clp_sa_ip',
            field=models.CharField(default='192.168.50.50', max_length=15),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='clp_sa_porta',
            field=models.IntegerField(default=5002),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='clp_tda_ip',
            field=models.CharField(default='192.168.50.54', max_length=15),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='clp_tda_porta',
            field=models.IntegerField(default=5002),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='clp_ug1_ip',
            field=models.CharField(default='192.168.50.51', max_length=15),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='clp_ug1_porta',
            field=models.IntegerField(default=5002),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='clp_ug2_ip',
            field=models.CharField(default='192.168.50.52', max_length=15),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='clp_ug2_porta',
            field=models.IntegerField(default=5002),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='clp_ug3_ip',
            field=models.CharField(default='192.168.50.53', max_length=15),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='clp_ug3_porta',
            field=models.IntegerField(default=503),
        ),
    ]
