# Generated by Django 2.2.12 on 2024-01-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0004_auto_20240129_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosusina',
            name='alerta_temperatura_oleo_uhrv_ug1',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='alerta_temperatura_oleo_uhrv_ug2',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='horario_disparo_lg',
            field=models.DateTimeField(default='2024-01-29 17:49:42'),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_oleo_uhrv_ug1',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_oleo_uhrv_ug2',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='manter_unidades',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='modo_lg',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='t_dias_disparo_lg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='t_horas_disparo_lg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ug1_ultima_etapa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ug2_ultima_etapa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='valor_disparo_lg_p1',
            field=models.DecimalField(decimal_places=2, default=0.3, max_digits=5),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='valor_disparo_lg_p2',
            field=models.DecimalField(decimal_places=2, default=0.3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='controleestados',
            name='ultimo_estado_ug1',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='controleestados',
            name='ultimo_estado_ug2',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='alerta_perda_grade_ug1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='alerta_perda_grade_ug2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='limite_perda_grade_ug1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='ug1_perda_grade_maxima',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='ug2_perda_grade_maxima',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
