# Generated by Django 4.2.3 on 2023-11-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0004_parametrosusina_ug1_ultima_etapa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controleestados',
            name='ultimo_estado_ug1',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='controleestados',
            name='ultimo_estado_ug2',
            field=models.TextField(default=''),
        ),
    ]
