# Generated by Django 4.2 on 2023-06-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0004_remove_parametrosusina_ug1_ultimo_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosusina',
            name='ug1_ultimo_estado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ug2_ultimo_estado',
            field=models.IntegerField(default=0),
        ),
    ]
