# Generated by Django 4.2 on 2023-08-31 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0005_parametrosusina_ug1_ultimo_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosusina',
            name='djl_manual',
            field=models.BooleanField(default=False),
        ),
    ]
