# Generated by Django 4.2 on 2023-10-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0005_alter_parametrosusina_clp_moa_ip_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='press_cx_alvo',
            new_name='ug1_press_cx_alvo',
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ug2_press_cx_alvo',
            field=models.DecimalField(decimal_places=2, default=16.3, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ug3_press_cx_alvo',
            field=models.DecimalField(decimal_places=2, default=16.3, max_digits=10),
        ),
    ]
