# Generated by Django 4.2.5 on 2023-11-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0005_rename_alerta_temperatura_fase_r_ug1_parametrosusina_alerta_temperatura_fase_u_ug2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='alerta_temperatura_mancal_la_1_ug2',
            new_name='alerta_temperatura_fase_u_ug1',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='alerta_temperatura_mancal_la_1_ug3',
            new_name='alerta_temperatura_fase_v_ug1',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='alerta_temperatura_mancal_la_1_ug4',
            new_name='alerta_temperatura_fase_w_ug1',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='alerta_temperatura_mancal_la_2_ug2',
            new_name='alerta_temperatura_mancal_gerador_la_1_ug1',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='alerta_temperatura_mancal_la_2_ug3',
            new_name='alerta_temperatura_mancal_gerador_la_1_ug2',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='alerta_temperatura_mancal_la_2_ug4',
            new_name='alerta_temperatura_mancal_gerador_la_1_ug3',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='alerta_temperatura_mancal_lna_1_ug2',
            new_name='alerta_temperatura_mancal_gerador_la_1_ug4',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='alerta_temperatura_mancal_lna_1_ug3',
            new_name='alerta_temperatura_mancal_gerador_la_2_ug1',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='alerta_temperatura_mancal_lna_1_ug4',
            new_name='alerta_temperatura_mancal_gerador_la_2_ug2',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='alerta_temperatura_mancal_lna_2_ug2',
            new_name='alerta_temperatura_mancal_gerador_la_2_ug3',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='alerta_temperatura_mancal_lna_2_ug3',
            new_name='alerta_temperatura_mancal_gerador_la_2_ug4',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='alerta_temperatura_mancal_lna_2_ug4',
            new_name='alerta_temperatura_mancal_gerador_lna_1_ug1',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='limite_temperatura_mancal_la_1_ug2',
            new_name='alerta_temperatura_mancal_gerador_lna_1_ug2',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='limite_temperatura_mancal_la_1_ug3',
            new_name='alerta_temperatura_mancal_gerador_lna_1_ug3',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='limite_temperatura_mancal_la_1_ug4',
            new_name='alerta_temperatura_mancal_gerador_lna_1_ug4',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='limite_temperatura_mancal_la_2_ug2',
            new_name='alerta_temperatura_mancal_gerador_lna_2_ug1',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='limite_temperatura_mancal_la_2_ug3',
            new_name='alerta_temperatura_mancal_gerador_lna_2_ug2',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='limite_temperatura_mancal_la_2_ug4',
            new_name='alerta_temperatura_mancal_gerador_lna_2_ug3',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='limite_temperatura_mancal_lna_1_ug2',
            new_name='alerta_temperatura_mancal_gerador_lna_2_ug4',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='limite_temperatura_mancal_lna_1_ug3',
            new_name='alerta_temperatura_mancal_turbina_contra_escora_ug1',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='limite_temperatura_mancal_lna_1_ug4',
            new_name='alerta_temperatura_mancal_turbina_escora_ug1',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='limite_temperatura_mancal_lna_2_ug2',
            new_name='alerta_temperatura_mancal_turbina_radial_ug1',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='limite_temperatura_mancal_lna_2_ug3',
            new_name='alerta_temperatura_oleo_uhct_ug1',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='limite_temperatura_mancal_lna_2_ug4',
            new_name='alerta_temperatura_oleo_uhlm_ug1',
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='alerta_perda_grade_ug1',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='alerta_pressao_turbina_ug1',
            field=models.DecimalField(decimal_places=2, default=1.4, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_perda_grade_ug1',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_pressao_turbina_ug1',
            field=models.DecimalField(decimal_places=2, default=1.4, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_fase_u_ug1',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_fase_v_ug1',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_fase_w_ug1',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_mancal_gerador_la_1_ug1',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_mancal_gerador_la_1_ug2',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_mancal_gerador_la_1_ug3',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_mancal_gerador_la_1_ug4',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_mancal_gerador_la_2_ug1',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_mancal_gerador_la_2_ug2',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_mancal_gerador_la_2_ug3',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_mancal_gerador_la_2_ug4',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_mancal_gerador_lna_1_ug1',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_mancal_gerador_lna_1_ug2',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_mancal_gerador_lna_1_ug3',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_mancal_gerador_lna_1_ug4',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_mancal_gerador_lna_2_ug1',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_mancal_gerador_lna_2_ug2',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_mancal_gerador_lna_2_ug3',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_mancal_gerador_lna_2_ug4',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_mancal_turbina_contra_escora_ug1',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_mancal_turbina_escora_ug1',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_mancal_turbina_radial_ug1',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_oleo_uhct_ug1',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_oleo_uhlm_ug1',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
