# Generated by Django 4.2.3 on 2023-11-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0006_parametrosusina_manter_unidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosusina',
            name='tempo_disparo_lg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='alerta_perda_grade_ug1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='limite_perda_grade_ug1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='ug1_perda_grade_maxima',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='ug2_perda_grade_maxima',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
