# Generated by Django 4.2 on 2023-11-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0006_rename_press_cx_alvo_parametrosusina_ug1_press_cx_alvo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosusina',
            name='aviso_caixa_espiral_ug1',
            field=models.DecimalField(decimal_places=2, default=16.5, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='aviso_caixa_espiral_ug2',
            field=models.DecimalField(decimal_places=2, default=16.5, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='aviso_caixa_espiral_ug3',
            field=models.DecimalField(decimal_places=2, default=16.5, max_digits=10),
        ),
    ]
