# Generated by Django 2.2.12 on 2023-06-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0006_auto_20230630_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controleestados',
            name='id',
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ug1_ultimo_estado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ug2_ultimo_estado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ug3_ultimo_estado',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='controleestados',
            name='ts',
            field=models.DateTimeField(default=0, primary_key=True, serialize=False),
        ),
    ]
