# Generated by Django 2.2.12 on 2024-04-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0006_parametrosusina_djl_manual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametrosusina',
            name='djl_manual',
        ),
        migrations.AlterField(
            model_name='controleestados',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
