# Generated by Django 4.2 on 2023-11-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0007_parametrosusina_aviso_caixa_espiral_ug1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controleestados',
            name='ultimo_estado_ug1',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='controleestados',
            name='ultimo_estado_ug2',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='controleestados',
            name='ultimo_estado_ug3',
            field=models.TextField(default=''),
        ),
    ]
