# Generated by Django 4.2.3 on 2023-11-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0007_parametrosusina_tempo_disparo_lg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametrosusina',
            name='tempo_disparo_lg',
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='tempo_disparo_lg_h',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='tempo_disparo_lg_m',
            field=models.IntegerField(default=0),
        ),
    ]
