# Generated by Django 4.2 on 2024-03-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0007_auto_20240222_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosusina',
            name='alerta_perda_grade',
            field=models.DecimalField(decimal_places=3, default=0.3, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_perda_grade',
            field=models.DecimalField(decimal_places=3, default=0.4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='controleestados',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
