# Generated by Django 4.2 on 2023-11-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0008_alter_controleestados_ultimo_estado_ug1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='valor_ie_inicial',
            new_name='ie_inicial',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='pot_nominal',
            new_name='pot_alvo_usina',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='pot_nominal_ug',
            new_name='pot_maxima_ugs',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='pot_minima',
            new_name='pot_minima_ugs',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='ug1_press_cx_alvo',
            new_name='ug1_pressao_alvo',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='ug2_press_cx_alvo',
            new_name='ug2_pressao_alvo',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='ug3_press_cx_alvo',
            new_name='ug3_pressao_alvo',
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='pot_maxima_usina',
            field=models.DecimalField(decimal_places=0, default=10800, max_digits=10),
        ),
    ]
