# Generated by Django 4.2.3 on 2023-11-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0008_remove_parametrosusina_tempo_disparo_lg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosusina',
            name='hora_disparo_lg',
            field=models.DateTimeField(default='2023-11-29 10:18:00'),
        ),
    ]
