# Generated by Django 4.2 on 2023-11-28 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0009_rename_valor_ie_inicial_parametrosusina_ie_inicial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametrosusina',
            name='pot_alvo_usina',
        ),
    ]
