# Generated by Django 4.2.3 on 2023-11-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0009_parametrosusina_hora_disparo_lg'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosusina',
            name='tempo_disparo_lg_d',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='alerta_perda_grade_ug2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
