# Generated by Django 4.2.3 on 2023-11-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0010_parametrosusina_tempo_disparo_lg_d_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosusina',
            name='modo_lg',
            field=models.IntegerField(default=1),
        ),
    ]
