# Generated by Django 4.2.3 on 2023-11-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0011_parametrosusina_modo_lg'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosusina',
            name='valor_disparo_lg_perda_ug1',
            field=models.DecimalField(decimal_places=2, default=0.3, max_digits=5),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='valor_disparo_lg_perda_ug2',
            field=models.DecimalField(decimal_places=2, default=0.3, max_digits=5),
        ),
    ]
