# Generated by Django 4.2.3 on 2023-11-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0012_parametrosusina_valor_disparo_lg_perda_ug1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrosusina',
            name='hora_disparo_lg',
            field=models.DateTimeField(default='2023-11-29 17:07:23'),
        ),
    ]
