# Generated by Django 4.2.3 on 2023-11-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0013_alter_parametrosusina_hora_disparo_lg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrosusina',
            name='hora_disparo_lg',
            field=models.DateTimeField(default='2023-11-29 18:45:04'),
        ),
    ]
