# Generated by Django 4.2.3 on 2023-11-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0014_alter_parametrosusina_hora_disparo_lg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametrosusina',
            name='tempo_disparo_lg_m',
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='hora_disparo_lg',
            field=models.DateTimeField(default='2023-11-30 09:52:22'),
        ),
    ]
