# Generated by Django 4.2.3 on 2023-11-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0016_rename_valor_disparo_lg_perda_ug1_parametrosusina_valor_disparo_lg_p1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametrosusina',
            name='hora_disparo_lg',
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='horario_disparo_lg',
            field=models.DateTimeField(default='2023-11-30 10:46:18'),
        ),
    ]
