# Generated by Django 4.2.3 on 2023-11-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0017_remove_parametrosusina_hora_disparo_lg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='tempo_disparo_lg_d',
            new_name='t_dias_disparo_lg_d',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='tempo_disparo_lg_h',
            new_name='t_horas_disparo_lg_h',
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='horario_disparo_lg',
            field=models.DateTimeField(default='2023-11-30 10:47:20'),
        ),
    ]
