# Generated by Django 4.2.3 on 2023-11-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0018_rename_tempo_disparo_lg_d_parametrosusina_t_dias_disparo_lg_d_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='t_dias_disparo_lg_d',
            new_name='t_dias_disparo_lg',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='t_horas_disparo_lg_h',
            new_name='t_horas_disparo_lg',
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='horario_disparo_lg',
            field=models.DateTimeField(default='2023-11-30 10:47:38'),
        ),
    ]
