# Generated by Django 4.2.3 on 2023-12-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0019_rename_t_dias_disparo_lg_d_parametrosusina_t_dias_disparo_lg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosusina',
            name='alerta_temperatura_oleo_uhrv_ug1',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='alerta_temperatura_oleo_uhrv_ug2',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_oleo_uhrv_ug1',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='limite_temperatura_oleo_uhrv_ug2',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='horario_disparo_lg',
            field=models.DateTimeField(default='2023-12-27 10:16:31'),
        ),
    ]
