import logging

import src.funcoes.leitura as l
import src.conectores.servidores as s

from time import sleep
from logging.config import fileConfig

from src.dicionarios.reg import *


fileConfig("/opt/operacao-autonoma/testes/log_testes.ini")
log = logging.getLogger("teste")


l_condic: "dict[str,l.LeituraModbusBit]" = {}
l_mensageiro: "dict[str,l.LeituraModbusBit]" = {}


l_condic['1'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["EMERGENCIA_ACIONADA"], descricao="[SA]  Usina Emergência Acionada")
l_condic['2'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["CB_ALARME"], descricao="[SA]  Alarme Carregador Baterias 1")
l_condic['3'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["CB2_ALARME"], descricao="[SA]  Alarme Carregador Baterias 2")
l_condic['4'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["FUGA_TERRA_ALARME"], descricao="[SA]  Alarme Fuga Terra")
l_condic['5'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme08_07"], descricao="[SA]  Sistema de Água de Serviço - Botão de Emergência do Filtro 01 Acionado")
l_condic['6'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme21_02"], descricao="[SA]  Torre de Resfriamento - Botão de Emergência Acionado")
l_condic['7'] = l.LeituraModbus(s.Servidores.clp["SA"], REG_SA["FUGA_TERRA_TENSAO"], descricao="[SA]  Fuga Terra Tensão")
l_condic['8'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["FUGA_TERRA_TRIP"], descricao="[SA]  TRIP Fuga Terra")
l_condic['9'] = l.LeituraModbus(s.Servidores.clp["SA"], REG_SA["FUGA_TERRA_TENSAO_POSITIVA"], descricao="[SA]  Fuga Terra Tensão Positiva")
l_condic['10'] = l.LeituraModbus(s.Servidores.clp["SA"], REG_SA["FUGA_TERRA_TENSAO_NEGATIVA"], descricao="[SA]  Fuga Terra Tensão Negativa")
l_condic['11'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["FUGA_TERRA_POSITIVO"], descricao="[SA]  Fuga Terra Positivo")
l_condic['12'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["FUGA_TERRA_NEGATIVO"], descricao="[SA]  Fuga Terra Negativo")
l_condic['13'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme01_02"], descricao="[SA]  PDSA-CC - Falta Tensão Vcc Carregador de Baterias 01")
l_condic['14'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme01_03"], descricao="[SA]  PDSA-CC - Falta Tensão Vcc Carregador de Baterias 02")
l_condic['15'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme01_07"], descricao="[SA]  PINV - Controlador Boost 01 - Sobretensão no Link 540Vcc")
l_condic['16'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme01_08"], descricao="[SA]  PINV - Controlador Boost 01 - Subtensão no Link 540Vcc")
l_condic['17'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme01_09"], descricao="[SA]  Compressor de AR - Pressão Baixa")
l_condic['18'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme01_10"], descricao="[SA]  Compressor de AR - Pressão Alta")
l_condic['19'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme01_11"], descricao="[SA]  PINV - Controlador Boost 01 - Sobre Disparo IGBT")
l_condic['20'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme01_15"], descricao="[SA]  PINV - Controlador Boost 01 - Sub Disparo IGBT")
l_condic['21'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme02_03"], descricao="[SA]  PINV - Controlador Boost 01 - Sobrecorrente no Link 125Vcc")
l_condic['22'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme02_06"], descricao="[SA]  PINV - Controlador Boost 01 - Subcorrente no Link 125Vcc")
l_condic['23'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme02_09"], descricao="[SA]  PINV - Controlador Boost 01 - Falha no Circuito de Potência")
l_condic['24'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme02_10"], descricao="[SA]  PINV - Controlador Boost 01 - Falha Acionamento Contator 1K2")
l_condic['25'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme02_14"], descricao="[SA]  PINV - Controlador Boost 01 - Falha na Pré-Carga")
l_condic['26'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme02_15"], descricao="[SA]  PINV - Controlador Boost 01 - Falha Acionamento Contator 1K1")
l_condic['27'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme03_09"], descricao="[SA]  Falta de Fase Fonte 01 (TSA-01)")
l_condic['28'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme03_10"], descricao="[SA]  Falta de Fase Fonte 02 (TSA-02 ou Rede Celesc)")
l_condic['29'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme03_11"], descricao="[SA]  Falta de Fase Fonte 03 (Grupo Diesel)")
l_condic['30'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme03_12"], descricao="[SA]  Falha nas Fontes")
l_condic['31'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme03_13"], descricao="[SA]  Atenção Comandos em Modo Manual")
l_condic['32'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme03_14"], descricao="[SA]  Falta de Fase Fonte 04 (TSA-02)")
l_condic['33'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme03_15"], descricao="[SA]  Falta de Fase Fonte 05 (Rede Celesc)")
l_condic['34'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme04_00"], descricao="[SA]  Atenção Quadro de Transferência em Modo Local")
l_condic['35'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme04_01"], descricao="[SA]  Trafo Auxiliar TSA-01 - Alarme Sobretemperatura do Enrolamento")
l_condic['36'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme04_02"], descricao="[SA]  Trafo Auxiliar TSA-01 - Trip Sobretemperatura do Enrolamento (Efetuar Troca Para o TSA-02)")
l_condic['37'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme04_03"], descricao="[SA]  Trafo Auxiliar TSA-01 - Falha Relé Monitor de Temperatura")
l_condic['38'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme04_04"], descricao="[SA]  PINV - Controlador Boost 01 - Falha na Realimentação")
l_condic['39'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme04_05"], descricao="[SA]  Trafo Auxiliar TSA-02 - Alarme Sobretemperatura do Enrolamento")
l_condic['40'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme04_06"], descricao="[SA]  Trafo Auxiliar TSA-02 - Trip Sobretemperatura do Enrolamento (Efetuar Troca Para o TSA-01)")
l_condic['41'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme04_07"], descricao="[SA]  Trafo Auxiliar TSA-02 - Falha Relé Monitor de Temperatura")
l_condic['42'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme04_08"], descricao="[SA]  PINV - Controlador Boost 02 - Sobretensão no Link 540Vcc")
l_condic['43'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme04_09"], descricao="[SA]  PINV - Controlador Boost 02 - Subtensão no Link 540Vcc")
l_condic['44'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme05_00"], descricao="[SA]  PINV - Controlador Boost 02 - Sobre Disparo IGBT")
l_condic['45'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme05_01"], descricao="[SA]  PINV - Controlador Boost 02 - Sub Disparo IGBT")
l_condic['46'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme05_15"], descricao="[SA]  PINV - Controlador Boost 02 - Sobrecorrente no Link 125Vcc")
l_condic['47'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme06_00"], descricao="[SA]  PINV - Controlador Boost 02 - Subcorrente no Link 125Vcc")
l_condic['48'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme06_01"], descricao="[SA]  PINV - Controlador Boost 02 - Falha no Circuito de Potência")
l_condic['49'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme06_02"], descricao="[SA]  PINV - Controlador Boost 02 - Falha Acionamento Contator 1K2")
l_condic['50'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme06_03"], descricao="[SA]  Carregador de Baterias 01 - Fuga Terra Polo Positivo ou Negativo")
l_condic['51'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme06_04"], descricao="[SA]  Carregador de Baterias 01 - Falha Alarme no Retificador")
l_condic['52'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme06_05"], descricao="[SA]  Carregador de Baterias 01 - Sub/Sobretensão Vcc")
l_condic['53'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme06_06"], descricao="[SA]  Carregador de Baterias 01 - Ausência de Tensão CA ou Tensão Baixa nas Baterias")
l_condic['54'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme06_07"], descricao="[SA]  PINV - Controlador Boost 02 - Falha na Pré-Carga")
l_condic['55'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme06_08"], descricao="[SA]  PINV - Controlador Boost 02 - Falha Acionamento Contator 1K1")
l_condic['56'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme06_09"], descricao="[SA]  PINV - Controlador Boost 02 - Falha na Realimentação")
l_condic['57'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme06_11"], descricao="[SA]  Carregador de Baterias 02 - Fuga Terra Polo Positivo ou Negativo")
l_condic['58'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme06_12"], descricao="[SA]  Carregador de Baterias 02 - Falha Alarme no Retificador")
l_condic['59'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme06_13"], descricao="[SA]  Carregador de Baterias 02 - Sub/Sobretensão Vcc")
l_condic['60'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme06_14"], descricao="[SA]  Carregador de Baterias 02 - Ausência de Tensão CA ou Tensão Baixa nas Baterias")
l_condic['61'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme07_01"], descricao="[SA]  Drenagem - Nível do Poço Alto")
l_condic['62'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme07_02"], descricao="[SA]  Drenagem - Nível do Poço Muito Alto")
l_condic['63'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme07_03"], descricao="[SA]  Drenagem - Nível do Poço Inundação ( Bloquio 86H nas UGs*)")
l_condic['64'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme07_04"], descricao="[SA]  Drenagem - Falta Alimentação CA nos Relés de Nível")
l_condic['65'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme07_05"], descricao="[SA]  Drenagem - Bomba 01 Falha no Acionamento ")
l_condic['66'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme07_06"], descricao="[SA]  Drenagem - Bomba 02 Falha no Acionamento")
l_condic['67'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme07_07"], descricao="[SA]  Drenagem - Bomba 03 Falha no Acionamento")
l_condic['68'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme07_11"], descricao="[SA]  Injeção de Água no Selo Mecânico - Falha no Acionamento da Bomba 01")
l_condic['69'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme07_12"], descricao="[SA]  Injeção de Água no Selo Mecânico - Falha no Acionamento da Bomba 02")
l_condic['70'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme07_13"], descricao="[SA]  Sistema de Água de Serviço - Falha no Acionamento da Bomba 01")
l_condic['71'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme07_14"], descricao="[SA]  Sistema de Água de Serviço - Falha no Acionamento da Bomba 02")
l_condic['72'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme07_15"], descricao="[SA]  Sistema de Água de Serviço - Falha na Abertura da Válvula de Entrada do Filtro 01")
l_condic['73'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme08_00"], descricao="[SA]  Sistema de Água de Serviço - Falha no Fechamento da Válvula de Entrada do Filtro 01")
l_condic['74'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme08_01"], descricao="[SA]  Sistema de Água de Serviço - Falha na Abertura da Válvula de Entrada do Filtro 02")
l_condic['75'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme08_02"], descricao="[SA]  Sistema de Água de Serviço - Falha no Fechamento da Válvula de Entrada do Filtro 02")
l_condic['76'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme08_03"], descricao="[SA]  Sistema de Água de Serviço - Falha na Abertura da Válvula de Entrada da Torre de Resfriamento")
l_condic['77'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme08_04"], descricao="[SA]  Sistema de Água de Serviço - Falha no Fechamento da Válvula de Entrada da Torre de Resfriamento")
l_condic['78'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme08_05"], descricao="[SA]  Sistema de Água de Serviço - Falha na Abertura da Válvula de Saída da Torre de Resfriamento")
l_condic['79'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme08_06"], descricao="[SA]  Sistema de Água de Serviço - Falha no Fechamento da Válvula de Saída da Torre de Resfriamento")
l_condic['80'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme08_08"], descricao="[SA]  Sistema de Água de Serviço - Trip Disjuntor Filtro 01")
l_condic['81'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme08_09"], descricao="[SA]  Sistema de Água de Serviço - Perda de Carga no Filtro 01")
l_condic['82'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme08_10"], descricao="[SA]  Sistema de Água de Serviço - Falta de Fase CA no Filtro 01")
l_condic['83'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme08_11"], descricao="[SA]  Sistema de Água de Serviço - Botão de Emergência do Filtro 02 Acionado")
l_condic['84'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme08_12"], descricao="[SA]  Sistema de Água de Serviço - Trip Disjuntor Filtro 02")
l_condic['85'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme08_13"], descricao="[SA]  Sistema de Água de Serviço - Perda de Carga no Filtro 02")
l_condic['86'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme08_14"], descricao="[SA]  Sistema de Água de Serviço - Falta de Fase CA no Filtro 02")
l_condic['87'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme09_00"], descricao="[SA]  Sensor de Presença Sala Supervisório Atuado")
l_condic['88'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme09_01"], descricao="[SA]  Sensor de Presença Saída Cozinha Banheiro Atuado")
l_condic['89'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme09_02"], descricao="[SA]  Sensor de Presença Almoxarifado Atuado")
l_condic['90'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme09_03"], descricao="[SA]  Sensor de Presença Área de Montagem Atuado")
l_condic['91'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme09_04"], descricao="[SA]  Sensor de Presença Sala de Cubículos Atuado")
l_condic['92'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme09_09"], descricao="[SA]  PDSA-CA - Sensor de Fumaça Atuado")
l_condic['93'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme09_10"], descricao="[SA]  PDSA-CA - Sensor de Fumaça Desconectado")
l_condic['94'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme09_11"], descricao="[SA]  PDSA-CC - Sensor de Fumaça Atuado")
l_condic['95'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme09_12"], descricao="[SA]  PDSA-CC - Sensor de Fumaça Desconectado")
l_condic['96'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme10_00"], descricao="[SA]  PACP-SE - Alimentação Relés de Nível do Poço de Drenagem - Disj. Q220.1 Desligado")
l_condic['97'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme10_01"], descricao="[SA]  PACP-SE - Alimentação Circuitos de Comando - Disj. Q125.0 Desligado")
l_condic['98'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme10_02"], descricao="[SA]  PACP-SE - Alimentação Relé de Proteção 59N - Disj. Q125.1 Desligado")
l_condic['99'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme10_03"], descricao="[SA]  PACP-SE - Alimentação Relés de Proteção SEL311C e SEL787 - Disj. Q125.2 Desligado")
l_condic['100'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme10_04"], descricao="[SA]  PACP-SE - Alimentação Circuitos de Comando Seccionadora 89L - Disj. Q125.4 Desligado")
l_condic['101'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme10_05"], descricao="[SA]  PACP-SE - Alimentação Circuito de Bloqueio Lâmina de Terra - Disj. Q125.5 Desligado")
l_condic['102'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme10_06"], descricao="[SA]  PACP-SE - Alimentação Circuito de Comando Disjuntor 52L - Disj. Q125.6 Desligado")
l_condic['103'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme10_07"], descricao="[SA]  PACP-SE - Alimentação Motor Carregamento da Mola do Disjuntor 52L - Disj. Q125.7 Desligado")
l_condic['104'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme11_00"], descricao="[SA]  CSA-U1 - Alimentação Circuitos de Sinalização - Disj. Q125.0 Desligado")
l_condic['105'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme11_01"], descricao="[SA]  CSA-U2 - Alimentação Circuitos de Sinalização - Disj. Q125.0 Desligado")
l_condic['106'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme11_02"], descricao="[SA]  CB01 - Carregador de Baterias 01 - Disj. Q1/Q2/Q3 Desligado")
l_condic['107'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme11_03"], descricao="[SA]  CB01 - Carregador de Baterias 01 - Disj. Q1/Q2/Q3 Inconsistência")
l_condic['108'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme11_04"], descricao="[SA]  CB01 - Carregador de Baterias 01 - Disj. Q1/Q2/Q3 Trip")
l_condic['109'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme11_05"], descricao="[SA]  CB02 - Carregador de Baterias 02 - Disj. Q1/Q2/Q3 Desligado")
l_condic['110'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme11_06"], descricao="[SA]  CB02 - Carregador de Baterias 02 - Disj. Q1/Q2/Q3 Inconsistência")
l_condic['111'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme11_07"], descricao="[SA]  CB02 - Carregador de Baterias 02 - Disj. Q1/Q2/Q3 Trip")
l_condic['112'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme11_08"], descricao="[SA]  PDSA-CC - Alimentação Principal CB01 - Disj. Q125.E1 Desligado")
l_condic['113'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme11_09"], descricao="[SA]  PDSA-CC - Alimentação Principal CB01 - Disj. Q125.E1 Inconsistência")
l_condic['114'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme11_10"], descricao="[SA]  PDSA-CC - Alimentação Principal CB01 - Disj. Q125.E1 Trip")
l_condic['115'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme11_11"], descricao="[SA]  PDSA-CC - Alimentação Principal CB02 - Disj. Q125.E2 Desligado")
l_condic['116'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme11_12"], descricao="[SA]  PDSA-CC - Alimentação Principal CB02 - Disj. Q125.E2 Inconsistência")
l_condic['117'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme11_13"], descricao="[SA]  PDSA-CC - Alimentação Principal CB02 - Disj. Q125.E2 Trip")
l_condic['118'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme11_14"], descricao="[SA]  PDSA-CC - Alimentação Inversor 125Vcc/220Vca - Disj. Q125.1 Desligado")
l_condic['119'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme11_15"], descricao="[SA]  PDSA-CC - Alimentação do Painel PDSA-CA - Disj. Q125.3 Desligado")
l_condic['120'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme12_00"], descricao="[SA]  PDSA-CC - Alimentação do Rack de Comunicação - Disj. Q125.4 Desligado")
l_condic['121'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme12_04"], descricao="[SA]  PDSA-CC - Alimentação Monitor de Temperatura do TSA-01 - Disj. Q125.8 Desligado")
l_condic['122'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme12_05"], descricao="[SA]  PDSA-CC - Alimentação Monitor de Temperatura do TSA-02 - Disj. Q125.9 Desligado")
l_condic['123'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme12_06"], descricao="[SA]  PDSA-CC - Alimentação Reserva - Disj. Q125.10 Desligado")
l_condic['124'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme14_03"], descricao="[SA]  PDSA-CA - Alimentação Bomba Drenagem 01 - Disj. QM1 Desligado")
l_condic['125'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme14_04"], descricao="[SA]  PDSA-CA - Alimentação Bomba Drenagem 02 - Disj. QM2 Desligado")
l_condic['126'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme14_05"], descricao="[SA]  PDSA-CA - Alimentação Bomba Drenagem 03 - Disj. QM3 Desligado")
l_condic['127'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme14_06"], descricao="[SA]  PDSA-CA - Alimentação da Bomba de Esgotamento - Disj. QM4 Desligado")
l_condic['128'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme14_08"], descricao="[SA]  PDSA-CA - Alimentação 125Vcc Principal - Disj. Q125.0 Desligado")
l_condic['129'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme14_09"], descricao="[SA]  PDSA-CA - Alimentação 380Vca Principal - Disj. Q380.0 Desligado")
l_condic['130'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme14_10"], descricao="[SA]  PDSA-CA - Alimentação 380Vca Principal - Disj. Q380.0 Inconsistência")
l_condic['131'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme14_11"], descricao="[SA]  PDSA-CA - Alimentação 380Vca Principal - Disj. Q380.0 Trip")
l_condic['132'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme14_12"], descricao="[SA]  PDSA-CA - Alimentação do Painel PCTA - Disj. Q380.1 Desligado")
l_condic['133'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme14_13"], descricao="[SA]  PDSA-CA - Alimentação do Painel PCTA - Disj. Q380.1 Inconsistência")
l_condic['134'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme14_14"], descricao="[SA]  PDSA-CA - Alimentação do Painel PCTA - Disj. Q380.1 Trip")
l_condic['135'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme14_15"], descricao="[SA]  PDSA-CA - Alimentação da Ponte Rolante - Disj. Q380.2 Desligado")
l_condic['136'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme15_00"], descricao="[SA]  PDSA-CA - Alimentação da Ponte Rolante - Disj. Q380.2 Inconsistência")
l_condic['137'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme15_01"], descricao="[SA]  PDSA-CA - Alimentação da Ponte Rolante - Disj. Q380.2 Trip")
l_condic['138'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme15_02"], descricao="[SA]  PDSA-CA - Alimentação Monovia de Jusante - Disj. Q380.3 Desligado")
l_condic['139'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme15_03"], descricao="[SA]  PDSA-CA - Alimentação do Quadro QDLCF - Disj. Q380.4 Desligado")
l_condic['140'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme15_04"], descricao="[SA]  PDSA-CA - Alimentação do Quadro QDLCF - Disj. Q380.4 Inconsistência")
l_condic['141'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme15_05"], descricao="[SA]  PDSA-CA - Alimentação do Quadro QDLCF - Disj. Q380.4 Trip")
l_condic['142'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme15_06"], descricao="[SA]  PDSA-CA - Alimentação do Elevador da Casa de Força - Disj. Q380.5 Desligado")
l_condic['143'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme15_07"], descricao="[SA]  PDSA-CA - Alimentação do Painel PCAD - Disj. Q380.6 Desligado")
l_condic['144'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme15_08"], descricao="[SA]  PDSA-CA - Alimentação Sistema de Retrolavagem do Filtro 01 - Disj. Q380.7 Desligado")
l_condic['145'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme15_09"], descricao="[SA]  PDSA-CA - Alimentação Sistema de Retrolavagem do Filtro 02 - Disj. Q380.8 Desligado")
l_condic['146'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme15_10"], descricao="[SA]  PDSA-CA - Alimentação do Carregador de Baterias 01 - Disj. Q380.9 Desligado")
l_condic['147'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme15_11"], descricao="[SA]  PDSA-CA - Alimentação do Carregador de Baterias 02 - Disj. Q380.10 Desligado")
l_condic['148'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme16_10"], descricao="[SA]  PDSA-CA - Alimentação Bomba 01 Injeção Água Selo Mecânico - Disj. QM5 Desligado")
l_condic['149'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme16_11"], descricao="[SA]  PDSA-CA - Alimentação Bomba 02 Injeção Água Selo Mecânico - Disj. QM6 Desligado")
l_condic['150'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme16_12"], descricao="[SA]  PDSA-CA - Alimentação Bomba 01 Água Serviço - Disj. QM7 Desligado")
l_condic['151'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme16_13"], descricao="[SA]  PDSA-CA - Alimentação Bomba 02 Água Serviço - Disj. QM8 Desligado")
l_condic['152'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme16_14"], descricao="[SA]  PDSA-CA - Alimentação UCP Bombas de Drenagem - Disj. Q220.11 Desligado")
l_condic['153'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme16_15"], descricao="[SA]  PDSA-CA - Alimentação Torre de Resfriamento - Disj. Q380.11 Desligado")
l_condic['154'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme17_00"], descricao="[SA]  PDSA-CA - Alimentação Compressor de Ar - Disj. Q380.12 Desligado")
l_condic['155'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme17_01"], descricao="[SA]  PDSA-CA - Alimentação do Guincho da Bomba de Esgotamento - Disj. Q380.13 Desligado")
l_condic['156'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme17_02"], descricao="[SA]  PDSA-CA - Alimentação Alimentação do Quadro QDLSE - Disj. Q380.14 Desligado")
l_condic['157'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme17_03"], descricao="[SA]  PACP-SE - Alimentação Válvulas Sistema de Água de Refrigeração -  Disj. Q125.8 Desligado")
l_condic['158'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme17_04"], descricao="[SA]  PDSA-CC - Alimentação do Painel PINV - Disj. Q125.11 Desligado")
l_condic['159'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme17_05"], descricao="[SA]  PINV - Alimentação Boost 01 - Disj. Q125.0 Desligado")
l_condic['160'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme17_06"], descricao="[SA]  PINV - Alimentação Boost 02 - Disj. Q125.1 Desligado")
l_condic['161'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme17_07"], descricao="[SA]  PINV - Alimentação Fonte 125/24Vcc (Ventilação Forçada e Switch) - Disj. Q125.2 Desligado")
l_condic['162'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme17_09"], descricao="[SA]  Sistema de Água - Caixa D'Água 01 - Nível de água abaixo de 50%")
l_condic['163'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme17_10"], descricao="[SA]  Sistema de Água - Caixa D'Água 02 - Nível de água abaixo de 50%")
l_condic['164'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme17_11"], descricao="[SA]  PINV - Falha/Watchdog Controlador Boost 01")
l_condic['165'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme17_12"], descricao="[SA]  PINV - Falha/Watchdog Controlador Boost 02")
l_condic['166'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme17_13"], descricao="[SA]  PINV - Falta Tensão 125Vcc")
l_condic['167'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme17_14"], descricao="[SA]  PINV - Fusível Entrada Link 125Vcc Aberto")
l_condic['168'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme18_00"], descricao="[SA]  Erro de Leitura na entrada analógica do Nível de Jusante")
l_condic['169'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme18_01"], descricao="[SA]  Erro de Leitura na entrada analógica da Pressão do Sistema de Ar Comprimido")
l_condic['170'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme18_03"], descricao="[SA]  PACP-SE - Falha de Comunicação com o Controlador Boost 01 do PINV")
l_condic['171'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme18_06"], descricao="[SA]  PACP-SE - Falha de Comunicação com o Multimedidor MIB-7000C do Serviço Auxiliar")
l_condic['172'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme18_07"], descricao="[SA]  PACP-SE - Falha de Comunicação com o Grupo Diesel Ceraça ComAP")
l_condic['173'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme18_08"], descricao="[SA]  PACP-SE - Falha de Comunicação com o Carregador de Baterias 01 Modelo TPRe")
l_condic['174'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme18_09"], descricao="[SA]  PACP-SE - Falha de Comunicação com o Carregador de Baterias 02 Modelo TPRe")
l_condic['175'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme18_10"], descricao="[SA]  PACP-SE - Falha de Comunicação com o Controlador Boost 02 do PINV")
l_condic['176'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme18_11"], descricao="[SA]  Grupo Diesel - Nível de combustível menor que 30%")
l_condic['177'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme18_12"], descricao="[SA]  Grupo Diesel - Botão de Emergência Pressionado")
l_condic['178'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme19_06"], descricao="[SA]  Carregador de Baterias 01 - Sobretensão Vca Entrada do Carregador")
l_condic['179'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme19_07"], descricao="[SA]  Carregador de Baterias 01 - Subtensão Vca Entrada do Carregador")
l_condic['180'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme19_08"], descricao="[SA]  Carregador de Baterias 01 - Alarme")
l_condic['181'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme19_09"], descricao="[SA]  Carregador de Baterias 01 - Sobretensão nas Baterias")
l_condic['182'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme19_10"], descricao="[SA]  Carregador de Baterias 01 - Subtensão nas Baterias")
l_condic['183'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme19_11"], descricao="[SA]  Carregador de Baterias 01 - Sobretensão Vcc Saída do Carregador")
l_condic['184'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme19_12"], descricao="[SA]  Carregador de Baterias 01 - Subtensão Vcc Saída do Carregador")
l_condic['185'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme19_13"], descricao="[SA]  Carregador de Baterias 01 - Fuga Terra - Positivo à Terra")
l_condic['186'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme19_14"], descricao="[SA]  Carregador de Baterias 01 - Fuga Terra - Negativo à Terra")
l_condic['187'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme20_06"], descricao="[SA]  Carregador de Baterias 02 - Sobretensão Vca Entrada do Carregador")
l_condic['188'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme20_07"], descricao="[SA]  Carregador de Baterias 02 - Subtensão Vca Entrada do Carregador")
l_condic['189'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme20_08"], descricao="[SA]  Carregador de Baterias 02 - Alarme")
l_condic['190'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme20_09"], descricao="[SA]  Carregador de Baterias 02 - Sobretensão nas Baterias")
l_condic['191'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme20_10"], descricao="[SA]  Carregador de Baterias 02 - Subtensão nas Baterias")
l_condic['192'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme20_11"], descricao="[SA]  Carregador de Baterias 02 - Sobretensão Vcc Saída do Carregador")
l_condic['193'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme20_12"], descricao="[SA]  Carregador de Baterias 02 - Subtensão Vcc Saída do Carregador")
l_condic['194'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme20_13"], descricao="[SA]  Carregador de Baterias 02 - Fuga Terra - Positivo à Terra")
l_condic['195'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme20_14"], descricao="[SA]  Carregador de Baterias 02 - Fuga Terra - Negativo à Terra")
l_condic['196'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme21_03"], descricao="[SA]  Torre de Resfriamento - Trip Disjuntor Motor do Ventilador")
l_condic['197'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme21_06"], descricao="[SA]  Drenagem - Sem Fluxo de Água na Saída da Bomba 01 ")
l_condic['198'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme21_07"], descricao="[SA]  Drenagem - Sem Fluxo de Água na Saída da Bomba 02 ")
l_condic['199'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme21_08"], descricao="[SA]  Drenagem - Sem Fluxo de Água na Saída da Bomba 03  ")
l_condic['200'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme21_09"], descricao="[SA]  Injeção de Água no Selo Mecânico - Sem Fluxo de Água na Saída da Bomba 01 ")
l_condic['201'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme21_10"], descricao="[SA]  Injeção de Água no Selo Mecânico - Sem Fluxo de Água na Saída da Bomba 02")
l_condic['202'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme21_11"], descricao="[SA]  Sistema de Água de Serviço - Sem Fluxo de Água na Saída da Bomba 01")
l_condic['203'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["Alarme21_12"], descricao="[SA]  Sistema de Água de Serviço - Sem Fluxo de Água na Saída da Bomba 02")

## MENSAGEIRO
l_mensageiro['1'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["CB_LIGADO"], descricao="[SA]  Carregador Baterias 1 Ligado")
l_mensageiro['2'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["CB2_LIGADO"], descricao="[SA]  Carregador Baterias 2 Ligado")
l_mensageiro['3'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["GD_COMB_MENOR30"], descricao="[SA]  Gerador Diesel Combustivel Menor 30%")
l_mensageiro['4'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["SA_MODO_LOCAL"], descricao="[SA] Serviço Auxiliar Modo Local")
l_mensageiro['5'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["SA_MODO_MANUAL"], descricao="[SA] Serviço Auxiliar Modo Manual")
l_mensageiro['6'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["POCO_MODO_LOCAL"], descricao="[SA] Poço Modo Local")
l_mensageiro['7'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["POCO_MODO_MANUAL"], descricao="[SA] Poço Modo Manual")
l_mensageiro['8'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["POCO_NIVEL_HH"], descricao="[SA] Poço Nível Muito Alto")
l_mensageiro['9'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["SENSOR_PRESENCA_HABILITADO"], descricao="[SA] Sensor Presença Habilitado")
l_mensageiro['10'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["SENSOR_PRESENCA_SALA_SUP"], descricao="[SA] Sensor Presença Sala Supervisório")
l_mensageiro['11'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["SENSOR_PRESENCA_SALA_COZI_BANH"], descricao="[SA] Sensor Presença Sala Cozinha Banheiro")
l_mensageiro['12'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["SENSOR_PRESENCA_ALMOXARI"], descricao="[SA] Sensor Presença Almoxarifado")
l_mensageiro['13'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["SENSOR_PRESENCA_AREA_MONT"], descricao="[SA] Sensor Presença Área Montagem")
l_mensageiro['14'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["SENSOR_PRESENCA_SALA_CUBI"], descricao="[SA] Sensor Presença Sala Cubículo")
l_mensageiro['15'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["SIS_AGUA_CAIXA_AGUA01_NV50"], descricao="[SA] Sistema Água Caixa Água 1 Nível 50%")
l_mensageiro['16'] = l.LeituraModbusBit(s.Servidores.clp["SA"], REG_SA["SIS_AGUA_CAIXA_AGUA02_NV50"], descricao="[SA] Sistema Água Caixa Água 2 Nível 50%")

for c in range(len(l_condic)):
    log.debug(f"Condicionador {c+1}:")
    log.debug(f"{l_condic[f'{c+1}'].descricao}: {l_condic[f'{c+1}'].valor}")
    log.debug("")

log.debug("")

for c in range(len(l_mensageiro)):
    log.debug(f"Mensageiro {c+1}:")
    log.debug(f"{l_mensageiro[f'{c+1}'].descricao}: {l_mensageiro[f'{c+1}'].valor}")
    log.debug("")