import logging

import src.funcoes.leitura as l
import src.conectores.servidores as s

from time import sleep
from logging.config import fileConfig

from src.dicionarios.reg import *


fileConfig("/opt/operacao-autonoma/testes/log_testes.ini")
log = logging.getLogger("teste")


l_condic: "dict[str,l.LeituraModbusBit]" = {}
l_mensageiro: "dict[str,l.LeituraModbusBit]" = {}

for u in range(4):
    l_condic[f'UG{u+1}_1'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["OPER_INFO_PARADA_EMERG"], descricao=f"[UG{u+1}] Operação Parada Emergência")
    l_condic[f'UG{u+1}_2'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["OPER_INFO_PARADA_TRIP_E"], descricao=f"[UG{u+1}] Operação Parada TRIP Elétrico")
    l_condic[f'UG{u+1}_3'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["OPER_INFO_PARADA_TRIP_H"], descricao=f"[UG{u+1}] Operação Parada TRIP Hidráulico")
    l_condic[f'UG{u+1}_4'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme01_01"], descricao=f"[UG{u+1}] Botão de Emergência Pressionado (Bloqueio 86H Trip)")
    l_condic[f'UG{u+1}_5'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme02_03"], descricao=f"[UG{u+1}] UHLM - Botão de Emergência Pressionado (Bloqueio 86H Trip)")
    l_condic[f'UG{u+1}_6'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme03_08"], descricao=f"[UG{u+1}] UHCT - Botão de Emergência Pressionado (Bloqueio 86H Trip)")
    l_condic[f'UG{u+1}_7'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme05_02"], descricao=f"[UG{u+1}] Reg Tensão - TRIP (Bloqueio 86E Trip)")
    l_condic[f'UG{u+1}_8'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme05_09"], descricao=f"[UG{u+1}] Relé de Bloqueio 86M Trip Atuado ")
    l_condic[f'UG{u+1}_9'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme05_10"], descricao=f"[UG{u+1}] Relé de Bloqueio 86M Trip Atuado Temporizado")
    l_condic[f'UG{u+1}_10'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme05_11"], descricao=f"[UG{u+1}] Relé de Bloqueio 86M Trip Atuado pelo CLP")
    l_condic[f'UG{u+1}_11'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme05_12"], descricao=f"[UG{u+1}] Relé de Bloqueio 86E Trip Atuado ")
    l_condic[f'UG{u+1}_12'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme05_13"], descricao=f"[UG{u+1}] Relé de Bloqueio 86E Trip Atuado Temporizado")
    l_condic[f'UG{u+1}_13'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme05_14"], descricao=f"[UG{u+1}] Relé de Bloqueio 86E Trip Atuado pelo CLP")
    l_condic[f'UG{u+1}_14'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme05_15"], descricao=f"[UG{u+1}] Relé de Bloqueio 86H Trip Atuado")
    l_condic[f'UG{u+1}_15'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme06_00"], descricao=f"[UG{u+1}] Relé de Bloqueio 86H Trip Atuado pelo CLP")
    l_condic[f'UG{u+1}_16'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme06_03"], descricao=f"[UG{u+1}] Relé de Proteção SEL700G - TRIP")
    l_condic[f'UG{u+1}_17'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["OPER_EMERGENCIA"], descricao=f"[UG{u+1}] Operação Emergência Ligada")
    l_condic[f'UG{u+1}_18'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["OPER_INFO_PARADA_TRIP_AGUA"], descricao=f"[UG{u+1}] Operação Parada TRIP Água")
    l_condic[f'UG{u+1}_19'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["OPER_INFO_PARADA_TRIP_M"], descricao=f"[UG{u+1}] Operação Parada TRIP Mecânico")
    l_condic[f'UG{u+1}_20'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["UHCT_NIVEL_OLEO_LL"], descricao=f"[UG{u+1}] UHCT Nível Óleo Muito Baixo")
    l_condic[f'UG{u+1}_21'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["UHLM_NIVEL_OLEO_LL"], descricao=f"[UG{u+1}] UHLM Nível Óleo Muito Baixo")
    l_condic[f'UG{u+1}_22'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Dj52G_INSERIDO"], descricao=f"[UG{u+1}] Disjuntor 52G Inserido")
    l_condic[f'UG{u+1}_23'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Dj52G_FALTA_VCC"], descricao=f"[UG{u+1}] Disjuntor 52G Falta VCC")
    l_condic[f'UG{u+1}_24'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme01_00"], descricao=f"[UG{u+1}] Emergência Supervisório Pressionada (Bloqueio 86H Trip)")
    l_condic[f'UG{u+1}_25'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme01_02"], descricao=f"[UG{u+1}] Botão de Emergência Quadro Q49-U1 Pressionado (Bloqueio 86H Trip)")
    l_condic[f'UG{u+1}_26'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme01_03"], descricao=f"[UG{u+1}] PCP-U1 - Falta de Fase CA Atuado")
    l_condic[f'UG{u+1}_27'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme01_06"], descricao=f"[UG{u+1}] Falha na Transição de UP para UPGM")
    l_condic[f'UG{u+1}_28'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme01_07"], descricao=f"[UG{u+1}] Falha na Transição de UPGM para UMD ")
    l_condic[f'UG{u+1}_29'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme01_08"], descricao=f"[UG{u+1}] Falha na Transição de UMD para UPS ")
    l_condic[f'UG{u+1}_30'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme01_09"], descricao=f"[UG{u+1}] Falha na Transição de UPS para US")
    l_condic[f'UG{u+1}_31'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme01_10"], descricao=f"[UG{u+1}] Falha na Transição de US para UPS")
    l_condic[f'UG{u+1}_32'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme01_11"], descricao=f"[UG{u+1}] Falha na Transição de UPS para UMD")
    l_condic[f'UG{u+1}_33'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme01_12"], descricao=f"[UG{u+1}] Falha na Transição de UMD para UPGM")
    l_condic[f'UG{u+1}_34'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme01_13"], descricao=f"[UG{u+1}] Falha na Transição de UPGM para UP")
    l_condic[f'UG{u+1}_35'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme01_14"], descricao=f"[UG{u+1}] UHLM - Falha no Inversor da Bomba de Emergência (PINV)")
    l_condic[f'UG{u+1}_36'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme01_15"], descricao=f"[UG{u+1}] UHLM - Falta Fluxo de Água na Saída do Trocador de Calor")
    l_condic[f'UG{u+1}_37'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme02_00"], descricao=f"[UG{u+1}] UHLM - Nível de Óleo Baixo")
    l_condic[f'UG{u+1}_38'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme02_01"], descricao=f"[UG{u+1}] UHLM - Nível de Óleo Crítico (Bloqueio 86H Trip)")
    l_condic[f'UG{u+1}_39'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme02_02"], descricao=f"[UG{u+1}] UHLM - Filtro de Pressão Sujo")
    l_condic[f'UG{u+1}_40'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme02_04"], descricao=f"[UG{u+1}] UHLM - Falta Fluxo de Óleo na Bucha Radial do Mancal Combinado - Analógico")
    l_condic[f'UG{u+1}_41'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme02_05"], descricao=f"[UG{u+1}] UHLM - Falta Fluxo de Óleo na Bomba Mecânica")
    l_condic[f'UG{u+1}_42'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme02_06"], descricao=f"[UG{u+1}] UHLM - Pressão de Óleo Baixa na Linha do Mancal Combinado (Bloqueio 86M Trip)")
    l_condic[f'UG{u+1}_43'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme02_07"], descricao=f"[UG{u+1}] UHLM - Partida da Maquina Bloqueada pelo Filtro Sujo (Bloqueio 86M Trip)")
    l_condic[f'UG{u+1}_44'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme02_08"], descricao=f"[UG{u+1}] UHLM - Falha no Acionamento da Bomba 01 (CA) de Óleo")
    l_condic[f'UG{u+1}_45'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme02_09"], descricao=f"[UG{u+1}] UHLM - Falha no Acionamento da Válvula Direcional da Bomba Mecânica")
    l_condic[f'UG{u+1}_46'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme02_10"], descricao=f"[UG{u+1}] UHLM - Falha na Abertura da Válvula de Entrada de Água no Trocador de Calor")
    l_condic[f'UG{u+1}_47'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme02_11"], descricao=f"[UG{u+1}] UHLM - Falha no Fechamento da Válvula de Entrada de Água no Trocador de Calor")
    l_condic[f'UG{u+1}_48'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme02_12"], descricao=f"[UG{u+1}] UHLM - Falha na Abertura da Válvula de Saída de Água no Trocador de Calor")
    l_condic[f'UG{u+1}_49'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme02_13"], descricao=f"[UG{u+1}] UHLM - Falha no Fechamento da Válvula de Saída de Água no Trocador de Calor")
    l_condic[f'UG{u+1}_50'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme02_14"], descricao=f"[UG{u+1}] UHLM - Falta Fluxo de Óleo na Bomba 01 (CA) - Analógico")
    l_condic[f'UG{u+1}_51'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme02_15"], descricao=f"[UG{u+1}] UHLM - Falta Fluxo de Óleo na Bomba 02 (Inversor) - Analógico")
    l_condic[f'UG{u+1}_52'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme03_00"], descricao=f"[UG{u+1}] UHCT - Falha de Pressurização")
    l_condic[f'UG{u+1}_53'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme03_01"], descricao=f"[UG{u+1}] UHCT - Pressão de Desligamento (Bloqueio 86M Trip)")
    l_condic[f'UG{u+1}_54'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme03_02"], descricao=f"[UG{u+1}] UHCT - Nível de Óleo Baixo")
    l_condic[f'UG{u+1}_55'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme03_03"], descricao=f"[UG{u+1}] UHCT - Nível de Óleo Crítico (Bloqueio 86H Trip)")
    l_condic[f'UG{u+1}_56'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme03_04"], descricao=f"[UG{u+1}] UHCT - Filtro de Pressão Sujo")
    l_condic[f'UG{u+1}_57'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme03_05"], descricao=f"[UG{u+1}] UHCT - Filtro de Retorno Sujo")
    l_condic[f'UG{u+1}_58'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme03_06"], descricao=f"[UG{u+1}] UHCT - Pressão Crítica Mecânica (Bloqueio 86H Trip)")
    l_condic[f'UG{u+1}_59'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme03_07"], descricao=f"[UG{u+1}] UHCT - Pressão Crítica Eletrônica (Bloqueio 86H Trip)")
    l_condic[f'UG{u+1}_60'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme03_09"], descricao=f"[UG{u+1}] UHCT - Falha no Acionamento da Bomba de Óleo 01")
    l_condic[f'UG{u+1}_61'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme03_10"], descricao=f"[UG{u+1}] UHCT - Falha no Acionamento da Bomba de Óleo 02")
    l_condic[f'UG{u+1}_62'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme03_11"], descricao=f"[UG{u+1}] UHLM - Falha na Energização da Válvula Direcional da Bomba Mecânica com Turbina Rodando")
    l_condic[f'UG{u+1}_63'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme03_12"], descricao=f"[UG{u+1}] Turbina - Falta Fluxo de Água na Vedação do Eixo - Lado Montante")
    l_condic[f'UG{u+1}_64'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme03_13"], descricao=f"[UG{u+1}] Turbina - Falta Fluxo de Água na Vedação do Eixo - Lado Jusante")
    l_condic[f'UG{u+1}_65'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme03_14"], descricao=f"[UG{u+1}] Turbina - Sem Pressão de Água na Vedação do Eixo - Lado Montante")
    l_condic[f'UG{u+1}_66'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme03_15"], descricao=f"[UG{u+1}] Turbina - Sem Pressão de Água na Vedação do Eixo - Lado Jusante")
    l_condic[f'UG{u+1}_67'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme04_00"], descricao=f"[UG{u+1}] Turbina - Falha no Fechamento do Distribuidor")
    l_condic[f'UG{u+1}_68'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme04_01"], descricao=f"[UG{u+1}] Turbina - Pás do Distribuidor Desalinhadas (Bloqueio 86H Trip)")
    l_condic[f'UG{u+1}_69'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme04_02"], descricao=f"[UG{u+1}] Turbina - Falta Fluxo ou Pressão de Água na Vedação do Eixo (Bloqueio 86M Trip)")
    l_condic[f'UG{u+1}_70'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme04_04"], descricao=f"[UG{u+1}] Filtro de Água - Atenção! Filtro 01 em Modo Manual")
    l_condic[f'UG{u+1}_71'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme04_05"], descricao=f"[UG{u+1}] Filtro de Água - Atenção! Filtro 02 em Modo Manual")
    l_condic[f'UG{u+1}_72'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme04_06"], descricao=f"[UG{u+1}] Filtro de Água - Falha no Sistema")
    l_condic[f'UG{u+1}_73'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme04_07"], descricao=f"[UG{u+1}] Filtro de Água - Falta de Alimentação CA")
    l_condic[f'UG{u+1}_74'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme04_09"], descricao=f"[UG{u+1}] Freio - Falha na Desaplicação")
    l_condic[f'UG{u+1}_75'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme04_10"], descricao=f"[UG{u+1}] Freio - Pastilha Gasta")
    l_condic[f'UG{u+1}_76'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme04_11"], descricao=f"[UG{u+1}] Freio - Pressão Baixa")
    l_condic[f'UG{u+1}_77'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme04_12"], descricao=f"[UG{u+1}] Reg Velocidade - TRIP (Bloqueio 86H Trip)")
    l_condic[f'UG{u+1}_78'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme04_13"], descricao=f"[UG{u+1}] Reg Velocidade - Falha Watchdog (Bloqueio 86H Trip)")
    l_condic[f'UG{u+1}_79'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme04_14"], descricao=f"[UG{u+1}] Reg Velocidade - Falha na Válvula de Segurança")
    l_condic[f'UG{u+1}_80'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme04_15"], descricao=f"[UG{u+1}] Dispositivo de SobreVelocidade Mecânico Atuado (Bloqueio 86H Trip)")
    l_condic[f'UG{u+1}_81'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme05_00"], descricao=f"[UG{u+1}] Reg Velocidade - Falha Sensor de Velocidade (Bloqueio 86H Trip)")
    l_condic[f'UG{u+1}_82'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme05_03"], descricao=f"[UG{u+1}] Reg Tensão - Falha Watchdog (Bloqueio 86E Trip)")
    l_condic[f'UG{u+1}_83'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme05_04"], descricao=f"[UG{u+1}] Reg Tensão - Falha no Contator de Campo ")
    l_condic[f'UG{u+1}_84'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme05_05"], descricao=f"[UG{u+1}] Reg Tensão - Falha Painel PRT em Modo Local")
    l_condic[f'UG{u+1}_85'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme05_06"], descricao=f"[UG{u+1}] Reg Tensão - Falha Painel PRT - Disjuntor dos TPs Aberto")
    l_condic[f'UG{u+1}_86'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme05_07"], descricao=f"[UG{u+1}] GRTD 2000 - Falha no Sincronismo")
    l_condic[f'UG{u+1}_87'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme06_04"], descricao=f"[UG{u+1}] Relé de Proteção SEL700G - Falha no Disjuntor 50_62BF")
    l_condic[f'UG{u+1}_88'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme06_05"], descricao=f"[UG{u+1}] Relé de Proteção SEL700G - Falha de Hardware")
    l_condic[f'UG{u+1}_89'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme06_08"], descricao=f"[UG{u+1}] Disjuntor 52G - Inconsistência Status Aberto/Fechado")
    l_condic[f'UG{u+1}_90'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme06_09"], descricao=f"[UG{u+1}] Disjuntor 52G - Falha no Carregamento da Mola")
    l_condic[f'UG{u+1}_91'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme06_10"], descricao=f"[UG{u+1}] Disjuntor 52G - Falta Tensão de Comando Vcc")
    l_condic[f'UG{u+1}_92'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme06_11"], descricao=f"[UG{u+1}] Disjuntor 52G - Falha na Abertura")
    l_condic[f'UG{u+1}_93'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme06_12"], descricao=f"[UG{u+1}] Disjuntor 52G - Grade Frontal do CSG-U1 Aberta (Abertura 52L- SEL787)")
    l_condic[f'UG{u+1}_94'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme06_13"], descricao=f"[UG{u+1}] Disjuntor 52G - Grade Traseira do CSG-U1 Aberta (Abertura 52L - SEL787)")
    l_condic[f'UG{u+1}_95'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme06_14"], descricao=f"[UG{u+1}] Disjuntor 52G - Tampa Traseira do CSG-U1 Aberta (Abertura 52L - SEL787)")
    l_condic[f'UG{u+1}_96'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme06_15"], descricao=f"[UG{u+1}] Disjuntor 52G - Posição de Teste (Extraído)")
    l_condic[f'UG{u+1}_97'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme07_00"], descricao=f"[UG{u+1}] Controle de Potência - Falha Nível Minimo Alarme")
    l_condic[f'UG{u+1}_98'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme07_01"], descricao=f"[UG{u+1}] Controle de Potência - Falha Nível Minimo Trip 86M")
    l_condic[f'UG{u+1}_99'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme07_02"], descricao=f"[UG{u+1}] Controle de Potência - Falha Potência Minima Alarme")
    l_condic[f'UG{u+1}_100'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme07_03"], descricao=f"[UG{u+1}] Controle de Potência - Falha Potência Minima Trip 86M")
    l_condic[f'UG{u+1}_101'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme07_06"], descricao=f"[UG{u+1}] Falha no Sensor de Temperatura da Fase R do Gerador")
    l_condic[f'UG{u+1}_102'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme07_07"], descricao=f"[UG{u+1}] Falha no Sensor de Temperatura da Fase S do Gerador")
    l_condic[f'UG{u+1}_103'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme07_08"], descricao=f"[UG{u+1}] Falha no Sensor de Temperatura da Fase T do Gerador")
    l_condic[f'UG{u+1}_104'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme07_09"], descricao=f"[UG{u+1}] Falha no Sensor de Temperatura do Casquilho 01 do Mancal LA")
    l_condic[f'UG{u+1}_105'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme07_10"], descricao=f"[UG{u+1}] Falha no Sensor de Temperatura do Casquilho 02 do Mancal LA")
    l_condic[f'UG{u+1}_106'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme07_11"], descricao=f"[UG{u+1}] Falha no Sensor de Temperatura do Casquilho 01 do Mancal LNA")
    l_condic[f'UG{u+1}_107'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme07_12"], descricao=f"[UG{u+1}] Falha no Sensor de Temperatura do Casquilho 02 do Mancal LNA")
    l_condic[f'UG{u+1}_108'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme07_13"], descricao=f"[UG{u+1}] Falha no Sensor de Temperatura do Gaxeteiro Lado Montante")
    l_condic[f'UG{u+1}_109'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme07_14"], descricao=f"[UG{u+1}] Falha no Sensor de Temperatura do Gaxeteiro Lado Jusante")
    l_condic[f'UG{u+1}_110'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme07_15"], descricao=f"[UG{u+1}] Falha no Sensor de Temperatura da Bucha Radial do Mancal Combinado")
    l_condic[f'UG{u+1}_111'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme08_00"], descricao=f"[UG{u+1}] Falha no Sensor de Temperatura das Sapatas Axiais Escora do Mancal Combinado")
    l_condic[f'UG{u+1}_112'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme08_01"], descricao=f"[UG{u+1}] Falha no Sensor de Temperatura das Sapatas Axiais Contra Escora do Mancal Combinado")
    l_condic[f'UG{u+1}_113'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme08_02"], descricao=f"[UG{u+1}] Falha no Sensor de Temperatura do Óleo da UHCT")
    l_condic[f'UG{u+1}_114'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme08_03"], descricao=f"[UG{u+1}] Falha no Sensor de Temperatura do Óleo da UHLM")
    l_condic[f'UG{u+1}_115'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme08_07"], descricao=f"[UG{u+1}] Alarme de Sobretemperatura da Fase R do Gerador Via CLP")
    l_condic[f'UG{u+1}_116'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme08_08"], descricao=f"[UG{u+1}] Alarme de Sobretemperatura da Fase S do Gerador Via CLP")
    l_condic[f'UG{u+1}_117'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme08_09"], descricao=f"[UG{u+1}] Alarme de Sobretemperatura da Fase T do Gerador Via CLP")
    l_condic[f'UG{u+1}_118'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme08_10"], descricao=f"[UG{u+1}] Alarme de Sobretemperatura do Casquilho 01 do Mancal LA Via CLP")
    l_condic[f'UG{u+1}_119'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme08_11"], descricao=f"[UG{u+1}] Alarme de Sobretemperatura do Casquilho 02 do Mancal LA Via CLP")
    l_condic[f'UG{u+1}_120'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme08_12"], descricao=f"[UG{u+1}] Alarme de Sobretemperatura do Casquilho 01 do Mancal LNA Via CLP")
    l_condic[f'UG{u+1}_121'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme08_13"], descricao=f"[UG{u+1}] Alarme de Sobretemperatura do Casquilho 02 do Mancal LNA Via CLP")
    l_condic[f'UG{u+1}_122'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme08_14"], descricao=f"[UG{u+1}] Alarme de Sobretemperatura do Gaxeteiro Lado Montante Via CLP")
    l_condic[f'UG{u+1}_123'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme08_15"], descricao=f"[UG{u+1}] Alarme de Sobretemperatura do Gaxeteiro Lado Jusante Via CLP")
    l_condic[f'UG{u+1}_124'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme09_00"], descricao=f"[UG{u+1}] Alarme de Sobretemperatura da Bucha Radial do Mancal Combinado Via CLP")
    l_condic[f'UG{u+1}_125'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme09_01"], descricao=f"[UG{u+1}] Alarme de Sobretemperatura das Sapatas Axiais Escora do Mancal Combinado Via CLP")
    l_condic[f'UG{u+1}_126'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme09_02"], descricao=f"[UG{u+1}] Alarme de Sobretemperatura das Sapatas Axiais Contra Escora do Mancal Combinado Via CLP")
    l_condic[f'UG{u+1}_127'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme09_03"], descricao=f"[UG{u+1}] Alarme de Sobretemperatura do Óleo da UHCT Via CLP")
    l_condic[f'UG{u+1}_128'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme09_04"], descricao=f"[UG{u+1}] Alarme de Sobretemperatura do Óleo da UHLM Via CLP")
    l_condic[f'UG{u+1}_129'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme09_06"], descricao=f"[UG{u+1}] Relé de Proteção - Sobretemperatura da Fase R do Gerador (Trip 86M)")
    l_condic[f'UG{u+1}_130'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme09_07"], descricao=f"[UG{u+1}] Relé de Proteção - Sobretemperatura da Fase S do Gerador (Trip 86M)")
    l_condic[f'UG{u+1}_131'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme09_08"], descricao=f"[UG{u+1}] Relé de Proteção - Sobretemperatura da Fase T do Gerador (Trip 86M)")
    l_condic[f'UG{u+1}_132'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme09_09"], descricao=f"[UG{u+1}] Relé de Proteção - Sobretemperatura do Casquilho 01 do Mancal LA (Trip 86M)")
    l_condic[f'UG{u+1}_133'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme09_10"], descricao=f"[UG{u+1}] Relé de Proteção - Sobretemperatura do Casquilho 02 do Mancal LA (Trip 86M)")
    l_condic[f'UG{u+1}_134'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme09_11"], descricao=f"[UG{u+1}] Relé de Proteção - Sobretemperatura do Casquilho 01 do Mancal LNA (Trip 86M)")
    l_condic[f'UG{u+1}_135'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme09_12"], descricao=f"[UG{u+1}] Relé de Proteção - Sobretemperatura do Casquilho 02 do Mancal LNA (Trip 86M)")
    l_condic[f'UG{u+1}_136'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme09_13"], descricao=f"[UG{u+1}] Relé de Proteção - Sobretemperatura do Gaxeteiro Lado Montante (Trip 86M)")
    l_condic[f'UG{u+1}_137'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme09_14"], descricao=f"[UG{u+1}] Relé de Proteção - Sobretemperatura do Gaxeteiro Lado Jusante (Trip 86M)")
    l_condic[f'UG{u+1}_138'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme09_15"], descricao=f"[UG{u+1}] Relé de Proteção - Sobretemperatura da Bucha Radial do Mancal Combinado (Trip 86M)")
    l_condic[f'UG{u+1}_139'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme10_00"], descricao=f"[UG{u+1}] Relé de Proteção - Sobretemperatura das Sapatas Axiais Escora do Mancal Combinado (Trip 86M)")
    l_condic[f'UG{u+1}_140'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme10_01"], descricao=f"[UG{u+1}] Relé de Proteção - Sobretemperatura das Sapatas Axiais Contra Escora do Mancal Combinado (Trip 86M)")
    l_condic[f'UG{u+1}_141'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme10_02"], descricao=f"[UG{u+1}] Sobretemperatura do Óleo da UHCT (Trip 86M via CLP)")
    l_condic[f'UG{u+1}_142'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme10_03"], descricao=f"[UG{u+1}] Sobretemperatura do Óleo da UHLM (Trip 86M via CLP)")
    l_condic[f'UG{u+1}_143'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme10_05"], descricao=f"[UG{u+1}] Relé de Proteção - Sobretemperatura da Fase R do Gerador (Trip 86E)")
    l_condic[f'UG{u+1}_144'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme10_06"], descricao=f"[UG{u+1}] Relé de Proteção - Sobretemperatura da Fase S do Gerador (Trip 86E)")
    l_condic[f'UG{u+1}_145'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme10_07"], descricao=f"[UG{u+1}] Relé de Proteção - Sobretemperatura da Fase T do Gerador (Trip 86E)")
    l_condic[f'UG{u+1}_146'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme10_08"], descricao=f"[UG{u+1}] Relé de Proteção - Sobretemperatura do Casquilho 01 do Mancal LA (Trip 86H)")
    l_condic[f'UG{u+1}_147'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme10_09"], descricao=f"[UG{u+1}] Relé de Proteção - Sobretemperatura do Casquilho 02 do Mancal LA (Trip 86H)")
    l_condic[f'UG{u+1}_148'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme10_10"], descricao=f"[UG{u+1}] Relé de Proteção - Sobretemperatura do Casquilho 01 do Mancal LNA (Trip 86H)")
    l_condic[f'UG{u+1}_149'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme10_11"], descricao=f"[UG{u+1}] Relé de Proteção - Sobretemperatura do Casquilho 02 do Mancal LNA (Trip 86H)")
    l_condic[f'UG{u+1}_150'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme10_12"], descricao=f"[UG{u+1}] Relé de Proteção - Sobretemperatura do Gaxeteiro Lado Montante (Trip 86H)")
    l_condic[f'UG{u+1}_151'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme10_13"], descricao=f"[UG{u+1}] Relé de Proteção - Sobretemperatura do Gaxeteiro Lado Jusante (Trip 86H)")
    l_condic[f'UG{u+1}_152'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme10_14"], descricao=f"[UG{u+1}] Relé de Proteção - Sobretemperatura da Bucha Radial do Mancal Combinado (Trip 86H)")
    l_condic[f'UG{u+1}_153'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme10_15"], descricao=f"[UG{u+1}] Relé de Proteção - Sobretemperatura das Sapatas Axiais Escora do Mancal Combinado (Trip 86H)")
    l_condic[f'UG{u+1}_154'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme11_00"], descricao=f"[UG{u+1}] Relé de Proteção - Sobretemperatura das Sapatas Axiais Contra Escora do Mancal Combinado (Trip 86H)")
    l_condic[f'UG{u+1}_155'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme11_01"], descricao=f"[UG{u+1}] Sobretemperatura do Óleo da UHCT (Trip 86H via CLP)")
    l_condic[f'UG{u+1}_156'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme11_02"], descricao=f"[UG{u+1}] Sobretemperatura do Óleo da UHLM (Trip 86H via CLP)")
    l_condic[f'UG{u+1}_157'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme11_06"], descricao=f"[UG{u+1}] GRTD2000 - Falha na Ponte de Excitação (Bloqueio 86H Trip)")
    l_condic[f'UG{u+1}_158'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme11_07"], descricao=f"[UG{u+1}] GRTD2000 - Falha na Saída Analógica do Distribuidor (Bloqueio 86H Trip)")
    l_condic[f'UG{u+1}_159'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme11_08"], descricao=f"[UG{u+1}] GRTD2000 - Falha na Saída Analógica do Rotor (Bloqueio 86H Trip)")
    l_condic[f'UG{u+1}_160'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme11_09"], descricao=f"[UG{u+1}] GRTD2000 - Falha Realimentação de Tensão (Bloqueio 86H Trip)")
    l_condic[f'UG{u+1}_161'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme11_10"], descricao=f"[UG{u+1}] GRTD2000 - Falha Sobretensão de Excitação (Bloqueio 86H Trip)")
    l_condic[f'UG{u+1}_162'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme11_11"], descricao=f"[UG{u+1}] GRTD2000 - Falha Sobrecorrente de Excitação (Bloqueio 86H Trip)")
    l_condic[f'UG{u+1}_163'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme11_12"], descricao=f"[UG{u+1}] GRTD2000 - Falha Sobrevelocidade Eletrônica (Bloqueio 86H Trip)")
    l_condic[f'UG{u+1}_164'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme11_13"], descricao=f"[UG{u+1}] GRTD2000 - Falha na Realimentação de Velocidade (Bloqueio 86H Trip)")
    l_condic[f'UG{u+1}_165'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme11_14"], descricao=f"[UG{u+1}] GRTD2000 - Falha na Realimentação do Distribuidor (Bloqueio 86H Trip)")
    l_condic[f'UG{u+1}_166'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme11_15"], descricao=f"[UG{u+1}] GRTD2000 - Falha na Realimentação do Rotor (Bloqueio 86H Trip)")
    l_condic[f'UG{u+1}_167'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme12_01"], descricao=f"[UG{u+1}] UHLM - Falta Fluxo de Óleo na Bucha Radial do Mancal Combinado - Digital")
    l_condic[f'UG{u+1}_168'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme12_02"], descricao=f"[UG{u+1}] UHLM - Falta Fluxo de Óleo na Bomba 01 (CA) - Digital")
    l_condic[f'UG{u+1}_169'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme12_03"], descricao=f"[UG{u+1}] UHLM - Falta Fluxo de Óleo na Bomba 02 (Inversor) - Digital")
    l_condic[f'UG{u+1}_170'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme12_04"], descricao=f"[UG{u+1}] UHLM - ATENÇÃO! Tempo Excedido no Teste Bomba Retaguarda Operacional")
    l_condic[f'UG{u+1}_171'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme12_05"], descricao=f"[UG{u+1}] GRTD2000 - Falha de Comunicação com o CLP")
    l_condic[f'UG{u+1}_172'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme12_06"], descricao=f"[UG{u+1}] Relé de Proteção SEL700G - Falha de Comunicação com o CLP")
    l_condic[f'UG{u+1}_173'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme12_07"], descricao=f"[UG{u+1}] Regulador de Tensão WEG ECW500 - Falha de Comunicação com o CLP")
    l_condic[f'UG{u+1}_174'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme12_09"], descricao=f"[UG{u+1}] PCP-U1 - Alimentação Circuitos de Comando - Disjuntor Q125.0 Desligado")
    l_condic[f'UG{u+1}_175'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme12_10"], descricao=f"[UG{u+1}] PCP-U1 - Alimentação Regulador GRTD2000 - Disjuntor Q125.1 Desligado")
    l_condic[f'UG{u+1}_176'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme12_11"], descricao=f"[UG{u+1}] PCP-U1 - Alimentação Relés de Proteção - Disjuntor Q125.2 Desligado")
    l_condic[f'UG{u+1}_177'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme12_12"], descricao=f"[UG{u+1}] PCP-U1 - Alimentação Válvulas do Sistema de Água - Disjuntor Q125.4 Desligado")
    l_condic[f'UG{u+1}_178'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme12_13"], descricao=f"[UG{u+1}] PCP-U1 - Alimentação Válvulas Proporcionais e Transdutores de Posição - Disjuntor Q24.0 Desligado")
    l_condic[f'UG{u+1}_179'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme12_14"], descricao=f"[UG{u+1}] CSG-U1 - Alimentação Motor Carga Mola Disj 52G - Disjuntor Q220.1 Desligado")
    l_condic[f'UG{u+1}_180'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme12_15"], descricao=f"[UG{u+1}] CSG-U1 - Alimentação Circuito de Comando Disj 52G - Disjuntor Q125.0 Desligado")
    l_condic[f'UG{u+1}_181'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme13_00"], descricao=f"[UG{u+1}] Q49-U1 - Alimentação Módulo de Aquisição de Temperaturas SEL2600 - Disjuntor Q125.0 Desligado")
    l_condic[f'UG{u+1}_182'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme13_01"], descricao=f"[UG{u+1}] PCP-U1 - Bomba de Óleo 01 da UHCT - Disjuntor Motor QM1 Desligado")
    l_condic[f'UG{u+1}_183'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme13_02"], descricao=f"[UG{u+1}] PCP-U1 - Bomba de Óleo 02 da UHCT - Disjuntor Motor QM2 Desligado")
    l_condic[f'UG{u+1}_184'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme13_03"], descricao=f"[UG{u+1}] PCP-U1 - Bomba de Óleo da UHLM - Disjuntor Motor QM3 Desligado")
    l_condic[f'UG{u+1}_185'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme13_09"], descricao=f"[UG{u+1}] Falha na Entrada Analógica de Fluxo de Óleo na Bucha Radial do Mancal Combinado")
    l_condic[f'UG{u+1}_186'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme13_10"], descricao=f"[UG{u+1}] Falha na Entrada Analógica de Fluxo de Óleo da Bomba 01")
    l_condic[f'UG{u+1}_187'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme13_11"], descricao=f"[UG{u+1}] Falha na Entrada Analógica de Fluxo de Óleo da Bomba 02")
    l_condic[f'UG{u+1}_188'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme13_12"], descricao=f"[UG{u+1}] Falha na Entrada Analógica de Fluxo de Óleo na Bomba Mecânica")
    l_condic[f'UG{u+1}_189'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme13_13"], descricao=f"[UG{u+1}] Falha na Entrada Analógica de Vibração Vertical do Mancal Combinado da Turbina")
    l_condic[f'UG{u+1}_190'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme13_14"], descricao=f"[UG{u+1}] Falha na Entrada Analógica de Vibração Horizontal do Mancal Combinado da Turbina")
    l_condic[f'UG{u+1}_191'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme13_15"], descricao=f"[UG{u+1}] Falha na Entrada Analógica de Vibração do Mancal Combinado Axial da Turbina")
    l_condic[f'UG{u+1}_192'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme14_00"], descricao=f"[UG{u+1}] Falha na Entrada Analógica de Pressão do Conduto")
    l_condic[f'UG{u+1}_193'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme14_01"], descricao=f"[UG{u+1}] Falha na Entrada Analógica de Pressão da Turbina")
    l_condic[f'UG{u+1}_194'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme14_02"], descricao=f"[UG{u+1}] Falha na Entrada Analógica de Vibração do Mancal Lado Acoplado do Gerador")
    l_condic[f'UG{u+1}_195'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme14_03"], descricao=f"[UG{u+1}] Falha na Entrada Analógica de Vibração do Mancal Lado Não Acoplado do Gerador")
    l_condic[f'UG{u+1}_196'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme14_04"], descricao=f"[UG{u+1}] Falha na Entrada Analógica de Pressão de Óleo da UHCT")
    l_condic[f'UG{u+1}_197'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme14_05"], descricao=f"[UG{u+1}] Falha na Entrada Analógica de Temperatura do Óleo da UHCT")
    l_condic[f'UG{u+1}_198'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme14_10"], descricao=f"[UG{u+1}] PCP-U1 - Sensor de Fumaça Atuado ")
    l_condic[f'UG{u+1}_199'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme14_11"], descricao=f"[UG{u+1}] PCP-U1 - Sensor de Fumaça Desconectado")
    l_condic[f'UG{u+1}_200'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme14_12"], descricao=f"[UG{u+1}] PINV - Controlador Boost 01 - Falha Circuito de Potência/Falha Contator 1K1 ou 1K2/Falha Pré-Carga")
    l_condic[f'UG{u+1}_201'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme14_13"], descricao=f"[UG{u+1}] PINV - Controlador Boost 01 - Sub_Sobretensão ou Sub_SobreCorrente Link 540Vcc/Sub_Sobre Disparo IGBT")
    l_condic[f'UG{u+1}_202'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme14_14"], descricao=f"[UG{u+1}] PINV - Controlador Boost 02 - Falha Circuito de Potência/Falha Contator 1K1 ou 1K2/Falha Pré-Carga")
    l_condic[f'UG{u+1}_203'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme14_15"], descricao=f"[UG{u+1}] PINV - Controlador Boost 02 - Sub_Sobretensão ou Sub_SobreCorrente Link 540Vcc/Sub_Sobre Disparo IGBT")
    l_condic[f'UG{u+1}_204'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme15_00"], descricao=f"[UG{u+1}] Alarme Vibração Vertical Excessiva Mancal Combinado da Turbina")
    l_condic[f'UG{u+1}_205'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme15_01"], descricao=f"[UG{u+1}] Trip Vibração Vertical Excessiva Mancal Combinado da Turbina (Bloqueio 86M Trip)")
    l_condic[f'UG{u+1}_206'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme15_02"], descricao=f"[UG{u+1}] Alarme Vibração Horizontal Excessiva Mancal Combinado da Turbina")
    l_condic[f'UG{u+1}_207'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme15_03"], descricao=f"[UG{u+1}] Trip Vibração Horizontal Excessiva Mancal Combinado da Turbina (Bloqueio 86M Trip)")
    l_condic[f'UG{u+1}_208'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme15_04"], descricao=f"[UG{u+1}] Alarme Vibração Axial Excessiva Mancal Combinado da Turbina")
    l_condic[f'UG{u+1}_209'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme15_05"], descricao=f"[UG{u+1}] Trip Vibração Axial Excessiva Mancal Combinado da Turbina (Bloqueio 86M Trip)")
    l_condic[f'UG{u+1}_210'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme15_06"], descricao=f"[UG{u+1}] Alarme Vibração Excessiva Mancal Lado Acoplado do Gerador ")
    l_condic[f'UG{u+1}_211'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme15_07"], descricao=f"[UG{u+1}] Trip Vibração Excessiva Mancal Lado Acoplado do Gerador (Bloqueio 86M Trip)")
    l_condic[f'UG{u+1}_212'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme15_08"], descricao=f"[UG{u+1}] Alarme Vibração Excessiva Mancal Lado Não Acoplado do Gerador")
    l_condic[f'UG{u+1}_213'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme15_09"], descricao=f"[UG{u+1}] Trip Vibração Excessiva Mancal Lado Não Acoplado do Gerador (Bloqueio 86M Trip)")
    l_condic[f'UG{u+1}_214'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme15_10"], descricao=f"[UG{u+1}] Diferencial de Nível de Água - Grade Suja TRIP")
    l_condic[f'UG{u+1}_215'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme15_12"], descricao=f"[UG{u+1}] Relé de Proteção SEL700G - Proteção Diferencial Residual (87G) (Bloqueio 86E Trip)")
    l_condic[f'UG{u+1}_216'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme15_13"], descricao=f"[UG{u+1}] Relé de Proteção SEL700G - Proteção Diferencial de Neutro (87N) (Bloqueio 86E Trip)")
    l_condic[f'UG{u+1}_217'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme15_14"], descricao=f"[UG{u+1}] Relé de Proteção SEL700G - Sobrecorrente com Restrição de Tensão (51V) (Bloqueio 86E Trip)")
    l_condic[f'UG{u+1}_218'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme15_15"], descricao=f"[UG{u+1}] Relé de Proteção SEL700G - Sobrecorrente Instantânea de Fase (50P) (Bloqueio 86E Trip)")
    l_condic[f'UG{u+1}_219'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme16_00"], descricao=f"[UG{u+1}] Relé de Proteção SEL700G - Energização Indevida (50M) (Bloqueio 86E Trip)")
    l_condic[f'UG{u+1}_220'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme16_01"], descricao=f"[UG{u+1}] Relé de Proteção SEL700G - Sobrecorrente de Sequência Negativa (46Q) (Bloqueio 86E Trip)")
    l_condic[f'UG{u+1}_221'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme16_02"], descricao=f"[UG{u+1}] Relé de Proteção SEL700G - Sobrecarga Térmica (49T) (Bloqueio 86E Trip)")
    l_condic[f'UG{u+1}_222'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme16_03"], descricao=f"[UG{u+1}] Relé de Proteção SEL700G - Sobre Excitação Volts/Hertz (24) (Bloqueio 86E Trip)")
    l_condic[f'UG{u+1}_223'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme16_04"], descricao=f"[UG{u+1}] Relé de Proteção SEL700G - Sobrecorrente Residual Instantânea (50G) (Bloqueio 86E Trip)")
    l_condic[f'UG{u+1}_224'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme16_05"], descricao=f"[UG{u+1}] Relé de Proteção SEL700G - Perda de Excitação (40Q) (Bloqueio 86E Trip)")
    l_condic[f'UG{u+1}_225'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme16_06"], descricao=f"[UG{u+1}] Relé de Proteção SEL700G - Sobrecorrente Instantânea de Neutro (50N) (Bloqueio 86E Trip)")
    l_condic[f'UG{u+1}_226'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme16_07"], descricao=f"[UG{u+1}] Relé de Proteção SEL700G - Potência Reversa (32P) (Bloqueio 86E Trip)")
    l_condic[f'UG{u+1}_227'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme16_08"], descricao=f"[UG{u+1}] Relé de Proteção SEL700G - Sobretensão de Fase (59P) (Bloqueio 86E Trip)")
    l_condic[f'UG{u+1}_228'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme16_09"], descricao=f"[UG{u+1}] Relé de Proteção SEL700G - Sobretensão Residual (59G) (Bloqueio 86E Trip)")
    l_condic[f'UG{u+1}_229'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme16_10"], descricao=f"[UG{u+1}] Relé de Proteção SEL700G - Sobrefrequência (81O) (Bloqueio 86E Trip)")
    l_condic[f'UG{u+1}_230'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme16_11"], descricao=f"[UG{u+1}] Relé de Proteção SEL700G - Falha do Disjuntor (50_62BF) (Bloqueio 86H Trip)")
    l_condic[f'UG{u+1}_231'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["Alarme16_12"], descricao=f"[UG{u+1}] Relé de Proteção SEL700G - Falha RTD's ou Falha de Comunicação com o Módulo SEL-2600 (Bloqueio 86M T)")

    l_mensageiro[f'UG{u+1}_1'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["OPER_MODO_LOCAL"], descricao=f"[UG{u+1}] Operação Modo Local Acionado")
    l_mensageiro[f'UG{u+1}_2'] = l.LeituraModbus(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["DJ_07"], descricao=f"[UG{u+1}] Q49 - Disjuntor Q125.0 UG1 - Alimentação SEL2600")
    l_mensageiro[f'UG{u+1}_3'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["UHCT_NIVEL_OLEO_L"], descricao=f"[UG{u+1}] UHCT Nível Óleo Baixo")
    l_mensageiro[f'UG{u+1}_4'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["UHCT_NIVEL_OLEO_H"], descricao=f"[UG{u+1}] UHCT Nível Óleo Alto")
    l_mensageiro[f'UG{u+1}_5'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["UHCT_NIVEL_OLEO_HH"], descricao=f"[UG{u+1}] UHCT Nível Óleo Muito Alto")
    l_mensageiro[f'UG{u+1}_6'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["UHLM_MODO_LOCAL"], descricao=f"[UG{u+1}] UHLM Modo Local Acionado")
    l_mensageiro[f'UG{u+1}_7'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["UHLM_NIVEL_OLEO_L"], descricao=f"[UG{u+1}] UHLM Nível Óleo Baixo")
    l_mensageiro[f'UG{u+1}_8'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["UHLM_NIVEL_OLEO_H"], descricao=f"[UG{u+1}] UHLM Nível Óleo Alto")
    l_mensageiro[f'UG{u+1}_9'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["UHLM_NIVEL_OLEO_HH"], descricao=f"[UG{u+1}] UHLM Nível Óleo Muito Alto")
    l_mensageiro[f'UG{u+1}_10'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["TURB_SENS_DESATIVADO"], descricao=f"[UG{u+1}] Turbina Sensor Desativado")
    l_mensageiro[f'UG{u+1}_11'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["TURB_FRENA_MANUAL"], descricao=f"[UG{u+1}] Turbina Frenagem Manual")
    l_mensageiro[f'UG{u+1}_12'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["REG_V_CTRL_MANUAL_DISTRI"], descricao=f"[UG{u+1}] RV Controle Manual Distribuidor")
    l_mensageiro[f'UG{u+1}_13'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["REG_V_CTRL_MANUAL_VALV"], descricao=f"[UG{u+1}] RV Controle Manual Válvula")
    l_mensageiro[f'UG{u+1}_14'] = l.LeituraModbusBit(s.Servidores.clp[f"UG{u+1}"], REG_UG[f"UG{u+1}"]["SINC_MODO_MANUAL"], descricao=f"[UG{u+1}] Sincronoscópio Modo Manual")

for u in range(4):
    for c in range(230):
        log.debug(f"[UG{u+1}] Condicionador {c+1}:")
        log.debug(f"{l_condic[f'UG{u+1}_{c+1}'].descricao}: {l_condic[f'UG{u+1}_{c+1}'].valor}")
        log.debug("")

    for c in range(13):
        log.debug(f"[UG{u+1}] Mensageiro {c+1}:")
        log.debug(f"{l_mensageiro[f'UG{u+1}_{c+1}'].descricao}: {l_mensageiro[f'UG{u+1}_{c+1}'].valor}")
        log.debug("")

    log.debug("")
    log.debug("\"----------------------------------------------------------------------------------------------------------------------------------------\"")
    log.debug("")
