# Generated by Django 2.2.12 on 2024-03-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(default='', max_length=250)),
                ('numero', models.CharField(default='', max_length=20)),
                ('data_inicio', models.DateField(default=0)),
                ('ts_inicio', models.TimeField(default=0)),
                ('data_fim', models.DateField(default=0)),
                ('ts_fim', models.TimeField(default=0)),
            ],
        ),
    ]
