# Generated by Django 4.2.11 on 2024-05-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=250)),
                ('numero', models.CharField(default='', max_length=20)),
                ('data_inicio', models.DateField(default=0)),
                ('ts_inicio', models.TimeField(default=0)),
                ('data_fim', models.DateField(default=0)),
                ('ts_fim', models.TimeField(default=0)),
            ],
        ),
    ]
