# Generated by Django 3.1.5 on 2021-02-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comando',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('numero', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ParametrosUsina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_autonomo', models.IntegerField()),
                ('status_moa', models.IntegerField()),
                ('emergencia_acionada', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('aguardando_reservatorio', models.IntegerField()),
                ('clp_online', models.IntegerField()),
                ('clp_ip', models.CharField(max_length=15)),
                ('clp_porta', models.IntegerField()),
                ('modbus_server_ip', models.CharField(max_length=15)),
                ('modbus_server_porta', models.IntegerField()),
                ('kp', models.DecimalField(decimal_places=15, max_digits=30)),
                ('ki', models.DecimalField(decimal_places=15, max_digits=30)),
                ('kd', models.DecimalField(decimal_places=15, max_digits=30)),
                ('kie', models.DecimalField(decimal_places=15, max_digits=30)),
                ('margem_pot_critica', models.DecimalField(decimal_places=15, max_digits=30)),
                ('n_movel_L', models.IntegerField()),
                ('n_movel_R', models.IntegerField()),
                ('nv_alvo', models.DecimalField(decimal_places=15, max_digits=30)),
                ('nv_maximo', models.DecimalField(decimal_places=15, max_digits=30)),
                ('nv_minimo', models.DecimalField(decimal_places=15, max_digits=30)),
                ('nv_montante', models.DecimalField(decimal_places=15, max_digits=30)),
                ('nv_religamento', models.DecimalField(decimal_places=15, max_digits=30)),
                ('posicao_comporta', models.IntegerField()),
                ('pot_minima', models.DecimalField(decimal_places=15, max_digits=30)),
                ('pot_nominal', models.DecimalField(decimal_places=15, max_digits=30)),
                ('pot_nominal_ug', models.DecimalField(decimal_places=15, max_digits=30)),
                ('pot_disp', models.DecimalField(decimal_places=15, max_digits=30)),
                ('timer_erro', models.IntegerField()),
                ('ug1_disp', models.DecimalField(decimal_places=15, max_digits=30)),
                ('ug1_pot', models.DecimalField(decimal_places=15, max_digits=30)),
                ('ug1_setpot', models.DecimalField(decimal_places=15, max_digits=30)),
                ('ug1_sinc', models.IntegerField()),
                ('ug1_tempo', models.IntegerField()),
                ('ug1_prioridade', models.IntegerField()),
                ('ug2_disp', models.DecimalField(decimal_places=15, max_digits=30)),
                ('ug2_pot', models.DecimalField(decimal_places=15, max_digits=30)),
                ('ug2_setpot', models.DecimalField(decimal_places=15, max_digits=30)),
                ('ug2_sinc', models.IntegerField()),
                ('ug2_tempo', models.IntegerField()),
                ('ug2_prioridade', models.IntegerField()),
                ('valor_ie_inicial', models.DecimalField(decimal_places=15, max_digits=30)),
                ('modo_de_escolha_das_ugs', models.IntegerField()),
            ],
        ),
    ]
