# Generated by Django 3.1.5 on 2021-02-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros_moa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosusina',
            name='aguardando_reservatorio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='clp_online',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ug1_sinc',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ug2_sinc',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
