# Generated by Django 3.1.5 on 2021-02-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros_moa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comando',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
