# Generated by Django 3.2.12 on 2023-04-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros_moa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosusina',
            name='tda_offline',
            field=models.IntegerField(default=0),
        ),
    ]
