# Generated by Django 2.2.12 on 2022-12-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros_moa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosusina',
            name='nv_pos_grade',
            field=models.DecimalField(decimal_places=3, default=820.8, max_digits=10),
        ),
    ]
