# Generated by Django 3.1.5 on 2021-02-03 17:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parametros_moa', '0002_auto_20210201_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosusina',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
