# Generated by Django 3.1.5 on 2021-02-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros_moa', '0002_auto_20210222_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comando',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
