# Generated by Django 3.2.12 on 2022-12-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros_moa', '0002_auto_20221214_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='pos_comporta',
            new_name='ug1_pos_comporta',
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ug2_pos_comporta',
            field=models.IntegerField(default=0),
        ),
    ]
