# Generated by Django 3.2.12 on 2023-04-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros_moa', '0003_auto_20230410_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comando',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
