# Generated by Django 3.1.5 on 2021-03-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros_moa', '0003_auto_20210222_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosusina',
            name='nv_comporta_anterior_1',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='nv_comporta_anterior_2',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='nv_comporta_anterior_3',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='nv_comporta_anterior_4',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='nv_comporta_anterior_5',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='nv_comporta_proximo_1',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='nv_comporta_proximo_2',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='nv_comporta_proximo_3',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='nv_comporta_proximo_4',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='nv_comporta_proximo_5',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='pos_comporta',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
