# Generated by Django 3.2.12 on 2022-12-15 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametros_moa', '0003_auto_20221214_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='alerta_caixa_espiral_ug1',
            new_name='alerta_pressao_turbina_ug1',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='alerta_caixa_espiral_ug2',
            new_name='alerta_pressao_turbina_ug2',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='limite_caixa_espiral_ug1',
            new_name='limite_pressao_turbina_ug1',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='limite_caixa_espiral_ug2',
            new_name='limite_pressao_turbina_ug2',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='press_cx_alvo',
            new_name='press_turbina_alvo',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='cx_ki',
            new_name='pt_ki',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='cx_kie',
            new_name='pt_kie',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='cx_kp',
            new_name='pt_kp',
        ),
    ]
