# Generated by Django 3.1.5 on 2021-02-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros_moa', '0003_parametrosusina_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosusina',
            name='emergencia_MOA',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
