# Generated by Django 2.2.12 on 2023-02-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros_moa', '0003_auto_20230210_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosusina',
            name='tda_offline',
            field=models.IntegerField(default=0),
        ),
    ]
