# Generated by Django 3.1.5 on 2021-02-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros_moa', '0004_parametrosusina_emergencia_moa'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosusina',
            name='modo_autonomo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
