# Generated by Django 2.2.12 on 2023-03-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros_moa', '0004_parametrosusina_tda_offline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrosusina',
            name='margem_pot_critica',
            field=models.DecimalField(decimal_places=5, default=0.037, max_digits=10),
        ),
    ]
