# Generated by Django 2.2.12 on 2023-05-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros_moa', '0004_parametrosusina_tda_offline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='modbus_server_ip',
            new_name='clp_moa_ip',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='clp_porta',
            new_name='clp_moa_porta',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='clp_tda_porta',
            new_name='clp_sa_porta',
        ),
        migrations.RemoveField(
            model_name='parametrosusina',
            name='alerta_caixa_espiral_ug1',
        ),
        migrations.RemoveField(
            model_name='parametrosusina',
            name='alerta_caixa_espiral_ug2',
        ),
        migrations.RemoveField(
            model_name='parametrosusina',
            name='clp_ip',
        ),
        migrations.RemoveField(
            model_name='parametrosusina',
            name='clp_tda_ip',
        ),
        migrations.RemoveField(
            model_name='parametrosusina',
            name='cx_ki',
        ),
        migrations.RemoveField(
            model_name='parametrosusina',
            name='cx_kie',
        ),
        migrations.RemoveField(
            model_name='parametrosusina',
            name='cx_kp',
        ),
        migrations.RemoveField(
            model_name='parametrosusina',
            name='limite_caixa_espiral_ug1',
        ),
        migrations.RemoveField(
            model_name='parametrosusina',
            name='limite_caixa_espiral_ug2',
        ),
        migrations.RemoveField(
            model_name='parametrosusina',
            name='modbus_server_porta',
        ),
        migrations.RemoveField(
            model_name='parametrosusina',
            name='pot_disp',
        ),
        migrations.RemoveField(
            model_name='parametrosusina',
            name='press_cx_alvo',
        ),
        migrations.RemoveField(
            model_name='parametrosusina',
            name='status_moa',
        ),
        migrations.RemoveField(
            model_name='parametrosusina',
            name='timer_erro',
        ),
        migrations.RemoveField(
            model_name='parametrosusina',
            name='ug1_disp',
        ),
        migrations.RemoveField(
            model_name='parametrosusina',
            name='ug1_sinc',
        ),
        migrations.RemoveField(
            model_name='parametrosusina',
            name='ug1_tempo',
        ),
        migrations.RemoveField(
            model_name='parametrosusina',
            name='ug2_disp',
        ),
        migrations.RemoveField(
            model_name='parametrosusina',
            name='ug2_sinc',
        ),
        migrations.RemoveField(
            model_name='parametrosusina',
            name='ug2_tempo',
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='clp_sa_ip',
            field=models.CharField(default='192.168.10.109', max_length=15),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='clp_ug1_ip',
            field=models.CharField(default='192.168.10.110', max_length=15),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='clp_ug1_porta',
            field=models.IntegerField(default=502),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='clp_ug2_ip',
            field=models.CharField(default='192.168.10.120', max_length=15),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='clp_ug2_porta',
            field=models.IntegerField(default=502),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ug1_ultimo_estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='ug2_ultimo_estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='kd',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='ki',
            field=models.DecimalField(decimal_places=3, default=0.1, max_digits=15),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='kie',
            field=models.DecimalField(decimal_places=3, default=0.1, max_digits=15),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='kp',
            field=models.DecimalField(decimal_places=3, default=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='margem_pot_critica',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='ug1_pot',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='ug1_setpot',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='ug2_pot',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='ug2_setpot',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='valor_ie_inicial',
            field=models.DecimalField(decimal_places=1, default=0.5, max_digits=10),
        ),
    ]
