# Generated by Django 2.2.12 on 2023-05-29 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametros_moa', '0005_auto_20230529_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametrosusina',
            name='tda_offline',
        ),
    ]
