# Generated by Django 3.2.12 on 2023-04-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros_moa', '0005_auto_20230315_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrosusina',
            name='valor_ie_inicial',
            field=models.DecimalField(decimal_places=1, default=0.5, max_digits=10),
        ),
    ]
