# Generated by Django 3.1.5 on 2021-02-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros_moa', '0005_parametrosusina_modo_autonomo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('numero', models.CharField(max_length=20)),
            ],
        ),
    ]
