# Generated by Django 3.1.5 on 2021-02-09 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros_moa', '0007_auto_20210208_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='emergencia_MOA',
            new_name='emergencia_django_acionada',
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='emergencia_elipse_acionada',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
