# Generated by Django 3.1.5 on 2021-03-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parametros_moa", "0007_parametrosusina_tolerancia_pot_maxima"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametrosusina",
            name="ug1_perda_grade",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="ug1_perda_grade_maxima",
            field=models.DecimalField(decimal_places=5, default=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="ug1_temp_mancal",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="ug1_temp_maxima",
            field=models.DecimalField(decimal_places=5, default=90, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="ug2_perda_grade",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="ug2_perda_grade_maxima",
            field=models.DecimalField(decimal_places=5, default=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="ug2_temp_mancal",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="ug2_temp_maxima",
            field=models.DecimalField(decimal_places=5, default=90, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="kd",
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="ki",
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="kie",
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="kp",
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="margem_pot_critica",
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="nv_alvo",
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="nv_comporta_pos_0_ant",
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="nv_comporta_pos_0_prox",
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="nv_comporta_pos_1_ant",
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="nv_comporta_pos_1_prox",
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="nv_comporta_pos_2_ant",
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="nv_comporta_pos_2_prox",
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="nv_comporta_pos_3_ant",
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="nv_comporta_pos_3_prox",
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="nv_comporta_pos_4_ant",
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="nv_comporta_pos_4_prox",
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="nv_comporta_pos_5_ant",
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="nv_comporta_pos_5_prox",
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="nv_maximo",
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="nv_minimo",
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="nv_montante",
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="nv_religamento",
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="pot_disp",
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="pot_minima",
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="pot_nominal",
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="pot_nominal_ug",
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="ug1_disp",
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="ug1_pot",
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="ug1_setpot",
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="ug2_disp",
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="ug2_pot",
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="ug2_setpot",
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="valor_ie_inicial",
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
