# Generated by Django 3.1.5 on 2021-02-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros_moa', '0008_auto_20210209_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosusina',
            name='status_moa',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
