# Generated by Django 3.1.5 on 2021-03-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros_moa', '0008_auto_20210305_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrosusina',
            name='nv_alvo',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='nv_comporta_pos_0_ant',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='nv_comporta_pos_0_prox',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='nv_comporta_pos_1_ant',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='nv_comporta_pos_1_prox',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='nv_comporta_pos_2_ant',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='nv_comporta_pos_2_prox',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='nv_comporta_pos_3_ant',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='nv_comporta_pos_3_prox',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='nv_comporta_pos_4_ant',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='nv_comporta_pos_4_prox',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='nv_comporta_pos_5_ant',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='nv_comporta_pos_5_prox',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='nv_maximo',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='nv_minimo',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='nv_montante',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='nv_religamento',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='ug1_perda_grade',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='ug1_perda_grade_maxima',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='ug1_temp_mancal',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='ug1_temp_maxima',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='ug2_perda_grade',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='ug2_perda_grade_maxima',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='ug2_temp_mancal',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='ug2_temp_maxima',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
