# Generated by Django 3.1.5 on 2021-03-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros_moa', '0009_auto_20210305_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosusina',
            name='pot_maxima_alvo',
            field=models.DecimalField(decimal_places=5, default=5, max_digits=10),
            preserve_default=False,
        ),
    ]
