# Generated by Django 3.2.6 on 2021-12-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parametros_moa", "0011_auto_20210317_1516"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametrosusina",
            name="temperatura_alerta_enrolamento_fase_r_ug1",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="temperatura_alerta_enrolamento_fase_s_ug1",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="temperatura_alerta_enrolamento_fase_t_ug1",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="temperatura_alerta_mancal_la_casquilho_ug1",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="temperatura_alerta_mancal_la_contra_escora_1_ug1",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="temperatura_alerta_mancal_la_contra_escora_2_ug1",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="temperatura_alerta_mancal_la_escora_1_ug1",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="temperatura_alerta_mancal_la_escora_2_ug1",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="temperatura_alerta_mancal_lna_casquilho_ug1",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="temperatura_limite_enrolamento_fase_r_ug1",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="temperatura_limite_enrolamento_fase_s_ug1",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="temperatura_limite_enrolamento_fase_t_ug1",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="temperatura_limite_mancal_la_casquilho_ug1",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="temperatura_limite_mancal_la_contra_escora_1_ug1",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="temperatura_limite_mancal_la_contra_escora_2_ug1",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="temperatura_limite_mancal_la_escora_1_ug1",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="temperatura_limite_mancal_la_escora_2_ug1",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="temperatura_limite_mancal_lna_casquilho_ug1",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
