# Generated by Django 3.2.6 on 2021-12-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros_moa', '0012_auto_20211213_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosusina',
            name='temperatura_alerta_enrolamento_fase_r_ug2',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='temperatura_alerta_enrolamento_fase_s_ug2',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='temperatura_alerta_enrolamento_fase_t_ug2',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='temperatura_alerta_mancal_la_casquilho_ug2',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='temperatura_alerta_mancal_la_contra_escora_1_ug2',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='temperatura_alerta_mancal_la_contra_escora_2_ug2',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='temperatura_alerta_mancal_la_escora_1_ug2',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='temperatura_alerta_mancal_la_escora_2_ug2',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='temperatura_alerta_mancal_lna_casquilho_ug2',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='temperatura_limite_enrolamento_fase_r_ug2',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='temperatura_limite_enrolamento_fase_s_ug2',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='temperatura_limite_enrolamento_fase_t_ug2',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='temperatura_limite_mancal_la_casquilho_ug2',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='temperatura_limite_mancal_la_contra_escora_1_ug2',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='temperatura_limite_mancal_la_contra_escora_2_ug2',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='temperatura_limite_mancal_la_escora_1_ug2',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='temperatura_limite_mancal_la_escora_2_ug2',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametrosusina',
            name='temperatura_limite_mancal_lna_casquilho_ug2',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
