# Generated by Django 3.2.11 on 2022-06-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parametros_moa", "0014_auto_20220329_0937"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametrosusina",
            name="temperatura_alerta_enrolamento_fase_r_ug3",
            field=models.DecimalField(decimal_places=5, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="temperatura_alerta_enrolamento_fase_s_ug3",
            field=models.DecimalField(decimal_places=5, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="temperatura_alerta_enrolamento_fase_t_ug3",
            field=models.DecimalField(decimal_places=5, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="temperatura_alerta_mancal_la_casquilho_ug3",
            field=models.DecimalField(decimal_places=5, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="temperatura_alerta_mancal_la_contra_escora_1_ug3",
            field=models.DecimalField(decimal_places=5, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="temperatura_alerta_mancal_la_contra_escora_2_ug3",
            field=models.DecimalField(decimal_places=5, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="temperatura_alerta_mancal_la_escora_1_ug3",
            field=models.DecimalField(decimal_places=5, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="temperatura_alerta_mancal_la_escora_2_ug3",
            field=models.DecimalField(decimal_places=5, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="temperatura_alerta_mancal_lna_casquilho_ug3",
            field=models.DecimalField(decimal_places=5, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="temperatura_limite_enrolamento_fase_r_ug3",
            field=models.DecimalField(decimal_places=5, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="temperatura_limite_enrolamento_fase_s_ug3",
            field=models.DecimalField(decimal_places=5, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="temperatura_limite_enrolamento_fase_t_ug3",
            field=models.DecimalField(decimal_places=5, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="temperatura_limite_mancal_la_casquilho_ug3",
            field=models.DecimalField(decimal_places=5, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="temperatura_limite_mancal_la_contra_escora_1_ug3",
            field=models.DecimalField(decimal_places=5, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="temperatura_limite_mancal_la_contra_escora_2_ug3",
            field=models.DecimalField(decimal_places=5, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="temperatura_limite_mancal_la_escora_1_ug3",
            field=models.DecimalField(decimal_places=5, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="temperatura_limite_mancal_la_escora_2_ug3",
            field=models.DecimalField(decimal_places=5, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="temperatura_limite_mancal_lna_casquilho_ug3",
            field=models.DecimalField(decimal_places=5, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="ug3_disp",
            field=models.DecimalField(decimal_places=5, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="ug3_perda_grade",
            field=models.DecimalField(decimal_places=3, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="ug3_perda_grade_alerta",
            field=models.DecimalField(decimal_places=3, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="ug3_perda_grade_maxima",
            field=models.DecimalField(decimal_places=3, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="ug3_pot",
            field=models.DecimalField(decimal_places=5, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="ug3_prioridade",
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="ug3_setpot",
            field=models.DecimalField(decimal_places=5, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="ug3_sinc",
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="ug3_temp_alerta",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="ug3_temp_mancal",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="ug3_temp_maxima",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="ug3_tempo",
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
