# Generated by Django 3.2.6 on 2023-01-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros_moa', '0014_auto_20220329_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='data_fim',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='contato',
            name='data_inicio',
            field=models.DateField(default='2023-01-01'),
        ),
        migrations.AddField(
            model_name='contato',
            name='ts_fim',
            field=models.TimeField(default='00:00:00.00'),
        ),
        migrations.AddField(
            model_name='contato',
            name='ts_inicio',
            field=models.TimeField(default='00:00:00.00'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='nome',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='contato',
            name='numero',
            field=models.CharField(default='', max_length=20),
        ),
    ]
