# Generated by Django 3.2.11 on 2022-07-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parametros_moa", "0015_auto_20220622_1502"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parametrosusina",
            name="n_movel_L",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="n_movel_R",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="nv_comporta_pos_0_ant",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="nv_comporta_pos_0_prox",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="nv_comporta_pos_1_ant",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="nv_comporta_pos_1_prox",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="nv_comporta_pos_2_ant",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="nv_comporta_pos_2_prox",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="nv_comporta_pos_3_ant",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="nv_comporta_pos_3_prox",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="nv_comporta_pos_4_ant",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="nv_comporta_pos_4_prox",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="nv_comporta_pos_5_ant",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="nv_comporta_pos_5_prox",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="pos_comporta",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="pot_maxima_alvo",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_alerta_enrolamento_fase_r_ug1",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_alerta_enrolamento_fase_r_ug2",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_alerta_enrolamento_fase_r_ug3",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_alerta_enrolamento_fase_s_ug1",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_alerta_enrolamento_fase_s_ug2",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_alerta_enrolamento_fase_s_ug3",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_alerta_enrolamento_fase_t_ug1",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_alerta_enrolamento_fase_t_ug2",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_alerta_enrolamento_fase_t_ug3",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_alerta_mancal_la_casquilho_ug1",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_alerta_mancal_la_casquilho_ug2",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_alerta_mancal_la_casquilho_ug3",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_alerta_mancal_la_contra_escora_1_ug1",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_alerta_mancal_la_contra_escora_1_ug2",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_alerta_mancal_la_contra_escora_1_ug3",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_alerta_mancal_la_contra_escora_2_ug1",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_alerta_mancal_la_contra_escora_2_ug2",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_alerta_mancal_la_contra_escora_2_ug3",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_alerta_mancal_la_escora_1_ug1",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_alerta_mancal_la_escora_1_ug2",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_alerta_mancal_la_escora_1_ug3",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_alerta_mancal_la_escora_2_ug1",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_alerta_mancal_la_escora_2_ug2",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_alerta_mancal_la_escora_2_ug3",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_alerta_mancal_lna_casquilho_ug1",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_alerta_mancal_lna_casquilho_ug2",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_alerta_mancal_lna_casquilho_ug3",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_limite_enrolamento_fase_r_ug1",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_limite_enrolamento_fase_r_ug2",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_limite_enrolamento_fase_r_ug3",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_limite_enrolamento_fase_s_ug1",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_limite_enrolamento_fase_s_ug2",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_limite_enrolamento_fase_s_ug3",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_limite_enrolamento_fase_t_ug1",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_limite_enrolamento_fase_t_ug2",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_limite_enrolamento_fase_t_ug3",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_limite_mancal_la_casquilho_ug1",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_limite_mancal_la_casquilho_ug2",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_limite_mancal_la_casquilho_ug3",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_limite_mancal_la_contra_escora_1_ug1",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_limite_mancal_la_contra_escora_1_ug2",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_limite_mancal_la_contra_escora_1_ug3",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_limite_mancal_la_contra_escora_2_ug1",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_limite_mancal_la_contra_escora_2_ug2",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_limite_mancal_la_contra_escora_2_ug3",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_limite_mancal_la_escora_1_ug1",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_limite_mancal_la_escora_1_ug2",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_limite_mancal_la_escora_1_ug3",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_limite_mancal_la_escora_2_ug1",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_limite_mancal_la_escora_2_ug2",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_limite_mancal_la_escora_2_ug3",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_limite_mancal_lna_casquilho_ug1",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_limite_mancal_lna_casquilho_ug2",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="temperatura_limite_mancal_lna_casquilho_ug3",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="tolerancia_pot_maxima",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="ug1_perda_grade",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="ug1_perda_grade_alerta",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="ug1_perda_grade_maxima",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="ug1_temp_alerta",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="ug1_temp_mancal",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="ug1_temp_maxima",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="ug2_perda_grade",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="ug2_perda_grade_alerta",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="ug2_perda_grade_maxima",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="ug2_temp_alerta",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="ug2_temp_mancal",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="ug2_temp_maxima",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="ug3_perda_grade",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="ug3_perda_grade_alerta",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="ug3_perda_grade_maxima",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="ug3_temp_alerta",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="ug3_temp_mancal",
        ),
        migrations.RemoveField(
            model_name="parametrosusina",
            name="ug3_temp_maxima",
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="alerta_temperatura_fase_r_ug1",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="alerta_temperatura_fase_r_ug2",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="alerta_temperatura_fase_r_ug3",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="alerta_temperatura_fase_s_ug1",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="alerta_temperatura_fase_s_ug2",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="alerta_temperatura_fase_s_ug3",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="alerta_temperatura_fase_t_ug1_ug1",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="alerta_temperatura_fase_t_ug2_ug2",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="alerta_temperatura_fase_t_ug3_ug3",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="alerta_temperatura_mancal_guia_contra_ug1",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="alerta_temperatura_mancal_guia_contra_ug2",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="alerta_temperatura_mancal_guia_contra_ug3",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="alerta_temperatura_mancal_guia_escora_ug1",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="alerta_temperatura_mancal_guia_escora_ug2",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="alerta_temperatura_mancal_guia_escora_ug3",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="alerta_temperatura_mancal_guia_radial_ug1",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="alerta_temperatura_mancal_guia_radial_ug2",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="alerta_temperatura_mancal_guia_radial_ug3",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="alerta_temperatura_mancal_rad_dia_1_ug1",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="alerta_temperatura_mancal_rad_dia_1_ug2",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="alerta_temperatura_mancal_rad_dia_1_ug3",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="alerta_temperatura_mancal_rad_dia_2_ug1",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="alerta_temperatura_mancal_rad_dia_2_ug2",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="alerta_temperatura_mancal_rad_dia_2_ug3",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="alerta_temperatura_mancal_rad_tra_1_ug1",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="alerta_temperatura_mancal_rad_tra_1_ug2",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="alerta_temperatura_mancal_rad_tra_1_ug3",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="alerta_temperatura_mancal_rad_tra_2_ug1",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="alerta_temperatura_mancal_rad_tra_2_ug2",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="alerta_temperatura_mancal_rad_tra_2_ug3",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="alerta_temperatura_nucleo_estator_ug1",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="alerta_temperatura_nucleo_estator_ug2",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="alerta_temperatura_nucleo_estator_ug3",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="alerta_temperatura_saida_de_ar_ug1",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="alerta_temperatura_saida_de_ar_ug2",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="alerta_temperatura_saida_de_ar_ug3",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="limite_temperatura_fase_r_ug1",
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="limite_temperatura_fase_r_ug2",
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="limite_temperatura_fase_r_ug3",
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="limite_temperatura_fase_s_ug1",
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="limite_temperatura_fase_s_ug2",
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="limite_temperatura_fase_s_ug3",
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="limite_temperatura_fase_t_ug1_ug1",
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="limite_temperatura_fase_t_ug2_ug2",
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="limite_temperatura_fase_t_ug3_ug3",
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="limite_temperatura_mancal_guia_contra_ug1",
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="limite_temperatura_mancal_guia_contra_ug2",
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="limite_temperatura_mancal_guia_contra_ug3",
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="limite_temperatura_mancal_guia_escora_ug1",
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="limite_temperatura_mancal_guia_escora_ug2",
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="limite_temperatura_mancal_guia_escora_ug3",
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="limite_temperatura_mancal_guia_radial_ug1",
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="limite_temperatura_mancal_guia_radial_ug2",
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="limite_temperatura_mancal_guia_radial_ug3",
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="limite_temperatura_mancal_rad_dia_1_ug1",
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="limite_temperatura_mancal_rad_dia_1_ug2",
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="limite_temperatura_mancal_rad_dia_1_ug3",
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="limite_temperatura_mancal_rad_dia_2_ug1",
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="limite_temperatura_mancal_rad_dia_2_ug2",
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="limite_temperatura_mancal_rad_dia_2_ug3",
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="limite_temperatura_mancal_rad_tra_1_ug1",
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="limite_temperatura_mancal_rad_tra_1_ug2",
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="limite_temperatura_mancal_rad_tra_1_ug3",
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="limite_temperatura_mancal_rad_tra_2_ug1",
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="limite_temperatura_mancal_rad_tra_2_ug2",
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="limite_temperatura_mancal_rad_tra_2_ug3",
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="limite_temperatura_nucleo_estator_ug1",
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="limite_temperatura_nucleo_estator_ug2",
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="limite_temperatura_nucleo_estator_ug3",
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="limite_temperatura_saida_de_ar_ug1",
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="limite_temperatura_saida_de_ar_ug2",
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="limite_temperatura_saida_de_ar_ug3",
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="aguardando_reservatorio",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="clp_ip",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="clp_online",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="clp_porta",
            field=models.IntegerField(default=502),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="emergencia_acionada",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="kd",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="ki",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="kie",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="kp",
            field=models.DecimalField(decimal_places=10, default=1, max_digits=15),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="margem_pot_critica",
            field=models.DecimalField(decimal_places=5, default=0.2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="modbus_server_ip",
            field=models.CharField(default="0.0.0.0", max_length=15),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="modbus_server_porta",
            field=models.IntegerField(default=5003),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="modo_autonomo",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="modo_de_escolha_das_ugs",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="nv_alvo",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="nv_maximo",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="nv_minimo",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="nv_montante",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="nv_religamento",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="pot_disp",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="pot_minima",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="pot_nominal",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="pot_nominal_ug",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="status_moa",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="timer_erro",
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="timestamp",
            field=models.DateTimeField(default=0),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="ug1_disp",
            field=models.DecimalField(decimal_places=5, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="ug1_pot",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="ug1_prioridade",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="ug1_setpot",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="ug1_sinc",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="ug1_tempo",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="ug2_disp",
            field=models.DecimalField(decimal_places=5, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="ug2_pot",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="ug2_prioridade",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="ug2_setpot",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="ug2_sinc",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="ug2_tempo",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="ug3_disp",
            field=models.DecimalField(decimal_places=5, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="ug3_pot",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="ug3_prioridade",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="ug3_setpot",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="ug3_sinc",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="ug3_tempo",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="parametrosusina",
            name="valor_ie_inicial",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
    ]
