# Generated by Django 3.2.11 on 2022-07-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parametros_moa", "0016_auto_20220707_0859"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametrosusina",
            name="alerta_caixa_espiral_ug1",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="alerta_caixa_espiral_ug2",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="alerta_caixa_espiral_ug3",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="limite_caixa_espiral_ug1",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="limite_caixa_espiral_ug2",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="parametrosusina",
            name="limite_caixa_espiral_ug3",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
