# Generated by Django 3.2.11 on 2022-07-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros_moa', '0017_auto_20220708_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrosusina',
            name='ug1_tempo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='ug2_tempo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosusina',
            name='ug3_tempo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
