# Generated by Django 3.2.11 on 2022-07-12 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametros_moa', '0018_auto_20220711_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='alerta_temperatura_fase_t_ug1_ug1',
            new_name='alerta_temperatura_fase_t_ug1',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='alerta_temperatura_fase_t_ug2_ug2',
            new_name='alerta_temperatura_fase_t_ug2',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='alerta_temperatura_fase_t_ug3_ug3',
            new_name='alerta_temperatura_fase_t_ug3',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='limite_temperatura_fase_t_ug1_ug1',
            new_name='limite_temperatura_fase_t_ug1',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='limite_temperatura_fase_t_ug2_ug2',
            new_name='limite_temperatura_fase_t_ug2',
        ),
        migrations.RenameField(
            model_name='parametrosusina',
            old_name='limite_temperatura_fase_t_ug3_ug3',
            new_name='limite_temperatura_fase_t_ug3',
        ),
    ]
