# Genéricos
INVALID = 0
CRITICAL_FAILURE = 2

ESCALA_DE_TEMPO = 1
TEMPO_CICLO_TOTAL = 50

TIMEOUT_PADRAO = 5
TIMEOUT_EMERGENCIA = 10
TIMEOUT_NORMALIZACAO = 10

# Tensão de linha
TENSAO_LINHA_BAIXA = 65550
TENSAO_LINHA_ALTA = 72450

TENSAO_VERIFICAR = 0
TENSAO_AGUARDO = 1
TENSAO_REESTABELECIDA = 2
TENSAO_FORA = 3

# Nível Montante
NIVEL_MAXIMORUM = 407.5
NIVEL_VERTIMENTO = 404.15
NIVEL_FUNDO_RESERVATORIO = 404.6

NV_FLAG_NORMAL = 0
NV_FLAG_EMERGENCIA = 1


MOA_SM_INVALIDO = 0
MOA_SM_NAO_INICIALIZADO = 1
MOA_SM_FALHA_CRITICA = 2
MOA_SM_PRONTO = 3
MOA_SM_EMERGENCIA = 4
MOA_SM_MODO_MANUAL = 5
MOA_SM_CONTROLE_ESTADOS = 6
MOA_SM_CONTROLE_RESERVATORIO = 7
MOA_SM_CONTROLE_DADOS = 8
MOA_SM_CONTROLE_AGENDAMENTOS = 9
MOA_SM_CONTROLE_TDA_OFFLINE = 10

# Modo MOA 'tabela 3'
MOA_DEACTIVATED_AUTONOMOUS_MODE = 0
MOA_ACTIVATED_AUTONOMOUS_MODE = 1

# Unidades de Geração
UNIDADE_INCONSISTENTE = 0
UNIDADE_PARANDO = 1
UNIDADE_PARADA = 2
UNIDADE_SINCRONIZANDO = 3
UNIDADE_SINCRONIZADA = 4

UNIDADE_LISTA_DE_ETAPAS = [
    UNIDADE_SINCRONIZADA,
    UNIDADE_PARANDO,
    UNIDADE_PARADA,
    UNIDADE_SINCRONIZANDO,
]
UNIDADE_DICT_ETAPAS = {}
UNIDADE_DICT_ETAPAS[UNIDADE_INCONSISTENTE] = "Unidade Inconsistente"
UNIDADE_DICT_ETAPAS[UNIDADE_PARANDO] = "Unidade Parando"
UNIDADE_DICT_ETAPAS[UNIDADE_PARADA] = "Unidade Parada"
UNIDADE_DICT_ETAPAS[UNIDADE_SINCRONIZANDO] = "Unidade Sincronizando"
UNIDADE_DICT_ETAPAS[UNIDADE_SINCRONIZADA] = "Unidade Sincronizada"

DEVE_IGNORAR = 0
DEVE_NORMALIZAR = 1
DEVE_AGUARDAR = 2
DEVE_INDISPONIBILIZAR = 3

CONDIC_STR_DCT = {}
CONDIC_STR_DCT[DEVE_IGNORAR] = "Ignorar"
CONDIC_STR_DCT[DEVE_NORMALIZAR] = "Normalizar"
CONDIC_STR_DCT[DEVE_AGUARDAR] = "Aguardar"
CONDIC_STR_DCT[DEVE_INDISPONIBILIZAR] = "Indisponibilizar"

MOA_UNIDADE_MANUAL = 0
MOA_UNIDADE_DISPONIVEL = 1
MOA_UNIDADE_RESTRITA = 2
MOA_UNIDADE_INDISPONIVEL = 3

# Agendamentos
AGENDAMENTO_INDISPONIBILIZAR = 1
AGENDAMENTO_ALTERAR_NV_ALVO = 2
AGENDAMENTO_ALTERAR_POT_LIMITE_TODAS_AS_UGS = 3
AGENDAMENTO_BAIXAR_POT_UGS_MINIMO = 4
AGENDAMENTO_NORMALIZAR_POT_UGS_MINIMO = 5

AGENDAMENTO_UG1_ALTERAR_POT_LIMITE = 102
AGENDAMENTO_UG1_FORCAR_ESTADO_DISPONIVEL = 103
AGENDAMENTO_UG1_FORCAR_ESTADO_INDISPONIVEL = 104
AGENDAMENTO_UG1_FORCAR_ESTADO_MANUAL = 105
AGENDAMENTO_UG1_FORCAR_ESTADO_RESTRITO = 106
AGENDAMENTO_UG1_TEMPO_ESPERA_RESTRITO = 107

AGENDAMENTO_UG2_ALTERAR_POT_LIMITE = 202
AGENDAMENTO_UG2_FORCAR_ESTADO_DISPONIVEL = 203
AGENDAMENTO_UG2_FORCAR_ESTADO_INDISPONIVEL = 204
AGENDAMENTO_UG2_FORCAR_ESTADO_MANUAL = 205
AGENDAMENTO_UG2_FORCAR_ESTADO_RESTRITO = 206
AGENDAMENTO_UG2_TEMPO_ESPERA_RESTRITO = 207

AGENDAMENTO_UG3_ALTERAR_POT_LIMITE = 302
AGENDAMENTO_UG3_FORCAR_ESTADO_DISPONIVEL = 303
AGENDAMENTO_UG3_FORCAR_ESTADO_INDISPONIVEL = 304
AGENDAMENTO_UG3_FORCAR_ESTADO_MANUAL = 305
AGENDAMENTO_UG3_FORCAR_ESTADO_RESTRITO = 306
AGENDAMENTO_UG3_TEMPO_ESPERA_RESTRITO = 307

MODO_ESCOLHA_MANUAL = 2

AGN_STR_DICT = {}
AGN_STR_DICT[AGENDAMENTO_INDISPONIBILIZAR] = "Indisponibilizar Usina"
AGN_STR_DICT[AGENDAMENTO_ALTERAR_NV_ALVO] = "Alterar Nível Alvo"
AGN_STR_DICT[AGENDAMENTO_ALTERAR_POT_LIMITE_TODAS_AS_UGS] = "Baixar Potênica Limite da Usina"
AGN_STR_DICT[AGENDAMENTO_BAIXAR_POT_UGS_MINIMO] = "Baixar Potência para limpeza de grades"
AGN_STR_DICT[AGENDAMENTO_NORMALIZAR_POT_UGS_MINIMO] = "Normalizar potência pós limpeza de grades"

AGN_STR_DICT[AGENDAMENTO_UG1_ALTERAR_POT_LIMITE] = "Alterar Potência Limite UG1"
AGN_STR_DICT[AGENDAMENTO_UG1_FORCAR_ESTADO_DISPONIVEL] = "Forçar Estado Disponível UG1"
AGN_STR_DICT[AGENDAMENTO_UG1_FORCAR_ESTADO_INDISPONIVEL] = "Forçar Estado Indisponível UG1"
AGN_STR_DICT[AGENDAMENTO_UG1_FORCAR_ESTADO_MANUAL] = "Forçar Estado Manual UG1"
AGN_STR_DICT[AGENDAMENTO_UG1_FORCAR_ESTADO_RESTRITO] = "Forçar Estado Restrito UG1"
AGN_STR_DICT[AGENDAMENTO_UG1_TEMPO_ESPERA_RESTRITO] = "Aguardar temporizador para normalização Restrito UG1"

AGN_STR_DICT[AGENDAMENTO_UG2_ALTERAR_POT_LIMITE] = "Alterar Potência Limite UG2"
AGN_STR_DICT[AGENDAMENTO_UG2_FORCAR_ESTADO_DISPONIVEL] = "Forçar Estado Disponível UG2"
AGN_STR_DICT[AGENDAMENTO_UG2_FORCAR_ESTADO_INDISPONIVEL] = "Forçar Estado Indisponível UG2"
AGN_STR_DICT[AGENDAMENTO_UG2_FORCAR_ESTADO_MANUAL] = "Forçar Estado Manual UG2"
AGN_STR_DICT[AGENDAMENTO_UG2_FORCAR_ESTADO_RESTRITO] = "Forçar Estado Restrito UG2"
AGN_STR_DICT[AGENDAMENTO_UG2_TEMPO_ESPERA_RESTRITO] = "Aguardar temporizador para normalização Restrito UG2"

AGN_STR_DICT[AGENDAMENTO_UG3_ALTERAR_POT_LIMITE] = "Alterar Potência Limite UG3"
AGN_STR_DICT[AGENDAMENTO_UG3_FORCAR_ESTADO_DISPONIVEL] = "Forçar Estado Disponível UG3"
AGN_STR_DICT[AGENDAMENTO_UG3_FORCAR_ESTADO_INDISPONIVEL] = "Forçar Estado Indisponível UG3"
AGN_STR_DICT[AGENDAMENTO_UG3_FORCAR_ESTADO_MANUAL] = "Forçar Estado Manual UG3"
AGN_STR_DICT[AGENDAMENTO_UG3_FORCAR_ESTADO_RESTRITO] = "Forçar Estado Restrito UG3"
AGN_STR_DICT[AGENDAMENTO_UG3_TEMPO_ESPERA_RESTRITO] = "Aguardar temporizador para normalização Restrito UG3"