# Generated by Django 4.2 on 2023-11-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarmes',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('data', models.DateTimeField(default='')),
                ('gravidade', models.IntegerField(default=0)),
                ('descricao', models.TextField(default='')),
                ('autor', models.TextField(default='')),
            ],
        ),
    ]
