# Generated by Django 4.2.5 on 2023-11-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarmes',
            fields=[
                ('data', models.DateTimeField(primary_key=True, serialize=False)),
                ('gravidade', models.IntegerField(default=0)),
                ('descricao', models.TextField(default='')),
            ],
        ),
    ]
