# Generated by Django 4.2.3 on 2023-11-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarmes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmes',
            name='autor',
            field=models.TextField(default=''),
        ),
    ]
