# Generated by Django 4.2 on 2023-06-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarmes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarmes',
            name='id',
        ),
        migrations.AlterField(
            model_name='alarmes',
            name='ts',
            field=models.IntegerField(default=0, max_length=11, primary_key=True, serialize=False),
        ),
    ]
