# Generated by Django 4.2.5 on 2024-03-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarmes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmes',
            name='autor',
            field=models.TextField(default=''),
        ),
    ]
