# Generated by Django 4.2 on 2023-06-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarmes', '0002_remove_alarmes_id_alter_alarmes_ts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmes',
            name='descricao',
            field=models.DateTimeField(),
        ),
    ]
