# Generated by Django 4.2 on 2023-06-22 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarmes', '0003_alter_alarmes_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alarmes',
            old_name='ts',
            new_name='data',
        ),
    ]
