# Generated by Django 4.2 on 2023-06-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarmes', '0004_rename_ts_alarmes_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmes',
            name='data',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='alarmes',
            name='descricao',
            field=models.TextField(default=''),
        ),
    ]
