# Generated by Django 4.2 on 2023-11-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarmes', '0005_alter_alarmes_data_alter_alarmes_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmes',
            name='autor',
            field=models.TextField(default=''),
        ),
    ]
