# Generated by Django 2.2.12 on 2024-03-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModoManual',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('partida_ug1', models.BooleanField(default=False)),
                ('parada_ug1', models.BooleanField(default=False)),
                ('modo_ug1', models.IntegerField(default=1)),
                ('partida_ug2', models.BooleanField(default=False)),
                ('parada_ug2', models.BooleanField(default=False)),
                ('modo_ug2', models.IntegerField(default=1)),
                ('comando_dj52l', models.BooleanField(default=True)),
                ('modo_comporta_1', models.IntegerField(default=0)),
                ('modo_comporta_2', models.IntegerField(default=0)),
            ],
        ),
    ]
