# Generated by Django 4.2.4 on 2023-08-02 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modo_manual', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modomanual',
            name='modo_comporta_1',
        ),
        migrations.RemoveField(
            model_name='modomanual',
            name='modo_comporta_2',
        ),
        migrations.RemoveField(
            model_name='modomanual',
            name='modo_ug2',
        ),
        migrations.RemoveField(
            model_name='modomanual',
            name='modo_ug3',
        ),
        migrations.RemoveField(
            model_name='modomanual',
            name='parada_ug2',
        ),
        migrations.RemoveField(
            model_name='modomanual',
            name='parada_ug3',
        ),
        migrations.RemoveField(
            model_name='modomanual',
            name='partida_ug2',
        ),
        migrations.RemoveField(
            model_name='modomanual',
            name='partida_ug3',
        ),
    ]
