# Generated by Django 2.2.12 on 2023-02-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComandosManual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partida_ug1', models.BooleanField(default=False)),
                ('parada_ug1', models.BooleanField(default=False)),
                ('partida_ug2', models.BooleanField(default=False)),
                ('parada_ug2', models.BooleanField(default=False)),
                ('fecha_dj52l', models.BooleanField(default=False)),
                ('abre_dj52l', models.BooleanField(default=False)),
                ('abrir_comporta1', models.BooleanField(default=False)),
                ('fechar_comporta1', models.BooleanField(default=False)),
                ('cracking_comporta1', models.BooleanField(default=False)),
                ('abrir_comporta2', models.BooleanField(default=False)),
                ('fechar_comporta2', models.BooleanField(default=False)),
                ('cracking_comporta2', models.BooleanField(default=False)),
            ],
        ),
    ]
