# Generated by Django 2.2.12 on 2023-02-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandos_manual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comandosmanual',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
