# Generated by Django 2.2.12 on 2023-02-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandos_manual', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comandosmanual',
            name='modo_ug3',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='comandosmanual',
            name='parada_ug3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comandosmanual',
            name='partida_ug3',
            field=models.BooleanField(default=False),
        ),
    ]
