# Generated by Django 2.2.12 on 2023-02-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandos_manual', '0002_auto_20230206_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='comandosmanual',
            name='forcar_manual_ug1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comandosmanual',
            name='forcar_manual_ug2',
            field=models.BooleanField(default=False),
        ),
    ]
