# Generated by Django 2.2.12 on 2023-02-07 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comandos_manual', '0003_auto_20230207_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comandosmanual',
            old_name='parada_ug1',
            new_name='partir_parar_ug1',
        ),
        migrations.RenameField(
            model_name='comandosmanual',
            old_name='parada_ug2',
            new_name='partir_parar_ug2',
        ),
        migrations.RemoveField(
            model_name='comandosmanual',
            name='partida_ug1',
        ),
        migrations.RemoveField(
            model_name='comandosmanual',
            name='partida_ug2',
        ),
    ]
