# Generated by Django 2.2.12 on 2023-02-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandos_manual', '0004_auto_20230207_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comandosmanual',
            old_name='partir_parar_ug1',
            new_name='parada_ug1',
        ),
        migrations.RenameField(
            model_name='comandosmanual',
            old_name='partir_parar_ug2',
            new_name='parada_ug2',
        ),
        migrations.AddField(
            model_name='comandosmanual',
            name='partida_ug1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comandosmanual',
            name='partida_ug2',
            field=models.BooleanField(default=False),
        ),
    ]
