# Generated by Django 2.2.12 on 2023-02-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandos_manual', '0005_auto_20230207_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comandosmanual',
            name='abre_dj52l',
        ),
        migrations.RemoveField(
            model_name='comandosmanual',
            name='fecha_dj52l',
        ),
        migrations.AddField(
            model_name='comandosmanual',
            name='comando_dj52l',
            field=models.BooleanField(default=True),
        ),
    ]
