# Generated by Django 2.2.12 on 2023-02-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandos_manual', '0006_auto_20230207_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comandosmanual',
            name='abrir_comporta1',
        ),
        migrations.RemoveField(
            model_name='comandosmanual',
            name='abrir_comporta2',
        ),
        migrations.RemoveField(
            model_name='comandosmanual',
            name='cracking_comporta1',
        ),
        migrations.RemoveField(
            model_name='comandosmanual',
            name='cracking_comporta2',
        ),
        migrations.RemoveField(
            model_name='comandosmanual',
            name='fechar_comporta1',
        ),
        migrations.RemoveField(
            model_name='comandosmanual',
            name='fechar_comporta2',
        ),
        migrations.RemoveField(
            model_name='comandosmanual',
            name='forcar_manual_ug1',
        ),
        migrations.RemoveField(
            model_name='comandosmanual',
            name='forcar_manual_ug2',
        ),
        migrations.AddField(
            model_name='comandosmanual',
            name='modo_comporta_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comandosmanual',
            name='modo_comporta_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comandosmanual',
            name='modo_ug1',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='comandosmanual',
            name='modo_ug2',
            field=models.IntegerField(default=1),
        ),
    ]
