# Generated by Django 2.2.12 on 2023-02-10 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comandos_manual', '0007_auto_20230208_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comandosmanual',
            name='modo_comporta_1',
        ),
        migrations.RemoveField(
            model_name='comandosmanual',
            name='modo_comporta_2',
        ),
        migrations.RemoveField(
            model_name='comandosmanual',
            name='parada_ug1',
        ),
        migrations.RemoveField(
            model_name='comandosmanual',
            name='parada_ug2',
        ),
        migrations.RemoveField(
            model_name='comandosmanual',
            name='partida_ug1',
        ),
        migrations.RemoveField(
            model_name='comandosmanual',
            name='partida_ug2',
        ),
    ]
