# Generated by Django 2.2.12 on 2023-02-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandos_manual', '0008_auto_20230210_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comandosmanual',
            name='comando_dj52l',
            field=models.IntegerField(default=1),
        ),
    ]
