## Dicionário de siglas

# ED -> Entradas Digitais
# RD -> Retornos Digitais
# CD -> Comandos Digitais
# EA -> Entradas Analógicas
# RA -> Retornos Analógicos
# SA -> Saídas Analógicas

UG = {}
# PARTIDA
UG["REG_UG1_CD_IniciaParada"] = 46  # Op15 (Write multiple coils)
UG["REG_UG1_CD_AbortaPartida"] = 47  # Op15 (Write multiple coils)
UG["REG_UG1_CD_AbortaSincronismo"] = 59  # Op15 (Write multiple coils)
UG["REG_UG1_COND_PART"] = 222

UG["REG_UG2_CD_IniciaParada"] = 46  # Op15 (Write multiple coils)
UG["REG_UG2_CD_AbortaPartida"] = 47  # Op15 (Write multiple coils)
UG["REG_UG2_CD_AbortaSincronismo"] = 59  # Op15 (Write multiple coils)
UG["REG_UG2_COND_PART"] = 222

UG["REG_UG3_CD_IniciaParada"] = 46  # Op15 (Write multiple coils)
UG["REG_UG3_CD_AbortaPartida"] = 47  # Op15 (Write multiple coils)
UG["REG_UG3_CD_AbortaSincronismo"] = 59  # Op15 (Write multiple coils)
UG["REG_UG3_COND_PART"] = 222

# ETAPAS
UG["REG_UG1_ED_RV_MaquinaParada"] = 0  # Op02 (Read Input Status)
UG["REG_UG1_ED_DisjGeradorFechado"] = 11  # Op02 (Read Input Status)
UG["REG_UG1_RD_PartindoEmAuto"] = 132  # Op02 (Read Input Status)
UG["REG_UG1_RD_ParandoEmAuto"] = 133  # Op02 (Read Input Status)

UG["REG_UG2_ED_RV_MaquinaParada"] = 0  # Op02 (Read Input Status)
UG["REG_UG2_ED_DisjGeradorFechado"] = 11  # Op02 (Read Input Status)
UG["REG_UG2_RD_PartindoEmAuto"] = 132  # Op02 (Read Input Status)
UG["REG_UG2_RD_ParandoEmAuto"] = 133  # Op02 (Read Input Status)

UG["REG_UG3_ED_RV_MaquinaParada"] = 0  # Op02 (Read Input Status)
UG["REG_UG3_ED_DisjGeradorFechado"] = 11  # Op02 (Read Input Status)
UG["REG_UG3_RD_PartindoEmAuto"] = 132  # Op02 (Read Input Status)
UG["REG_UG3_RD_ParandoEmAuto"] = 133  # Op02 (Read Input Status)

# POTÊNCIA
UG["REG_UG1_RA_PM_710_Potencia_Ativa"] = 45  # Op04 (Read Input Regs - 3x)
UG["REG_UG2_RA_PM_710_Potencia_Ativa"] = 45  # Op04 (Read Input Regs - 3x)
UG["REG_UG3_RA_PM_710_Potencia_Ativa"] = 45  # Op04 (Read Input Regs - 3x)

# SETPOINT
UG["REG_UG1_CD_ResetGeral"] = 0  # Op15 (Write multiple coils)
UG["REG_UG1_SA_SPPotAtiva"] = 1  # Scale - Op16 (Preset Multiple Regs - 4x)
UG["REG_UG1_CD_RV_RefRemHabilita"] = 63  # Op15 (Write multiple coils)

UG["REG_UG2_CD_ResetGeral"] = 0  # Op15 (Write multiple coils)
UG["REG_UG2_SA_SPPotAtiva"] = 1  # Scale - Op16 (Preset Multiple Regs - 4x)
UG["REG_UG2_CD_RV_RefRemHabilita"] = 63  # Op15 (Write multiple coils)

UG["REG_UG3_CD_ResetGeral"] = 0  # Op15 (Write multiple coils)
UG["REG_UG3_SA_SPPotAtiva"] = 1  # Scale - Op16 (Preset Multiple Regs - 4x)
UG["REG_UG3_CD_RV_RefRemHabilita"] = 63  # Op15 (Write multiple coils)

# HORÍMETRO
UG["REG_UG1_RA_Horimetro_Gerador"] = 51  # Op04 (Read Input Regs - 3x)
UG["REG_UG2_RA_Horimetro_Gerador"] = 51  # Op04 (Read Input Regs - 3x)
UG["REG_UG3_RA_Horimetro_Gerador"] = 51  # Op04 (Read Input Regs - 3x)
UG["REG_UG1_RA_Horimetro_Gerador_min"] = 52  # Op04 (Read Input Regs - 3x)
UG["REG_UG2_RA_Horimetro_Gerador_min"] = 52  # Op04 (Read Input Regs - 3x)
UG["REG_UG3_RA_Horimetro_Gerador_min"] = 52  # Op04 (Read Input Regs - 3x)

# TRIPS
UG["REG_UG1_ED_RV_Trip"] = 3  # Op02 (Read Input Status)
UG["REG_UG1_ED_AVR_Trip"] = 4  # Op02 (Read Input Status)
UG["REG_UG1_ED_SEL700G_Atuado"] = 18  # Op02 (Read Input Status)
UG["REG_UG1_RD_TripEletrico"] = 134  # Op02 (Read Input Status)
UG["REG_UG1_RD_TripMecanico"] = 135  # Op02 (Read Input Status)
UG["REG_UG1_CD_EmergenciaViaSuper"] = 4  # Op15 (Write multiple coils)

UG["REG_UG2_ED_RV_Trip"] = 3  # Op02 (Read Input Status)
UG["REG_UG2_ED_AVR_Trip"] = 4  # Op02 (Read Input Status)
UG["REG_UG2_ED_SEL700G_Atuado"] = 18  # Op02 (Read Input Status)
UG["REG_UG2_RD_TripEletrico"] = 134  # Op02 (Read Input Status)
UG["REG_UG2_RD_TripMecanico"] = 135  # Op02 (Read Input Status)
UG["REG_UG2_CD_EmergenciaViaSuper"] = 4  # Op15 (Write multiple coils)

UG["REG_UG3_ED_RV_Trip"] = 3  # Op02 (Read Input Status)
UG["REG_UG3_ED_AVR_Trip"] = 4  # Op02 (Read Input Status)
UG["REG_UG3_ED_SEL700G_Atuado"] = 18  # Op02 (Read Input Status)
UG["REG_UG3_RD_TripEletrico"] = 134  # Op02 (Read Input Status)
UG["REG_UG3_RD_TripMecanico"] = 135  # Op02 (Read Input Status)
UG["REG_UG3_CD_EmergenciaViaSuper"] = 4  # Op15 (Write multiple coils)

# RESET
UG["REG_UG1_CD_ResetReleBloq86H"] = 1  # Op15 (Write multiple coils)
UG["REG_UG1_CD_ResetReleBloq86M"] = 2  # Op15 (Write multiple coils)
UG["REG_UG1_CD_ResetRele700G"] = 3  # Op15 (Write multiple coils)
UG["REG_UG1_ED_ReleBloqA86HAtuado"] = 16  # Op02 (Read Input Status)
UG["REG_UG1_ED_ReleBloqA86MAtuado"] = 17  # Op02 (Read Input Status)
UG["REG_UG1_CD_Cala_Sirene"] = 61  # Op15 (Write multiple coils)
UG["REG_UG1_RD_700G_Trip"] = 197  # Op02 (Read Input Status)

UG["REG_UG2_CD_ResetReleBloq86H"] = 1  # Op15 (Write multiple coils)
UG["REG_UG2_CD_ResetReleBloq86M"] = 2  # Op15 (Write multiple coils)
UG["REG_UG2_CD_ResetRele700G"] = 3  # Op15 (Write multiple coils)
UG["REG_UG2_ED_ReleBloqA86HAtuado"] = 16  # Op02 (Read Input Status)
UG["REG_UG2_ED_ReleBloqA86MAtuado"] = 17  # Op02 (Read Input Status)
UG["REG_UG2_CD_Cala_Sirene"] = 61  # Op15 (Write multiple coils)
UG["REG_UG2_RD_700G_Trip"] = 197  # Op02 (Read Input Status)

UG["REG_UG3_CD_ResetReleBloq86H"] = 1  # Op15 (Write multiple coils)
UG["REG_UG3_CD_ResetReleBloq86M"] = 2  # Op15 (Write multiple coils)
UG["REG_UG3_CD_ResetRele700G"] = 3  # Op15 (Write multiple coils)
UG["REG_UG3_ED_ReleBloqA86HAtuado"] = 16  # Op02 (Read Input Status)
UG["REG_UG3_ED_ReleBloqA86MAtuado"] = 17  # Op02 (Read Input Status)
UG["REG_UG3_CD_Cala_Sirene"] = 61  # Op15 (Write multiple coils)
UG["REG_UG3_RD_700G_Trip"] = 197  # Op02 (Read Input Status)

# AVISOS VOIP
UG["REG_UG1_ED_FreioPastilhaGasta"] = 24  # Op02 (Read Input Status)
UG["REG_UG1_ED_FreioCmdRemoto"] = 29  # Op02 (Read Input Status)
UG["REG_UG1_ED_FiltroPresSujo75Troc"] = 37  # Op02 (Read Input Status)
UG["REG_UG1_ED_FiltroRetSujo75Troc"] = 39  # Op02 (Read Input Status)
UG["REG_UG1_ED_UHLM_Filt1PresSujo75Troc"] = 59  # Op02 (Read Input Status)
UG["REG_UG1_ED_UHLM_Filt2PresSujo75Troc"] = 61  # Op02 (Read Input Status)
UG["REG_UG1_ED_FiltroPressaoBbaMecSj75"] = 65  # Op02 (Read Input Status)
UG["REG_UG1_ED_TripPartRes"] = 82  # Op02 (Read Input Status)
UG["REG_UG1_ED_QCAUG1_Remoto"] = 88  # Op02 (Read Input Status)

UG["REG_UG2_ED_FreioPastilhaGasta"] = 24  # Op02 (Read Input Status)
UG["REG_UG2_ED_FreioCmdRemoto"] = 29  # Op02 (Read Input Status)
UG["REG_UG2_ED_FiltroPresSujo75Troc"] = 37  # Op02 (Read Input Status)
UG["REG_UG2_ED_FiltroRetSujo75Troc"] = 39  # Op02 (Read Input Status)
UG["REG_UG2_ED_UHLM_Filt1PresSujo75Troc"] = 59  # Op02 (Read Input Status)
UG["REG_UG2_ED_UHLM_Filt2PresSujo75Troc"] = 61  # Op02 (Read Input Status)
UG["REG_UG2_ED_FiltroPressaoBbaMecSj75"] = 65  # Op02 (Read Input Status)
UG["REG_UG2_ED_TripPartRes"] = 82  # Op02 (Read Input Status)

UG["REG_UG3_ED_FreioPastilhaGasta"] = 24  # Op02 (Read Input Status)
UG["REG_UG3_ED_FreioCmdRemoto"] = 29  # Op02 (Read Input Status)
UG["REG_UG3_ED_FiltroPresSujo75Troc"] = 37  # Op02 (Read Input Status)
UG["REG_UG3_ED_FiltroRetSujo75Troc"] = 39  # Op02 (Read Input Status)
UG["REG_UG3_ED_UHLM_Filt1PresSujo75Troc"] = 59  # Op02 (Read Input Status)
UG["REG_UG3_ED_UHLM_Filt2PresSujo75Troc"] = 61  # Op02 (Read Input Status)
UG["REG_UG3_ED_FiltroPressaoBbaMecSj75"] = 65  # Op02 (Read Input Status)
UG["REG_UG3_ED_TripPartRes"] = 82  # Op02 (Read Input Status)
UG["REG_UG3_ED_QCAUG3_Remoto"] = 88  # Op02 (Read Input Status)

# TEMPERATURAS
UG["REG_UG1_RA_Temperatura_01"] = 24  # Op04 (Read Input Regs - 3x)
UG["REG_UG1_RA_Temperatura_02"] = 25  # Op04 (Read Input Regs - 3x)
UG["REG_UG1_RA_Temperatura_03"] = 26  # Op04 (Read Input Regs - 3x)
UG["REG_UG1_RA_Temperatura_04"] = 27  # Op04 (Read Input Regs - 3x)
UG["REG_UG1_RA_Temperatura_05"] = 28  # Op04 (Read Input Regs - 3x)
UG["REG_UG1_RA_Temperatura_06"] = 29  # Op04 (Read Input Regs - 3x)
UG["REG_UG1_RA_Temperatura_07"] = 30  # Op04 (Read Input Regs - 3x)
UG["REG_UG1_RA_Temperatura_08"] = 31  # Op04 (Read Input Regs - 3x)
UG["REG_UG1_RA_Temperatura_09"] = 32  # Op04 (Read Input Regs - 3x)
UG["REG_UG1_RA_Temperatura_10"] = 33  # Op04 (Read Input Regs - 3x)
UG["REG_UG1_EA_TempMcGuiaRadial"] = 9  # Scale 0.1 - Op04 (Read Input Regs - 3x)
UG["REG_UG1_EA_TempMcGuiaEscora"] = 10  # Scale 0.1 - Op04 (Read Input Regs - 3x)
UG["REG_UG1_EA_TempMcGuiaContraEscora"] = 11  # Scale 0.1 - Op04 (Read Input Regs - 3x)

UG["REG_UG2_RA_Temperatura_01"] = 24  # Op04 (Read Input Regs - 3x)
UG["REG_UG2_RA_Temperatura_02"] = 25  # Op04 (Read Input Regs - 3x)
UG["REG_UG2_RA_Temperatura_03"] = 26  # Op04 (Read Input Regs - 3x)
UG["REG_UG2_RA_Temperatura_04"] = 27  # Op04 (Read Input Regs - 3x)
UG["REG_UG2_RA_Temperatura_05"] = 28  # Op04 (Read Input Regs - 3x)
UG["REG_UG2_RA_Temperatura_06"] = 29  # Op04 (Read Input Regs - 3x)
UG["REG_UG2_RA_Temperatura_07"] = 30  # Op04 (Read Input Regs - 3x)
UG["REG_UG2_RA_Temperatura_08"] = 31  # Op04 (Read Input Regs - 3x)
UG["REG_UG2_RA_Temperatura_09"] = 32  # Op04 (Read Input Regs - 3x)
UG["REG_UG2_RA_Temperatura_10"] = 33  # Op04 (Read Input Regs - 3x)
UG["REG_UG2_ED_QCAUG2_Remoto"] = 88  # Op02 (Read Input Status)
UG["REG_UG2_EA_TempMcGuiaRadial"] = 9  # Scale 0.1 - Op04 (Read Input Regs - 3x)
UG["REG_UG2_EA_TempMcGuiaEscora"] = 10  # Scale 0.1 - Op04 (Read Input Regs - 3x)
UG["REG_UG2_EA_TempMcGuiaContraEscora"] = 11  # Scale 0.1 - Op04 (Read Input Regs - 3x)

UG["REG_UG3_RA_Temperatura_01"] = 24  # Op04 (Read Input Regs - 3x)
UG["REG_UG3_RA_Temperatura_02"] = 25  # Op04 (Read Input Regs - 3x)
UG["REG_UG3_RA_Temperatura_03"] = 26  # Op04 (Read Input Regs - 3x)
UG["REG_UG3_RA_Temperatura_04"] = 27  # Op04 (Read Input Regs - 3x)
UG["REG_UG3_RA_Temperatura_05"] = 28  # Op04 (Read Input Regs - 3x)
UG["REG_UG3_RA_Temperatura_06"] = 29  # Op04 (Read Input Regs - 3x)
UG["REG_UG3_RA_Temperatura_07"] = 30  # Op04 (Read Input Regs - 3x)
UG["REG_UG3_RA_Temperatura_08"] = 31  # Op04 (Read Input Regs - 3x)
UG["REG_UG3_RA_Temperatura_09"] = 32  # Op04 (Read Input Regs - 3x)
UG["REG_UG3_RA_Temperatura_10"] = 33  # Op04 (Read Input Regs - 3x)
UG["REG_UG3_EA_TempMcGuiaRadial"] = 9  # Scale 0.1 - Op04 (Read Input Regs - 3x)
UG["REG_UG3_EA_TempMcGuiaEscora"] = 10  # Scale 0.1 - Op04 (Read Input Regs - 3x)
UG["REG_UG3_EA_TempMcGuiaContraEscora"] = 11  # Scale 0.1 - Op04 (Read Input Regs - 3x)

# CAIXA ESPIRAL
UG["REG_UG1_EA_PressK1CaixaExpiral_MaisCasas"] = 157 # Scale 0.01 - Op04 (Read Input Regs)
UG["REG_UG2_EA_PressK1CaixaExpiral_MaisCasas"] = 157 # Scale 0.01 - Op04 (Read Input Regs)
UG["REG_UG3_EA_PressK1CaixaExpiral_MaisCasas"] = 157 # Scale 0.01 - Op04 (Read Input Regs)



REG_UG1_ED_RV_VeloMenor30 = 1  # Op02 (Read Input Status)
REG_UG1_ED_RV_VeloMaior90 = 2  # Op02 (Read Input Status)

REG_UG1_ED_AVR_FalhaInterna = 5  # Op02 (Read Input Status)
REG_UG1_ED_AVR_Ligado = 6  # Op02 (Read Input Status)
REG_UG1_ED_PotenciaNula = 7  # Op02 (Read Input Status)
REG_UG1_ED_Falta125Vcc = 8  # Op02 (Read Input Status)
REG_UG1_ED_DisjGeradorInserido = 9  # Op02 (Read Input Status)
REG_UG1_ED_DisjGeradorAberto = 10  # Op02 (Read Input Status)

REG_UG1_ED_EmergPainelAtuada = 12  # Op02 (Read Input Status)
REG_UG1_ED_Falta125VccCom = 13  # Op02 (Read Input Status)
REG_UG1_ED_Falta125VccAlimVal = 14  # Op02 (Read Input Status)
REG_UG1_ED_FalhaDisjTpsProt = 15  # Op02 (Read Input Status)


REG_UG1_ED_SEL700G_FalhaInterna = 19  # Op02 (Read Input Status)
REG_UG1_ED_Falta125VccQPCUG2 = 20  # Op02 (Read Input Status)
REG_UG1_ED_Falta125VccQPCUG3 = 21  # Op02 (Read Input Status)
REG_UG1_ED_NivelMAltoPocoDren = 22  # Op02 (Read Input Status)
REG_UG1_ED_DijAlimAVRLig = 23  # Op02 (Read Input Status)

REG_UG1_ED_FreioPressNormal = 25  # Op02 (Read Input Status)
REG_UG1_ED_FreioDesaplicado = 26  # Op02 (Read Input Status)
REG_UG1_ED_FreioAplicado = 27  # Op02 (Read Input Status)
REG_UG1_ED_Reserva254 = 28  # Op02 (Read Input Status)

REG_UG1_ED_FreioFiltroSaturado = 30  # Op02 (Read Input Status)
REG_UG1_ED_FreioSemEnergia = 31  # Op02 (Read Input Status)
REG_UG1_ED_UHRV_PressCriticaPos321 = 32  # Op02 (Read Input Status)
REG_UG1_ED_UHRV_PressMinimaPos322 = 33  # Op02 (Read Input Status)
REG_UG1_ED_UHRV_PressNominalPos323 = 34  # Op02 (Read Input Status)
REG_UG1_ED_UHRV_Reserva263 = 35  # Op02 (Read Input Status)
REG_UG1_ED_UHRV_Reserva264 = 36  # Op02 (Read Input Status)

REG_UG1_ED_FiltroPresSujo100Sujo = 38  # Op02 (Read Input Status)

REG_UG1_ED_FiltroRetSujo100Sujo = 40  # Op02 (Read Input Status)
REG_UG1_ED_UHRV_NivOleoCriticoPos35 = 41  # Op02 (Read Input Status)
REG_UG1_ED_UHRV_NivOleominimoPos36 = 42  # Op02 (Read Input Status)
REG_UG1_ED_UHRV_PressaoEqual = 43  # Op02 (Read Input Status)
REG_UG1_ED_ValvBorbTravada = 44  # Op02 (Read Input Status)
REG_UG1_ED_ValvBorbDestravada = 45  # Op02 (Read Input Status)
REG_UG1_ED_ValvBorbFechada = 46  # Op02 (Read Input Status)
REG_UG1_ED_ValvBorbAberta = 47  # Op02 (Read Input Status)
REG_UG1_ED_ValvBorbADeriva = 48  # Op02 (Read Input Status)
REG_UG1_ED_ValvByPassFechada = 49  # Op02 (Read Input Status)
REG_UG1_ED_ValvByPassAberta = 50  # Op02 (Read Input Status)
REG_UG1_ED_DistribuidorFechado = 51  # Op02 (Read Input Status)
REG_UG1_ED_FluxInjAguaPos14 = 52  # Op02 (Read Input Status)
REG_UG1_ED_PresInjAguaPos15 = 53  # Op02 (Read Input Status)
REG_UG1_ED_SobreVeloMecPos18 = 54  # Op02 (Read Input Status)
REG_UG1_ED_FaltaFluxoOleoMc = 55  # Op02 (Read Input Status)
REG_UG1_ED_PalhetasDesal = 56  # Op02 (Read Input Status)
REG_UG1_ED_UHLM_FaltaFluxTroc = 57  # Op02 (Read Input Status)
REG_UG1_ED_UHLM_FaltaPressTroc = 58  # Op02 (Read Input Status)

REG_UG1_ED_UHLM_Filt1PresSujo100Sujo = 60  # Op02 (Read Input Status)

REG_UG1_ED_UHLM_Filt2PresSujo100Sujo = 62  # Op02 (Read Input Status)
REG_UG1_ED_UHLM_NivelCritOleo = 63  # Op02 (Read Input Status)
REG_UG1_ED_UHLM_NivelminOleo = 64  # Op02 (Read Input Status)

REG_UG1_ED_FiltroPressaoBbaMecSj100 = 66  # Op02 (Read Input Status)
REG_UG1_ED_FaltaFluxoBbaMec = 67  # Op02 (Read Input Status)
REG_UG1_ED_UHLM_FluxoMcDianteiro = 68  # Op02 (Read Input Status)
REG_UG1_ED_UHLM_FluxoMcTras = 69  # Op02 (Read Input Status)
REG_UG1_ED_UHLM_PressPos37 = 70  # Op02 (Read Input Status)
REG_UG1_ED_Reserva307 = 71  # Op02 (Read Input Status)
REG_UG1_ED_UHLM_Bomba1Ligada = 72  # Op02 (Read Input Status)
REG_UG1_ED_UHLM_Bomba2Ligada = 73  # Op02 (Read Input Status)
REG_UG1_ED_CompressorLigado = 74  # Op02 (Read Input Status)
REG_UG1_ED_UHRV_Bomba1Ligada = 75  # Op02 (Read Input Status)
REG_UG1_ED_UHRV_Bomba2Ligada = 76  # Op02 (Read Input Status)
REG_UG1_ED_QCAUG_Falha380VcaPainel = 77  # Op02 (Read Input Status)
REG_UG1_ED_QCAUG_Disj52A1Lig = 78  # Op02 (Read Input Status)
REG_UG1_ED_QCAUG_TripDisj52A1 = 79  # Op02 (Read Input Status)
REG_UG1_ED_UHLM_TripBomba1 = 80  # Op02 (Read Input Status)
REG_UG1_ED_UHLM_TripBomba2 = 81  # Op02 (Read Input Status)

REG_UG1_ED_UHRV_TripBomba1 = 83  # Op02 (Read Input Status)
REG_UG1_ED_UHRV_TripBomba2 = 84  # Op02 (Read Input Status)
REG_UG1_ED_TripAlimPainelFreio = 85  # Op02 (Read Input Status)
REG_UG1_ED_PainelFreioStatus = 86  # Op02 (Read Input Status)
REG_UG1_ED_QCAUG_TripDisjAgrup = 87  # Op02 (Read Input Status)

REG_UG1_RD_TensaoEstabilizada = 128  # Op02 (Read Input Status)
REG_UG1_RD_EmergenciaViaSuper = 129  # Op02 (Read Input Status)
REG_UG1_RD_SeqManual = 130  # Op02 (Read Input Status)
REG_UG1_RD_SeqAutomatica = 131  # Op02 (Read Input Status)

REG_UG1_RD_ValvSeg_Energizadas = 136  # Op02 (Read Input Status)
REG_UG1_RD_FalhaAcionAbertValvBorb = 137  # Op02 (Read Input Status)
REG_UG1_RD_FalhaAcionFechaValvBorb = 138  # Op02 (Read Input Status)
REG_UG1_RD_FalhaAcionAbertValvByPass = 139  # Op02 (Read Input Status)
REG_UG1_RD_FalhaAcionFechaValvByPass = 140  # Op02 (Read Input Status)
REG_UG1_RD_UHRV_CondOK_M1 = 141  # Op02 (Read Input Status)
REG_UG1_RD_UHRV_CondOK_M2 = 142  # Op02 (Read Input Status)
REG_UG1_RD_UHLM_CondOK_M1 = 143  # Op02 (Read Input Status)
REG_UG1_RD_UHLM_CondOK_M2 = 144  # Op02 (Read Input Status)
REG_UG1_RD_Bombas_UHRV_Ligada = 145  # Op02 (Read Input Status)
REG_UG1_RD_UHRV_FalhaAcionBbaM1 = 146  # Op02 (Read Input Status)
REG_UG1_RD_UHRV_FalhaAcionBbaM2 = 147  # Op02 (Read Input Status)
REG_UG1_RD_UHLM_FalhaAcionBbaM1 = 148  # Op02 (Read Input Status)
REG_UG1_RD_UHLM_FalhaAcionBbaM2 = 149  # Op02 (Read Input Status)
REG_UG1_RD_UHRV_PressaoOK = 150  # Op02 (Read Input Status)
REG_UG1_RD_UHRV_BbaM1Princ = 151  # Op02 (Read Input Status)
REG_UG1_RD_UHLM_BbaM1Princ = 152  # Op02 (Read Input Status)
REG_UG1_RD_Filtros_Manual = 153  # Op02 (Read Input Status)
REG_UG1_RD_FalhaAcionRT = 154  # Op02 (Read Input Status)
REG_UG1_RD_RV_CondOK = 155  # Op02 (Read Input Status)
REG_UG1_RD_RT_CondOK = 156  # Op02 (Read Input Status)
REG_UG1_RD_AVR_HabRefExterna = 157  # Op02 (Read Input Status)
REG_UG1_RD_AVR_ControleFP = 158  # Op02 (Read Input Status)
REG_UG1_RD_UHLM_Ligada = 159  # Op02 (Read Input Status)
REG_UG1_RD_Filtro1Sel = 160  # Op02 (Read Input Status)
REG_UG1_RD_Filtro2Sel = 161  # Op02 (Read Input Status)
REG_UG1_RD_FalhaAcionCompressor = 162  # Op02 (Read Input Status)
REG_UG1_RD_FalhaAcionFreio = 163  # Op02 (Read Input Status)
REG_UG1_RD_TripTempGaxeteiro = 164  # Op02 (Read Input Status)
REG_UG1_RD_TripTempMcGuiaRadial = 165  # Op02 (Read Input Status)
REG_UG1_RD_TripTempMcGuiaEscora = 166  # Op02 (Read Input Status)
REG_UG1_RD_TripTempMcGuiaContraEscora = (
    167  # Op02 (Read Input Status)
)
REG_UG1_RD_TripTempUHRV = 168  # Op02 (Read Input Status)
REG_UG1_RD_TripTempUHLM = 169  # Op02 (Read Input Status)
REG_UG1_RD_TripVibr1 = 170  # Op02 (Read Input Status)
REG_UG1_RD_TripVibr2 = 171  # Op02 (Read Input Status)
REG_UG1_RD_FalhaIbntDisjGer = 172  # Op02 (Read Input Status)
REG_UG1_RD_AbortaPartida = 173  # Op02 (Read Input Status)
REG_UG1_RD_TempoPartidaExc = 174  # Op02 (Read Input Status)
REG_UG1_RD_ValvInjArRotorLig = 175  # Op02 (Read Input Status)
REG_UG1_RD_ValvInjArRotorAuto = 176  # Op02 (Read Input Status)
REG_UG1_RD_PreCondPartidaOK = 177  # Op02 (Read Input Status)
REG_UG1_RD_PassoLigaValvSeg = 178  # Op02 (Read Input Status)
REG_UG1_RD_PassoDeslValvSeg = 179  # Op02 (Read Input Status)
REG_UG1_RD_PassoAbreValvBorb = 180  # Op02 (Read Input Status)
REG_UG1_RD_PassoFechaValvBorb = 181  # Op02 (Read Input Status)
REG_UG1_RD_PassoLigaUHRV = 182  # Op02 (Read Input Status)
REG_UG1_RD_PassoDesligaUHRV = 183  # Op02 (Read Input Status)
REG_UG1_RD_PassoLigaRT = 184  # Op02 (Read Input Status)
REG_UG1_RD_PassoDesligaRT = 185  # Op02 (Read Input Status)
REG_UG1_RD_PassoLigaRV = 186  # Op02 (Read Input Status)
REG_UG1_RD_PassoDesligaRV = 187  # Op02 (Read Input Status)
REG_UG1_RD_PassoAbreValvByPass = 188  # Op02 (Read Input Status)
REG_UG1_RD_PassoFechaValvByPass = 189  # Op02 (Read Input Status)
REG_UG1_RD_PassoLigaUHLM = 190  # Op02 (Read Input Status)
REG_UG1_RD_PassoDesligaUHLM = 191  # Op02 (Read Input Status)
REG_UG1_RD_PassoAbreDisjuntor = 192  # Op02 (Read Input Status)
REG_UG1_RD_PassoLigaFreioPara = 193  # Op02 (Read Input Status)
REG_UG1_RD_PassoDeslFreioPart = 194  # Op02 (Read Input Status)
REG_UG1_RD_PassoSincroniza = 195  # Op02 (Read Input Status)
REG_UG1_RD_700G_EN = 196  # Op02 (Read Input Status)

REG_UG1_RD_700G_TLED_01 = 198  # Op02 (Read Input Status)
REG_UG1_RD_700G_TLED_02 = 199  # Op02 (Read Input Status)
REG_UG1_RD_700G_TLED_03 = 200  # Op02 (Read Input Status)
REG_UG1_RD_700G_TLED_04 = 201  # Op02 (Read Input Status)
REG_UG1_RD_700G_TLED_05 = 202  # Op02 (Read Input Status)
REG_UG1_RD_700G_TLED_06 = 203  # Op02 (Read Input Status)
REG_UG1_RD_SincronismoHab = 204  # Op02 (Read Input Status)
REG_UG1_RD_CLP_Falha = 205  # Op02 (Read Input Status)
REG_UG1_RD_Remota_Falha = 206  # Op02 (Read Input Status)
REG_UG1_RD_PassoLigaFreioPart = 207  # Op02 (Read Input Status)
REG_UG1_RD_ArComprimPressBaixa = 208  # Op02 (Read Input Status)
REG_UG1_RD_ArComprimPressAlta = 209  # Op02 (Read Input Status)
REG_UG1_RD_PassoRetiraCarga = 210  # Op02 (Read Input Status)
REG_UG1_RD_RV_RefRemHabilitada = 211  # Op02 (Read Input Status)
REG_UG1_RD_FalhaComunG1TDA = 212  # Op02 (Read Input Status)
REG_UG1_RD_Q_Negativa = 213  # Op02 (Read Input Status)
REG_UG1_RD_UG1_StsBloqueio = 214  # Op02 (Read Input Status)
REG_UG1_RD_TripPressaoCaixaEspiral = 215  # Op02 (Read Input Status)
REG_UG1_RD_Trip_PBCE_Habilitado = 216  # Op02 (Read Input Status)
"""----------------SETPOINT------------------"""



REG_UG1_CD_AumentaTensaoRT = 7  # Op15 (Write multiple coils)
REG_UG1_CD_DiminuiTensaoRT = 8  # Op15 (Write multiple coils)
REG_UG1_CD_HabControleFP = 9  # Op15 (Write multiple coils)
REG_UG1_CD_DesabControleFP = 10  # Op15 (Write multiple coils)
REG_UG1_CD_HabRefExterna = 11  # Op15 (Write multiple coils)
REG_UG1_CD_DesHabRefExterna = 12  # Op15 (Write multiple coils)
REG_UG1_CD_AumentaFreq = 13  # Op15 (Write multiple coils)
REG_UG1_CD_DiminuiFreq = 14  # Op15 (Write multiple coils)
REG_UG1_CD_HabFiltro1 = 15  # Op15 (Write multiple coils)
REG_UG1_CD_DesabFiltro1 = 16  # Op15 (Write multiple coils)
REG_UG1_CD_HabFiltro2 = 17  # Op15 (Write multiple coils)
REG_UG1_CD_DesabFiltro2 = 18  # Op15 (Write multiple coils)
REG_UG1_CD_Filtros_Manual = 19  # Op15 (Write multiple coils)
REG_UG1_CD_Filtros_Auto = 20  # Op15 (Write multiple coils)
REG_UG1_CD_RV_Liga = 21  # Op15 (Write multiple coils)
REG_UG1_CD_RV_Desliga = 22  # Op15 (Write multiple coils)
REG_UG1_CD_RT_Liga = 23  # Op15 (Write multiple coils)
REG_UG1_CD_RT_Desliga = 24  # Op15 (Write multiple coils)
REG_UG1_CD_AbreValvBorb = 25  # Op15 (Write multiple coils)
REG_UG1_CD_FechaValvBorb = 26  # Op15 (Write multiple coils)
REG_UG1_CD_AbreValvByPass = 27  # Op15 (Write multiple coils)
REG_UG1_CD_FechaValvByPass = 28  # Op15 (Write multiple coils)
REG_UG1_CD_UHRV_LigaBbaM1 = 29  # Op15 (Write multiple coils)
REG_UG1_CD_UHRV_DesligaBbaM1 = 30  # Op15 (Write multiple coils)
REG_UG1_CD_UHRV_LigaBbaM2 = 31  # Op15 (Write multiple coils)
REG_UG1_CD_UHRV_DesligaBbaM2 = 32  # Op15 (Write multiple coils)
REG_UG1_CD_UHRV_SelM1Princ = 33  # Op15 (Write multiple coils)
REG_UG1_CD_UHRV_SelM2Princ = 34  # Op15 (Write multiple coils)
REG_UG1_CD_UHLM_LigaBbaM1 = 35  # Op15 (Write multiple coils)
REG_UG1_CD_UHLM_DesligaBbaM1 = 36  # Op15 (Write multiple coils)
REG_UG1_CD_UHLM_LigaBbaM2 = 37  # Op15 (Write multiple coils)
REG_UG1_CD_UHLM_DesligaBbaM2 = 38  # Op15 (Write multiple coils)
REG_UG1_CD_UHLM_SelM1Princ = 39  # Op15 (Write multiple coils)
REG_UG1_CD_UHLM_SelM2Princ = 40  # Op15 (Write multiple coils)
REG_UG1_CD_HabSeqAuto = 41  # Op15 (Write multiple coils)
REG_UG1_CD_HabSeqManual = 42  # Op15 (Write multiple coils)
REG_UG1_CD_Freio_Aplica = 43  # Op15 (Write multiple coils)
REG_UG1_CD_Freio_Desaplica = 44  # Op15 (Write multiple coils)


REG_UG1_CD_ValvSeg_Liga = 48  # Op15 (Write multiple coils)
REG_UG1_CD_ValvSeg_Desliga = 49  # Op15 (Write multiple coils)
REG_UG1_CD_DeslDisj52G = 50  # Op15 (Write multiple coils)
REG_UG1_CD_LigaCompressor = 51  # Op15 (Write multiple coils)
REG_UG1_CD_DeslCompressor = 52  # Op15 (Write multiple coils)
REG_UG1_CD_AbreDisj = 53  # Op15 (Write multiple coils)
REG_UG1_CD_SelValvInjRotorAuto = 54  # Op15 (Write multiple coils)
REG_UG1_CD_SelValvInjRotorManu = 55  # Op15 (Write multiple coils)
REG_UG1_CD_LigaValvInjArRotor = 56  # Op15 (Write multiple coils)
REG_UG1_CD_DeslValvInjArRotor = 57  # Op15 (Write multiple coils)
REG_UG1_CD_Sincroniza = 58  # Op15 (Write multiple coils)

REG_UG1_CD_Reset_Hori_Gerador = 60  # Op15 (Write multiple coils)

REG_UG1_CD_RV_RetiraCarga = 62  # Op15 (Write multiple coils)
"""----------------SETPOINT------------------"""
REG_UG1_CD_RV_RefRemDesabilita = 64  # Op15 (Write multiple coils)
REG_UG1_CD_Trip_PBCE_Habilita = 65  # Op15 (Write multiple coils)
REG_UG1_CD_Trip_PBCE_Desabilita = 66  # Op15 (Write multiple coils)

REG_UG1_RA_Temperatura_11 = 34  # Op04 (Read Input Regs - 3x)
REG_UG1_RA_Temperatura_12 = 35  # Op04 (Read Input Regs - 3x)
REG_UG1_RA_PM_710_Tensao_AB = 36  # Op04 (Read Input Regs - 3x)
REG_UG1_RA_PM_710_Tensao_BC = 37  # Op04 (Read Input Regs - 3x)
REG_UG1_RA_PM_710_Tensao_CA = 38  # Op04 (Read Input Regs - 3x)
REG_UG1_RA_PM_710_Corrente_A = 39  # Op04 (Read Input Regs - 3x)
REG_UG1_RA_PM_710_Corrente_B = 40  # Op04 (Read Input Regs - 3x)
REG_UG1_RA_PM_710_Corrente_C = 41  # Op04 (Read Input Regs - 3x)
REG_UG1_RA_PM_710_Frequencia = 42  # Op04 (Read Input Regs - 3x)
REG_UG1_RA_PM_710_Fator_Potencia = 43  # Op04 (Read Input Regs - 3x)
REG_UG1_RA_PM_710_Potencia_Aparente = (
    44  # Op04 (Read Input Regs - 3x)
)

REG_UG1_RA_PM_710_Potencia_Reativa = (
    46  # Op04 (Read Input Regs - 3x)
)

REG_UG1_RA_Estabiliz_Tensao = 49  # Op04 (Read Input Regs - 3x)
REG_UG1_EA_PosicaoDistribuidor = (
    0  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG1_EA_Velocidade = 1  # Scale 0.1 - Op04 (Read Input Regs - 3x)
REG_UG1_EA_Reserva01 = 2  # Scale 0.1 - Op04 (Read Input Regs - 3x)
REG_UG1_EA_Reserva02 = 3  # Scale 0.1 - Op04 (Read Input Regs - 3x)
REG_UG1_EA_PressAguaVedEixo = (
    4  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG1_EA_PressDifCaixaExpiral = (
    5  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG1_EA_PressK1CaixaExpiral = (
    6  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG1_EA_PressK1Succao = (
    7  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG1_EA_TempGaxetas = (
    8  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)

REG_UG1_EA_VibMcGuiaRadial = (
    12  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG1_EA_VibMcGuiaAxial = (
    13  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG1_EA_UHRV_TempOleo = (
    14  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG1_EA_UHRV_Pressao = (
    15  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG1_EA_UHLM_TempOleo = (
    16  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG1_EA_PressaoArComp = (
    17  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG1_EA_VazEntrOleoMcDiant = (
    18  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG1_EA_VazEntrOleoMcTras = (
    19  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG1_EA_Reserva04 = 20  # Scale 0.1 - Op04 (Read Input Regs - 3x)
REG_UG1_EA_Reserva05 = 21  # Scale 0.1 - Op04 (Read Input Regs - 3x)
REG_UG1_EA_Reserva06 = 22  # Scale 0.1 - Op04 (Read Input Regs - 3x)
REG_UG1_EA_Reserva07 = 23  # Scale 0.1 - Op04 (Read Input Regs - 3x)
REG_UG1_SA_Reserva01 = 0  # Scale - Op16 (Preset Multiple Regs - 4x)
"""----------------SETPOINT------------------"""
REG_UG1_SA_Reserva03 = 2  # Scale - Op16 (Preset Multiple Regs - 4x)
REG_UG1_SA_Reserva04 = 3  # Scale - Op16 (Preset Multiple Regs - 4x)
REG_UG1_RA_Float_PM_710_Energia_Reativa_Consumida = (
    149  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG1_RA_Float_PM_710_Energia_Ativa_Consumida = (
    151  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG1_RA_Float_PM_710_Energia_Reativa_Fornecida = (
    153  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG1_RA_Float_PM_710_Energia_Ativa_Fornecida = (
    155  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)


REG_UG2_ED_RV_VeloMenor30 = 1  # Op02 (Read Input Status)
REG_UG2_ED_RV_VeloMaior90 = 2  # Op02 (Read Input Status)


REG_UG2_ED_AVR_FalhaInterna = 5  # Op02 (Read Input Status)
REG_UG2_ED_AVR_Ligado = 6  # Op02 (Read Input Status)
REG_UG2_ED_PotenciaNula = 7  # Op02 (Read Input Status)
REG_UG2_ED_Falta125Vcc = 8  # Op02 (Read Input Status)
REG_UG2_ED_DisjGeradorInserido = 9  # Op02 (Read Input Status)
REG_UG2_ED_DisjGeradorAberto = 10  # Op02 (Read Input Status)
REG_UG2_ED_EmergPainelAtuada = 12  # Op02 (Read Input Status)
REG_UG2_ED_Falta125VccQPCUG1 = 13  # Op02 (Read Input Status)
REG_UG2_ED_Falta125VccQPCUG3 = 00000  # Op02 (Read Input Status) # verificar
REG_UG2_ED_Falta125VccAlimVal = 14  # Op02 (Read Input Status)
REG_UG2_ED_FalhaDisjTpsProt = 15  # Op02 (Read Input Status)


REG_UG2_ED_SEL700G_FalhaInterna = 19  # Op02 (Read Input Status)
REG_UG2_ED_Reserva244 = 20  # Op02 (Read Input Status)
REG_UG2_ED_Reserva245 = 21  # Op02 (Read Input Status)
REG_UG2_ED_NivelMAltoPocoDren = 22  # Op02 (Read Input Status)
REG_UG2_ED_DijAlimAVRLig = 23  # Op02 (Read Input Status)

REG_UG2_ED_FreioPressNormal = 25  # Op02 (Read Input Status)
REG_UG2_ED_FreioDesaplicado = 26  # Op02 (Read Input Status)
REG_UG2_ED_FreioAplicado = 27  # Op02 (Read Input Status)
REG_UG2_ED_Reserva254 = 28  # Op02 (Read Input Status)

REG_UG2_ED_FreioFiltroSaturado = 30  # Op02 (Read Input Status)
REG_UG2_ED_FreioSemEnergia = 31  # Op02 (Read Input Status)
REG_UG2_ED_UHRV_PressCriticaPos321 = 32  # Op02 (Read Input Status)
REG_UG2_ED_UHRV_PressMinimaPos322 = 33  # Op02 (Read Input Status)
REG_UG2_ED_UHRV_PressNominalPos323 = 34  # Op02 (Read Input Status)
REG_UG2_ED_UHRV_Reserva263 = 35  # Op02 (Read Input Status)
REG_UG2_ED_UHRV_Reserva264 = 36  # Op02 (Read Input Status)

REG_UG2_ED_FiltroPresSujo100Sujo = 38  # Op02 (Read Input Status)

REG_UG2_ED_FiltroRetSujo100Sujo = 40  # Op02 (Read Input Status)
REG_UG2_ED_UHRV_NivOleoCriticoPos35 = 41  # Op02 (Read Input Status)
REG_UG2_ED_UHRV_NivOleominimoPos36 = 42  # Op02 (Read Input Status)
REG_UG2_ED_UHRV_PressaoEqual = 43  # Op02 (Read Input Status)
REG_UG2_ED_ValvBorbTravada = 44  # Op02 (Read Input Status)
REG_UG2_ED_ValvBorbDestravada = 45  # Op02 (Read Input Status)
REG_UG2_ED_ValvBorbFechada = 46  # Op02 (Read Input Status)
REG_UG2_ED_ValvBorbAberta = 47  # Op02 (Read Input Status)
REG_UG2_ED_ValvBorbADeriva = 48  # Op02 (Read Input Status)
REG_UG2_ED_ValvByPassFechada = 49  # Op02 (Read Input Status)
REG_UG2_ED_ValvByPassAberta = 50  # Op02 (Read Input Status)
REG_UG2_ED_DistribuidorFechado = 51  # Op02 (Read Input Status)
REG_UG2_ED_FluxInjAguaPos14 = 52  # Op02 (Read Input Status)
REG_UG2_ED_PresInjAguaPos15 = 53  # Op02 (Read Input Status)
REG_UG2_ED_SobreVeloMecPos18 = 54  # Op02 (Read Input Status)
REG_UG2_ED_FaltaFluxoOleoMc = 55  # Op02 (Read Input Status)
REG_UG2_ED_PalhetasDesal = 56  # Op02 (Read Input Status)
REG_UG2_ED_UHLM_FaltaFluxTroc = 57  # Op02 (Read Input Status)
REG_UG2_ED_UHLM_FaltaPressTroc = 58  # Op02 (Read Input Status)

REG_UG2_ED_UHLM_Filt1PresSujo100Sujo = 60  # Op02 (Read Input Status)

REG_UG2_ED_UHLM_Filt2PresSujo100Sujo = 62  # Op02 (Read Input Status)
REG_UG2_ED_UHLM_NivelCritOleo = 63  # Op02 (Read Input Status)
REG_UG2_ED_UHLM_NivelminOleo = 64  # Op02 (Read Input Status)

REG_UG2_ED_FiltroPressaoBbaMecSj100 = 66  # Op02 (Read Input Status)
REG_UG2_ED_FaltaFluxoBbaMec = 67  # Op02 (Read Input Status)
REG_UG2_ED_UHLM_FluxoMcDianteiro = 68  # Op02 (Read Input Status)
REG_UG2_ED_UHLM_FluxoMcTras = 69  # Op02 (Read Input Status)
REG_UG2_ED_UHLM_PressPos37 = 70  # Op02 (Read Input Status)
REG_UG2_ED_Reserva307 = 71  # Op02 (Read Input Status)
REG_UG2_ED_UHLM_Bomba1Ligada = 72  # Op02 (Read Input Status)
REG_UG2_ED_UHLM_Bomba2Ligada = 73  # Op02 (Read Input Status)
REG_UG2_ED_PartResLigada = 74  # Op02 (Read Input Status)
REG_UG2_ED_UHRV_Bomba1Ligada = 75  # Op02 (Read Input Status)
REG_UG2_ED_UHRV_Bomba2Ligada = 76  # Op02 (Read Input Status)
REG_UG2_ED_QCAUG_Falha380VcaPainel = 77  # Op02 (Read Input Status)
REG_UG2_ED_QCAUG_Disj52A1Lig = 78  # Op02 (Read Input Status)
REG_UG2_ED_QCAUG_TripDisj52A1 = 79  # Op02 (Read Input Status)
REG_UG2_ED_UHLM_TripBomba1 = 80  # Op02 (Read Input Status)
REG_UG2_ED_UHLM_TripBomba2 = 81  # Op02 (Read Input Status)

REG_UG2_ED_UHRV_TripBomba1 = 83  # Op02 (Read Input Status)
REG_UG2_ED_UHRV_TripBomba2 = 84  # Op02 (Read Input Status)
REG_UG2_ED_TripAlimPainelFreio = 85  # Op02 (Read Input Status)
REG_UG2_ED_PainelFreioStatus = 86  # Op02 (Read Input Status)
REG_UG2_ED_QCAUG_TripDisjAgrup = 87  # Op02 (Read Input Status)

REG_UG2_RD_TensaoEstabilizada = 128  # Op02 (Read Input Status)
REG_UG2_RD_EmergenciaViaSuper = 129  # Op02 (Read Input Status)
REG_UG2_RD_SeqManual = 130  # Op02 (Read Input Status)
REG_UG2_RD_SeqAutomatica = 131  # Op02 (Read Input Status)



REG_UG2_RD_ValvSeg_Energizadas = 136  # Op02 (Read Input Status)
REG_UG2_RD_FalhaAcionAbertValvBorb = 137  # Op02 (Read Input Status)
REG_UG2_RD_FalhaAcionFechaValvBorb = 138  # Op02 (Read Input Status)
REG_UG2_RD_FalhaAcionAbertValvByPass = 139  # Op02 (Read Input Status)
REG_UG2_RD_FalhaAcionFechaValvByPass = 140  # Op02 (Read Input Status)
REG_UG2_RD_UHRV_CondOK_M1 = 141  # Op02 (Read Input Status)
REG_UG2_RD_UHRV_CondOK_M2 = 142  # Op02 (Read Input Status)
REG_UG2_RD_UHLM_CondOK_M1 = 143  # Op02 (Read Input Status)
REG_UG2_RD_UHLM_CondOK_M2 = 144  # Op02 (Read Input Status)
REG_UG2_RD_Bombas_UHRV_Ligada = 145  # Op02 (Read Input Status)
REG_UG2_RD_UHRV_FalhaAcionBbaM1 = 146  # Op02 (Read Input Status)
REG_UG2_RD_UHRV_FalhaAcionBbaM2 = 147  # Op02 (Read Input Status)
REG_UG2_RD_UHLM_FalhaAcionBbaM1 = 148  # Op02 (Read Input Status)
REG_UG2_RD_UHLM_FalhaAcionBbaM2 = 149  # Op02 (Read Input Status)
REG_UG2_RD_UHRV_PressaoOK = 150  # Op02 (Read Input Status)
REG_UG2_RD_UHRV_BbaM1Princ = 151  # Op02 (Read Input Status)
REG_UG2_RD_UHLM_BbaM1Princ = 152  # Op02 (Read Input Status)
REG_UG2_RD_Filtros_Manual = 153  # Op02 (Read Input Status)
REG_UG2_RD_FalhaAcionRT = 154  # Op02 (Read Input Status)
REG_UG2_RD_RV_CondOK = 155  # Op02 (Read Input Status)
REG_UG2_RD_RT_CondOK = 156  # Op02 (Read Input Status)
REG_UG2_RD_AVR_HabRefExterna = 157  # Op02 (Read Input Status)
REG_UG2_RD_AVR_ControleFP = 158  # Op02 (Read Input Status)
REG_UG2_RD_UHLM_Ligada = 159  # Op02 (Read Input Status)
REG_UG2_RD_Filtro1Sel = 160  # Op02 (Read Input Status)
REG_UG2_RD_Filtro2Sel = 161  # Op02 (Read Input Status)
REG_UG2_RD_QCAUGFalhaAcionPartRes = 162  # Op02 (Read Input Status)
REG_UG2_RD_FalhaAcionFreio = 163  # Op02 (Read Input Status)
REG_UG2_RD_TripTempGaxeteiro = 164  # Op02 (Read Input Status)
REG_UG2_RD_TripTempMcGuiaRadial = 165  # Op02 (Read Input Status)
REG_UG2_RD_TripTempMcGuiaEscora = 166  # Op02 (Read Input Status)
REG_UG2_RD_TripTempMcGuiaContraEscora = (
    167  # Op02 (Read Input Status)
)
REG_UG2_RD_TripTempUHRV = 168  # Op02 (Read Input Status)
REG_UG2_RD_TripTempUHLM = 169  # Op02 (Read Input Status)
REG_UG2_RD_TripVibr1 = 170  # Op02 (Read Input Status)
REG_UG2_RD_TripVibr2 = 171  # Op02 (Read Input Status)
REG_UG2_RD_FalhaIbntDisjGer = 172  # Op02 (Read Input Status)
REG_UG2_RD_AbortaPartida = 173  # Op02 (Read Input Status)
REG_UG2_RD_TempoPartidaExc = 174  # Op02 (Read Input Status)
REG_UG2_RD_ValvInjArRotorLig = 175  # Op02 (Read Input Status)
REG_UG2_RD_ValvInjArRotorAuto = 176  # Op02 (Read Input Status)
REG_UG2_RD_PreCondPartidaOK = 177  # Op02 (Read Input Status)
REG_UG2_RD_PassoLigaValvSeg = 178  # Op02 (Read Input Status)
REG_UG2_RD_PassoDeslValvSeg = 179  # Op02 (Read Input Status)
REG_UG2_RD_PassoAbreValvBorb = 180  # Op02 (Read Input Status)
REG_UG2_RD_PassoFechaValvBorb = 181  # Op02 (Read Input Status)
REG_UG2_RD_PassoLigaUHRV = 182  # Op02 (Read Input Status)
REG_UG2_RD_PassoDesligaUHRV = 183  # Op02 (Read Input Status)
REG_UG2_RD_PassoLigaRT = 184  # Op02 (Read Input Status)
REG_UG2_RD_PassoDesligaRT = 185  # Op02 (Read Input Status)
REG_UG2_RD_PassoLigaRV = 186  # Op02 (Read Input Status)
REG_UG2_RD_PassoDesligaRV = 187  # Op02 (Read Input Status)
REG_UG2_RD_PassoAbreValvByPass = 188  # Op02 (Read Input Status)
REG_UG2_RD_PassoFechaValvByPass = 189  # Op02 (Read Input Status)
REG_UG2_RD_PassoLigaUHLM = 190  # Op02 (Read Input Status)
REG_UG2_RD_PassoDesligaUHLM = 191  # Op02 (Read Input Status)
REG_UG2_RD_PassoAbreDisjuntor = 192  # Op02 (Read Input Status)
REG_UG2_RD_PassoLigaFreioPara = 193  # Op02 (Read Input Status)
REG_UG2_RD_PassoDeslFreioPart = 194  # Op02 (Read Input Status)
REG_UG2_RD_PassoSincroniza = 195  # Op02 (Read Input Status)
REG_UG2_RD_700G_EN = 196  # Op02 (Read Input Status)

REG_UG2_RD_700G_TLED_01 = 198  # Op02 (Read Input Status)
REG_UG2_RD_700G_TLED_02 = 199  # Op02 (Read Input Status)
REG_UG2_RD_700G_TLED_03 = 200  # Op02 (Read Input Status)
REG_UG2_RD_700G_TLED_04 = 201  # Op02 (Read Input Status)
REG_UG2_RD_700G_TLED_05 = 202  # Op02 (Read Input Status)
REG_UG2_RD_700G_TLED_06 = 203  # Op02 (Read Input Status)
REG_UG2_RD_SincronismoHab = 204  # Op02 (Read Input Status)
REG_UG2_RD_CLP_Falha = 205  # Op02 (Read Input Status)
REG_UG2_RD_Remota_Falha = 206  # Op02 (Read Input Status)
REG_UG2_RD_PassoLigaFreioPart = 207  # Op02 (Read Input Status)
REG_UG2_RD_RV_RetiraCarga = 208  # Op02 (Read Input Status)
REG_UG2_RD_RV_RefRemHabilitada = 209  # Op02 (Read Input Status)
REG_UG2_RD_FalhaComunG2TDA = 210  # Op02 (Read Input Status)
REG_UG2_RD_Q_Negativa = 211  # Op02 (Read Input Status)
REG_UG2_RD_UG2_StsBloqueio = 212  # Op02 (Read Input Status)
REG_UG2_RD_TripPressaoCaixaEspiral = 213  # Op02 (Read Input Status)
REG_UG2_RD_Trip_PBCE_Habilitado = 214  # Op02 (Read Input Status)
"""----------------SETPOINT------------------"""

REG_UG2_CD_ResetReleRT = 5  # Op15 (Write multiple coils)
REG_UG2_CD_ResetRV = 6  # Op15 (Write multiple coils)
REG_UG2_CD_AumentaTensaoRT = 7  # Op15 (Write multiple coils)
REG_UG2_CD_DiminuiTensaoRT = 8  # Op15 (Write multiple coils)
REG_UG2_CD_HabControleFP = 9  # Op15 (Write multiple coils)
REG_UG2_CD_DesabControleFP = 10  # Op15 (Write multiple coils)
REG_UG2_CD_HabRefExterna = 11  # Op15 (Write multiple coils)
REG_UG2_CD_DesHabRefExterna = 12  # Op15 (Write multiple coils)
REG_UG2_CD_AumentaFreq = 13  # Op15 (Write multiple coils)
REG_UG2_CD_DiminuiFreq = 14  # Op15 (Write multiple coils)
REG_UG2_CD_HabFiltro1 = 15  # Op15 (Write multiple coils)
REG_UG2_CD_DesabFiltro1 = 16  # Op15 (Write multiple coils)
REG_UG2_CD_HabFiltro2 = 17  # Op15 (Write multiple coils)
REG_UG2_CD_DesabFiltro2 = 18  # Op15 (Write multiple coils)
REG_UG2_CD_Filtros_Manual = 19  # Op15 (Write multiple coils)
REG_UG2_CD_Filtros_Auto = 20  # Op15 (Write multiple coils)
REG_UG2_CD_RV_Liga = 21  # Op15 (Write multiple coils)
REG_UG2_CD_RV_Desliga = 22  # Op15 (Write multiple coils)
REG_UG2_CD_RT_Liga = 23  # Op15 (Write multiple coils)
REG_UG2_CD_RT_Desliga = 24  # Op15 (Write multiple coils)
REG_UG2_CD_AbreValvBorb = 25  # Op15 (Write multiple coils)
REG_UG2_CD_FechaValvBorb = 26  # Op15 (Write multiple coils)
REG_UG2_CD_AbreValvByPass = 27  # Op15 (Write multiple coils)
REG_UG2_CD_FechaValvByPass = 28  # Op15 (Write multiple coils)
REG_UG2_CD_UHRV_LigaBbaM1 = 29  # Op15 (Write multiple coils)
REG_UG2_CD_UHRV_DesligaBbaM1 = 30  # Op15 (Write multiple coils)
REG_UG2_CD_UHRV_LigaBbaM2 = 31  # Op15 (Write multiple coils)
REG_UG2_CD_UHRV_DesligaBbaM2 = 32  # Op15 (Write multiple coils)
REG_UG2_CD_UHRV_SelM1Princ = 33  # Op15 (Write multiple coils)
REG_UG2_CD_UHRV_SelM2Princ = 34  # Op15 (Write multiple coils)
REG_UG2_CD_UHLM_LigaBbaM1 = 35  # Op15 (Write multiple coils)
REG_UG2_CD_UHLM_DesligaBbaM1 = 36  # Op15 (Write multiple coils)
REG_UG2_CD_UHLM_LigaBbaM2 = 37  # Op15 (Write multiple coils)
REG_UG2_CD_UHLM_DesligaBbaM2 = 38  # Op15 (Write multiple coils)
REG_UG2_CD_UHLM_SelM1Princ = 39  # Op15 (Write multiple coils)
REG_UG2_CD_UHLM_SelM2Princ = 40  # Op15 (Write multiple coils)
REG_UG2_CD_HabSeqAuto = 41  # Op15 (Write multiple coils)
REG_UG2_CD_HabSeqManual = 42  # Op15 (Write multiple coils)
REG_UG2_CD_Freio_Aplica = 43  # Op15 (Write multiple coils)
REG_UG2_CD_Freio_Desaplica = 44  # Op15 (Write multiple coils)

REG_UG2_CD_ValvSeg_Liga = 48  # Op15 (Write multiple coils)
REG_UG2_CD_ValvSeg_Desliga = 49  # Op15 (Write multiple coils)
REG_UG2_CD_DeslDisj52G = 50  # Op15 (Write multiple coils)
REG_UG2_CD_QCAUG_LigaPartRes = 51  # Op15 (Write multiple coils)
REG_UG2_CD_QCAUG_DeslPartRes = 52  # Op15 (Write multiple coils)
REG_UG2_CD_AbreDisj = 53  # Op15 (Write multiple coils)
REG_UG2_CD_SelValvInjRotorAuto = 54  # Op15 (Write multiple coils)
REG_UG2_CD_SelValvInjRotorManu = 55  # Op15 (Write multiple coils)
REG_UG2_CD_LigaValvInjArRotor = 56  # Op15 (Write multiple coils)
REG_UG2_CD_DeslValvInjArRotor = 57  # Op15 (Write multiple coils)
REG_UG2_CD_Sincroniza = 58  # Op15 (Write multiple coils)

REG_UG2_CD_Reset_Hori_Gerador = 60  # Op15 (Write multiple coils)

REG_UG2_CD_RetiraCarga = 62  # Op15 (Write multiple coils)
REG_UG2_CD_RV_RetiraCarga = 63  # Op15 (Write multiple coils)
"""----------------SETPOINT------------------"""
REG_UG2_CD_RV_RefRemDesabilita = 65  # Op15 (Write multiple coils)
REG_UG2_CD_Trip_PBCE_Habilita = 66  # Op15 (Write multiple coils)
REG_UG2_CD_Trip_PBCE_Desabilita = 67  # Op15 (Write multiple coils)

REG_UG2_RA_Temperatura_11 = 34  # Op04 (Read Input Regs - 3x)
REG_UG2_RA_Temperatura_12 = 35  # Op04 (Read Input Regs - 3x)
REG_UG2_RA_PM_710_Tensao_AB = 36  # Op04 (Read Input Regs - 3x)
REG_UG2_RA_PM_710_Tensao_BC = 37  # Op04 (Read Input Regs - 3x)
REG_UG2_RA_PM_710_Tensao_CA = 38  # Op04 (Read Input Regs - 3x)
REG_UG2_RA_PM_710_Corrente_A = 39  # Op04 (Read Input Regs - 3x)
REG_UG2_RA_PM_710_Corrente_B = 40  # Op04 (Read Input Regs - 3x)
REG_UG2_RA_PM_710_Corrente_C = 41  # Op04 (Read Input Regs - 3x)
REG_UG2_RA_PM_710_Frequencia = 42  # Op04 (Read Input Regs - 3x)
REG_UG2_RA_PM_710_Fator_Potencia = 43  # Op04 (Read Input Regs - 3x)
REG_UG2_RA_PM_710_Potencia_Aparente = (
    44  # Op04 (Read Input Regs - 3x)
)

REG_UG2_RA_PM_710_Potencia_Reativa = (
    46  # Op04 (Read Input Regs - 3x)
)
REG_UG2_RA_Estabiliz_Tensao = 49  # Op04 (Read Input Regs - 3x)
REG_UG2_EA_PosicaoDistribuidor = (
    0  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG2_EA_Velocidade = 1  # Scale 0.1 - Op04 (Read Input Regs - 3x)
REG_UG2_EA_Reserva01 = 2  # Scale 0.1 - Op04 (Read Input Regs - 3x)
REG_UG2_EA_Reserva02 = 3  # Scale 0.1 - Op04 (Read Input Regs - 3x)
REG_UG2_EA_PressAguaVedEixo = (
    4  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG2_EA_PressDifCaixaExpiral = (
    5  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG2_EA_PressK1CaixaExpiral = (
    6  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG2_EA_PressK1Succao = (
    7  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG2_EA_TempGaxetas = (
    8  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)


REG_UG2_EA_VibMcGuiaRadial = (
    12  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG2_EA_VibMcGuiaAxial = (
    13  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG2_EA_UHRV_TempOleo = (
    14  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG2_EA_UHRV_Pressao = (
    15  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG2_EA_UHLM_TempOleo = (
    16  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG2_EA_Reserva03 = 17  # Scale 0.1 - Op04 (Read Input Regs - 3x)
REG_UG2_EA_VazEntrOleoMcDiant = (
    18  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG2_EA_VazEntrOleoMcTras = (
    19  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG2_EA_Reserva04 = 20  # Scale 0.1 - Op04 (Read Input Regs - 3x)
REG_UG2_EA_Reserva05 = 21  # Scale 0.1 - Op04 (Read Input Regs - 3x)
REG_UG2_EA_Reserva06 = 22  # Scale 0.1 - Op04 (Read Input Regs - 3x)
REG_UG2_EA_Reserva07 = 23  # Scale 0.1 - Op04 (Read Input Regs - 3x)
REG_UG2_SA_Reserva01 = 0  # Scale - Op16 (Preset Multiple Regs - 4x)
"""----------------SETPOINT------------------"""
REG_UG2_SA_Reserva03 = 2  # Scale - Op16 (Preset Multiple Regs - 4x)
REG_UG2_SA_Reserva04 = 3  # Scale - Op16 (Preset Multiple Regs - 4x)
REG_UG2_RA_Float_PM_710_Energia_Reativa_Consumida = (
    149  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG2_RA_Float_PM_710_Energia_Ativa_Consumida = (
    151  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG2_RA_Float_PM_710_Energia_Reativa_Fornecida = (
    153  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG2_RA_Float_PM_710_Energia_Ativa_Fornecida = (
    155  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)

REG_UG3_ED_RV_VeloMenor30 = 1  # Op02 (Read Input Status)
REG_UG3_ED_RV_VeloMaior90 = 2  # Op02 (Read Input Status)

REG_UG3_ED_AVR_FalhaInterna = 5  # Op02 (Read Input Status)
REG_UG3_ED_AVR_Ligado = 6  # Op02 (Read Input Status)
REG_UG3_ED_PotenciaNula = 7  # Op02 (Read Input Status)
REG_UG3_ED_Falta125Vcc = 8  # Op02 (Read Input Status)
REG_UG3_ED_DisjGeradorInserido = 9  # Op02 (Read Input Status)
REG_UG3_ED_DisjGeradorAberto = 10  # Op02 (Read Input Status)

REG_UG3_ED_EmergPainelAtuada = 12  # Op02 (Read Input Status)
REG_UG3_ED_Falta125VccCom = 13  # Op02 (Read Input Status)
REG_UG3_ED_Falta125VccAlimVal = 14  # Op02 (Read Input Status)
REG_UG3_ED_FalhaDisjTpsProt = 15  # Op02 (Read Input Status)


REG_UG3_ED_SEL700G_FalhaInterna = 19  # Op02 (Read Input Status)
REG_UG3_ED_Falta125VccQPCUG2 = 20  # Op02 (Read Input Status)
REG_UG3_ED_Falta125VccQPCUG1 = 21  # Op02 (Read Input Status)
REG_UG3_ED_NivelMAltoPocoDren = 22  # Op02 (Read Input Status)
REG_UG3_ED_DijAlimAVRLig = 23  # Op02 (Read Input Status)

REG_UG3_ED_FreioPressNormal = 25  # Op02 (Read Input Status)
REG_UG3_ED_FreioDesaplicado = 26  # Op02 (Read Input Status)
REG_UG3_ED_FreioAplicado = 27  # Op02 (Read Input Status)
REG_UG3_ED_Reserva254 = 28  # Op02 (Read Input Status)

REG_UG3_ED_FreioFiltroSaturado = 30  # Op02 (Read Input Status)
REG_UG3_ED_FreioSemEnergia = 31  # Op02 (Read Input Status)
REG_UG3_ED_UHRV_PressCriticaPos321 = 32  # Op02 (Read Input Status)
REG_UG3_ED_UHRV_PressMinimaPos322 = 33  # Op02 (Read Input Status)
REG_UG3_ED_UHRV_PressNominalPos323 = 34  # Op02 (Read Input Status)
REG_UG3_ED_UHRV_Reserva263 = 35  # Op02 (Read Input Status)
REG_UG3_ED_UHRV_Reserva264 = 36  # Op02 (Read Input Status)

REG_UG3_ED_FiltroPresSujo100Sujo = 38  # Op02 (Read Input Status)

REG_UG3_ED_FiltroRetSujo100Sujo = 40  # Op02 (Read Input Status)
REG_UG3_ED_UHRV_NivOleoCriticoPos35 = 41  # Op02 (Read Input Status)
REG_UG3_ED_UHRV_NivOleominimoPos36 = 42  # Op02 (Read Input Status)
REG_UG3_ED_UHRV_PressaoEqual = 43  # Op02 (Read Input Status)
REG_UG3_ED_ValvBorbTravada = 44  # Op02 (Read Input Status)
REG_UG3_ED_ValvBorbDestravada = 45  # Op02 (Read Input Status)
REG_UG3_ED_ValvBorbFechada = 46  # Op02 (Read Input Status)
REG_UG3_ED_ValvBorbAberta = 47  # Op02 (Read Input Status)
REG_UG3_ED_ValvBorbADeriva = 48  # Op02 (Read Input Status)
REG_UG3_ED_ValvByPassFechada = 49  # Op02 (Read Input Status)
REG_UG3_ED_ValvByPassAberta = 50  # Op02 (Read Input Status)
REG_UG3_ED_DistribuidorFechado = 51  # Op02 (Read Input Status)
REG_UG3_ED_FluxInjAguaPos14 = 52  # Op02 (Read Input Status)
REG_UG3_ED_PresInjAguaPos15 = 53  # Op02 (Read Input Status)
REG_UG3_ED_SobreVeloMecPos18 = 54  # Op02 (Read Input Status)
REG_UG3_ED_FaltaFluxoOleoMc = 55  # Op02 (Read Input Status)
REG_UG3_ED_PalhetasDesal = 56  # Op02 (Read Input Status)
REG_UG3_ED_UHLM_FaltaFluxTroc = 57  # Op02 (Read Input Status)
REG_UG3_ED_UHLM_FaltaPressTroc = 58  # Op02 (Read Input Status)

REG_UG3_ED_UHLM_Filt1PresSujo100Sujo = 60  # Op02 (Read Input Status)

REG_UG3_ED_UHLM_Filt2PresSujo100Sujo = 62  # Op02 (Read Input Status)
REG_UG3_ED_UHLM_NivelCritOleo = 63  # Op02 (Read Input Status)
REG_UG3_ED_UHLM_NivelminOleo = 64  # Op02 (Read Input Status)

REG_UG3_ED_FiltroPressaoBbaMecSj100 = 66  # Op02 (Read Input Status)
REG_UG3_ED_FaltaFluxoBbaMec = 67  # Op02 (Read Input Status)
REG_UG3_ED_UHLM_FluxoMcDianteiro = 68  # Op02 (Read Input Status)
REG_UG3_ED_UHLM_FluxoMcTras = 69  # Op02 (Read Input Status)
REG_UG3_ED_UHLM_PressPos37 = 70  # Op02 (Read Input Status)
REG_UG3_ED_Reserva307 = 71  # Op02 (Read Input Status)
REG_UG3_ED_UHLM_Bomba1Ligada = 72  # Op02 (Read Input Status)
REG_UG3_ED_UHLM_Bomba2Ligada = 73  # Op02 (Read Input Status)
REG_UG3_ED_PartResLigada = 74  # Op02 (Read Input Status)
REG_UG3_ED_UHRV_Bomba1Ligada = 75  # Op02 (Read Input Status)
REG_UG3_ED_UHRV_Bomba2Ligada = 76  # Op02 (Read Input Status)
REG_UG3_ED_QCAUG_Falha380VcaPainel = 77  # Op02 (Read Input Status)
REG_UG3_ED_QCAUG_Disj52A1Lig = 78  # Op02 (Read Input Status)
REG_UG3_ED_QCAUG_TripDisj52A1 = 79  # Op02 (Read Input Status)
REG_UG3_ED_UHLM_TripBomba1 = 80  # Op02 (Read Input Status)
REG_UG3_ED_UHLM_TripBomba2 = 81  # Op02 (Read Input Status)

REG_UG3_ED_UHRV_TripBomba1 = 83  # Op02 (Read Input Status)
REG_UG3_ED_UHRV_TripBomba2 = 84  # Op02 (Read Input Status)
REG_UG3_ED_TripAlimPainelFreio = 85  # Op02 (Read Input Status)
REG_UG3_ED_PainelFreioStatus = 86  # Op02 (Read Input Status)
REG_UG3_ED_QCAUG_TripDisjAgrup = 87  # Op02 (Read Input Status)

REG_UG3_RD_TensaoEstabilizada = 128  # Op02 (Read Input Status)
REG_UG3_RD_EmergenciaViaSuper = 129  # Op02 (Read Input Status)
REG_UG3_RD_SeqManual = 130  # Op02 (Read Input Status)
REG_UG3_RD_SeqAutomatica = 131  # Op02 (Read Input Status)

REG_UG3_RD_ValvSeg_Energizadas = 136  # Op02 (Read Input Status)
REG_UG3_RD_FalhaAcionAbertValvBorb = 137  # Op02 (Read Input Status)
REG_UG3_RD_FalhaAcionFechaValvBorb = 138  # Op02 (Read Input Status)
REG_UG3_RD_FalhaAcionAbertValvByPass = 139  # Op02 (Read Input Status)
REG_UG3_RD_FalhaAcionFechaValvByPass = 140  # Op02 (Read Input Status)
REG_UG3_RD_UHRV_CondOK_M1 = 141  # Op02 (Read Input Status)
REG_UG3_RD_UHRV_CondOK_M2 = 142  # Op02 (Read Input Status)
REG_UG3_RD_UHLM_CondOK_M1 = 143  # Op02 (Read Input Status)
REG_UG3_RD_UHLM_CondOK_M2 = 144  # Op02 (Read Input Status)
REG_UG3_RD_Bombas_UHRV_Ligada = 145  # Op02 (Read Input Status)
REG_UG3_RD_UHRV_FalhaAcionBbaM1 = 146  # Op02 (Read Input Status)
REG_UG3_RD_UHRV_FalhaAcionBbaM2 = 147  # Op02 (Read Input Status)
REG_UG3_RD_UHLM_FalhaAcionBbaM1 = 148  # Op02 (Read Input Status)
REG_UG3_RD_UHLM_FalhaAcionBbaM2 = 149  # Op02 (Read Input Status)
REG_UG3_RD_UHRV_PressaoOK = 150  # Op02 (Read Input Status)
REG_UG3_RD_UHRV_BbaM1Princ = 151  # Op02 (Read Input Status)
REG_UG3_RD_UHLM_BbaM1Princ = 152  # Op02 (Read Input Status)
REG_UG3_RD_Filtros_Manual = 153  # Op02 (Read Input Status)
REG_UG3_RD_FalhaAcionRT = 154  # Op02 (Read Input Status)
REG_UG3_RD_RV_CondOK = 155  # Op02 (Read Input Status)
REG_UG3_RD_RT_CondOK = 156  # Op02 (Read Input Status)
REG_UG3_RD_AVR_HabRefExterna = 157  # Op02 (Read Input Status)
REG_UG3_RD_AVR_ControleFP = 158  # Op02 (Read Input Status)
REG_UG3_RD_UHLM_Ligada = 159  # Op02 (Read Input Status)
REG_UG3_RD_Filtro1Sel = 160  # Op02 (Read Input Status)
REG_UG3_RD_Filtro2Sel = 161  # Op02 (Read Input Status)
REG_UG3_RD_QCAUGFalhaAcionPartRes = 162  # Op02 (Read Input Status)
REG_UG3_RD_FalhaAcionFreio = 163  # Op02 (Read Input Status)
REG_UG3_RD_TripTempGaxeteiro = 164  # Op02 (Read Input Status)
REG_UG3_RD_TripTempMcGuiaRadial = 165  # Op02 (Read Input Status)
REG_UG3_RD_TripTempMcGuiaEscora = 166  # Op02 (Read Input Status)
REG_UG3_RD_TripTempMcGuiaContraEscora = (
    167  # Op02 (Read Input Status)
)
REG_UG3_RD_TripTempUHRV = 168  # Op02 (Read Input Status)
REG_UG3_RD_TripTempUHLM = 169  # Op02 (Read Input Status)
REG_UG3_RD_TripVibr1 = 170  # Op02 (Read Input Status)
REG_UG3_RD_TripVibr2 = 171  # Op02 (Read Input Status)
REG_UG3_RD_FalhaIbntDisjGer = 172  # Op02 (Read Input Status)
REG_UG3_RD_AbortaPartida = 173  # Op02 (Read Input Status)
REG_UG3_RD_TempoPartidaExc = 174  # Op02 (Read Input Status)
REG_UG3_RD_ValvInjArRotorLig = 175  # Op02 (Read Input Status)
REG_UG3_RD_ValvInjArRotorAuto = 176  # Op02 (Read Input Status)
REG_UG3_RD_PreCondPartidaOK = 177  # Op02 (Read Input Status)
REG_UG3_RD_PassoLigaValvSeg = 178  # Op02 (Read Input Status)
REG_UG3_RD_PassoDeslValvSeg = 179  # Op02 (Read Input Status)
REG_UG3_RD_PassoAbreValvBorb = 180  # Op02 (Read Input Status)
REG_UG3_RD_PassoFechaValvBorb = 181  # Op02 (Read Input Status)
REG_UG3_RD_PassoLigaUHRV = 182  # Op02 (Read Input Status)
REG_UG3_RD_PassoDesligaUHRV = 183  # Op02 (Read Input Status)
REG_UG3_RD_PassoLigaRT = 184  # Op02 (Read Input Status)
REG_UG3_RD_PassoDesligaRT = 185  # Op02 (Read Input Status)
REG_UG3_RD_PassoLigaRV = 186  # Op02 (Read Input Status)
REG_UG3_RD_PassoDesligaRV = 187  # Op02 (Read Input Status)
REG_UG3_RD_PassoAbreValvByPass = 188  # Op02 (Read Input Status)
REG_UG3_RD_PassoFechaValvByPass = 189  # Op02 (Read Input Status)
REG_UG3_RD_PassoLigaUHLM = 190  # Op02 (Read Input Status)
REG_UG3_RD_PassoDesligaUHLM = 191  # Op02 (Read Input Status)
REG_UG3_RD_PassoAbreDisjuntor = 192  # Op02 (Read Input Status)
REG_UG3_RD_PassoLigaFreioPara = 193  # Op02 (Read Input Status)
REG_UG3_RD_PassoDeslFreioPart = 194  # Op02 (Read Input Status)
REG_UG3_RD_PassoSincroniza = 195  # Op02 (Read Input Status)
REG_UG3_RD_700G_EN = 196  # Op02 (Read Input Status)

REG_UG3_RD_700G_TLED_01 = 198  # Op02 (Read Input Status)
REG_UG3_RD_700G_TLED_02 = 199  # Op02 (Read Input Status)
REG_UG3_RD_700G_TLED_03 = 200  # Op02 (Read Input Status)
REG_UG3_RD_700G_TLED_04 = 201  # Op02 (Read Input Status)
REG_UG3_RD_700G_TLED_05 = 202  # Op02 (Read Input Status)
REG_UG3_RD_700G_TLED_06 = 203  # Op02 (Read Input Status)
REG_UG3_RD_SincronismoHab = 204  # Op02 (Read Input Status)
REG_UG3_RD_CLP_Falha = 205  # Op02 (Read Input Status)
REG_UG3_RD_Remota_Falha = 206  # Op02 (Read Input Status)
REG_UG3_RD_PassoLigaFreioPart = 207  # Op02 (Read Input Status)
REG_UG3_RD_RV_RetiraCarga = 208  # Op02 (Read Input Status)
REG_UG3_RD_RV_RefRemHabilitada = 209  # Op02 (Read Input Status)
REG_UG3_RD_FalhaComunG3TDA = 210  # Op02 (Read Input Status)
REG_UG3_RD_Q_Negativa = 211  # Op02 (Read Input Status)
REG_UG3_RD_UG3_StsBloqueio = 212  # Op02 (Read Input Status)
REG_UG3_RD_TripPressaoCaixaEspiral = 213  # Op02 (Read Input Status)
REG_UG3_RD_Trip_PBCE_Habilitado = 214  # Op02 (Read Input Status)
"""----------------SETPOINT------------------"""

REG_UG3_CD_ResetReleRT = 5  # Op15 (Write multiple coils)
REG_UG3_CD_ResetRV = 6  # Op15 (Write multiple coils)
REG_UG3_CD_AumentaTensaoRT = 7  # Op15 (Write multiple coils)
REG_UG3_CD_DiminuiTensaoRT = 8  # Op15 (Write multiple coils)
REG_UG3_CD_HabControleFP = 9  # Op15 (Write multiple coils)
REG_UG3_CD_DesabControleFP = 10  # Op15 (Write multiple coils)
REG_UG3_CD_HabRefExterna = 11  # Op15 (Write multiple coils)
REG_UG3_CD_DesHabRefExterna = 12  # Op15 (Write multiple coils)
REG_UG3_CD_AumentaFreq = 13  # Op15 (Write multiple coils)
REG_UG3_CD_DiminuiFreq = 14  # Op15 (Write multiple coils)
REG_UG3_CD_HabFiltro1 = 15  # Op15 (Write multiple coils)
REG_UG3_CD_DesabFiltro1 = 16  # Op15 (Write multiple coils)
REG_UG3_CD_HabFiltro2 = 17  # Op15 (Write multiple coils)
REG_UG3_CD_DesabFiltro2 = 18  # Op15 (Write multiple coils)
REG_UG3_CD_Filtros_Manual = 19  # Op15 (Write multiple coils)
REG_UG3_CD_Filtros_Auto = 20  # Op15 (Write multiple coils)
REG_UG3_CD_RV_Liga = 21  # Op15 (Write multiple coils)
REG_UG3_CD_RV_Desliga = 22  # Op15 (Write multiple coils)
REG_UG3_CD_RT_Liga = 23  # Op15 (Write multiple coils)
REG_UG3_CD_RT_Desliga = 24  # Op15 (Write multiple coils)
REG_UG3_CD_AbreValvBorb = 25  # Op15 (Write multiple coils)
REG_UG3_CD_FechaValvBorb = 26  # Op15 (Write multiple coils)
REG_UG3_CD_AbreValvByPass = 27  # Op15 (Write multiple coils)
REG_UG3_CD_FechaValvByPass = 28  # Op15 (Write multiple coils)
REG_UG3_CD_UHRV_LigaBbaM1 = 29  # Op15 (Write multiple coils)
REG_UG3_CD_UHRV_DesligaBbaM1 = 30  # Op15 (Write multiple coils)
REG_UG3_CD_UHRV_LigaBbaM2 = 31  # Op15 (Write multiple coils)
REG_UG3_CD_UHRV_DesligaBbaM2 = 32  # Op15 (Write multiple coils)
REG_UG3_CD_UHRV_SelM1Princ = 33  # Op15 (Write multiple coils)
REG_UG3_CD_UHRV_SelM2Princ = 34  # Op15 (Write multiple coils)
REG_UG3_CD_UHLM_LigaBbaM1 = 35  # Op15 (Write multiple coils)
REG_UG3_CD_UHLM_DesligaBbaM1 = 36  # Op15 (Write multiple coils)
REG_UG3_CD_UHLM_LigaBbaM2 = 37  # Op15 (Write multiple coils)
REG_UG3_CD_UHLM_DesligaBbaM2 = 38  # Op15 (Write multiple coils)
REG_UG3_CD_UHLM_SelM1Princ = 39  # Op15 (Write multiple coils)
REG_UG3_CD_UHLM_SelM2Princ = 40  # Op15 (Write multiple coils)
REG_UG3_CD_HabSeqAuto = 41  # Op15 (Write multiple coils)
REG_UG3_CD_HabSeqManual = 42  # Op15 (Write multiple coils)
REG_UG3_CD_Freio_Aplica = 43  # Op15 (Write multiple coils)
REG_UG3_CD_Freio_Desaplica = 44  # Op15 (Write multiple coils)

REG_UG3_CD_ValvSeg_Liga = 48  # Op15 (Write multiple coils)
REG_UG3_CD_ValvSeg_Desliga = 49  # Op15 (Write multiple coils)
REG_UG3_CD_DeslDisj52G = 50  # Op15 (Write multiple coils)
REG_UG3_CD_QCAUG_LigaPartRes = 51  # Op15 (Write multiple coils)
REG_UG3_CD_QCAUG_DeslPartRes = 52  # Op15 (Write multiple coils)
REG_UG3_CD_AbreDisj = 53  # Op15 (Write multiple coils)
REG_UG3_CD_SelValvInjRotorAuto = 54  # Op15 (Write multiple coils)
REG_UG3_CD_SelValvInjRotorManu = 55  # Op15 (Write multiple coils)
REG_UG3_CD_LigaValvInjArRotor = 56  # Op15 (Write multiple coils)
REG_UG3_CD_DeslValvInjArRotor = 57  # Op15 (Write multiple coils)

REG_UG3_CD_Reset_Hori_Gerador = 60  # Op15 (Write multiple coils)

REG_UG3_CD_RV_RetiraCarga = 62  # Op15 (Write multiple coils)
"""----------------SETPOINT------------------"""
REG_UG3_CD_RV_RefRemDesabilita = 64  # Op15 (Write multiple coils)
REG_UG3_CD_Trip_PBCE_Habilita = 65  # Op15 (Write multiple coils)
REG_UG3_CD_Trip_PBCE_Desabilita = 66  # Op15 (Write multiple coils)

REG_UG3_RA_Temperatura_11 = 34  # Op04 (Read Input Regs - 3x)
REG_UG3_RA_Temperatura_12 = 35  # Op04 (Read Input Regs - 3x)
REG_UG3_RA_PM_710_Tensao_AB = 36  # Op04 (Read Input Regs - 3x)
REG_UG3_RA_PM_710_Tensao_BC = 37  # Op04 (Read Input Regs - 3x)
REG_UG3_RA_PM_710_Tensao_CA = 38  # Op04 (Read Input Regs - 3x)
REG_UG3_RA_PM_710_Corrente_A = 39  # Op04 (Read Input Regs - 3x)
REG_UG3_RA_PM_710_Corrente_B = 40  # Op04 (Read Input Regs - 3x)
REG_UG3_RA_PM_710_Corrente_C = 41  # Op04 (Read Input Regs - 3x)
REG_UG3_RA_PM_710_Frequencia = 42  # Op04 (Read Input Regs - 3x)
REG_UG3_RA_PM_710_Fator_Potencia = 43  # Op04 (Read Input Regs - 3x)
REG_UG3_RA_PM_710_Potencia_Aparente = (
    44  # Op04 (Read Input Regs - 3x)
)

REG_UG3_RA_PM_710_Potencia_Reativa = (
    46  # Op04 (Read Input Regs - 3x)
)
REG_UG3_RA_Estabiliz_Tensao = 49  # Op04 (Read Input Regs - 3x)
REG_UG3_EA_PosicaoDistribuidor = (
    0  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG3_EA_Velocidade = 1  # Scale 0.1 - Op04 (Read Input Regs - 3x)
REG_UG3_EA_Reserva01 = 2  # Scale 0.1 - Op04 (Read Input Regs - 3x)
REG_UG3_EA_Reserva02 = 3  # Scale 0.1 - Op04 (Read Input Regs - 3x)
REG_UG3_EA_PressAguaVedEixo = (
    4  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG3_EA_PressDifCaixaExpiral = (
    5  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG3_EA_PressK1CaixaExpiral = (
    6  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG3_EA_PressK1Succao = (
    7  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG3_EA_TempGaxetas = (
    8  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)

REG_UG3_EA_VibMcGuiaRadial = (
    12  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG3_EA_VibMcGuiaAxial = (
    13  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG3_EA_UHRV_TempOleo = (
    14  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG3_EA_UHRV_Pressao = (
    15  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG3_EA_UHLM_TempOleo = (
    16  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG3_EA_Reserva03 = 17  # Scale 0.1 - Op04 (Read Input Regs - 3x)
REG_UG3_EA_VazEntrOleoMcDiant = (
    18  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG3_EA_VazEntrOleoMcTras = (
    19  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG3_EA_Reserva04 = 20  # Scale 0.1 - Op04 (Read Input Regs - 3x)
REG_UG3_EA_Reserva05 = 21  # Scale 0.1 - Op04 (Read Input Regs - 3x)
REG_UG3_EA_Reserva06 = 22  # Scale 0.1 - Op04 (Read Input Regs - 3x)
REG_UG3_EA_Reserva07 = 23  # Scale 0.1 - Op04 (Read Input Regs - 3x)
REG_UG3_SA_Reserva01 = 0  # Scale - Op16 (Preset Multiple Regs - 4x)
"""----------------SETPOINT------------------"""
REG_UG3_SA_Reserva03 = 2  # Scale - Op16 (Preset Multiple Regs - 4x)
REG_UG3_SA_Reserva04 = 3  # Scale - Op16 (Preset Multiple Regs - 4x)
REG_UG3_RA_Float_PM_710_Energia_Reativa_Consumida = (
    149  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG3_RA_Float_PM_710_Energia_Ativa_Consumida = (
    151  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG3_RA_Float_PM_710_Energia_Reativa_Fornecida = (
    153  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_UG3_RA_Float_PM_710_Energia_Ativa_Fornecida = (
    155  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)



REG_SA_EA_SA_Reserva07 = 15  # Scale - Op04 (Read Input Regs - 3x)
REG_SA_EA_SA_QCAP_TensaoT = (
    14  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_SA_EA_SA_QCAP_TensaoS = (
    13  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_SA_EA_SA_QCAP_TensaoR = (
    12  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_SA_EA_SA_CBU01_TensaoBarra = (
    11  # Scale - Op04 (Read Input Regs - 3x)
)
REG_SA_EA_SA_CBU01_CorrenteBarra = (
    10  # Scale - Op04 (Read Input Regs - 3x)
)
REG_SA_EA_SA_QCCP_Tensao = 9  # Scale - Op04 (Read Input Regs - 3x)
REG_SA_EA_SA_QCCP_Corrente = (
    8  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_SA_EA_SA_Reserva06 = 7  # Scale - Op04 (Read Input Regs - 3x)
REG_SA_EA_SA_Reserva05 = 6  # Scale - Op04 (Read Input Regs - 3x)
REG_SA_EA_SA_Reserva04 = 5  # Scale - Op04 (Read Input Regs - 3x)
REG_SA_EA_SA_Reserva03 = 4  # Scale - Op04 (Read Input Regs - 3x)
REG_SA_EA_SA_NivelSuccao = (
    3  # Scale 0.01 - Op04 (Read Input Regs - 3x)
)
REG_SA_EA_HoraLigaGerador = 2  # Op04 (Read Input Regs - 3x)
REG_SA_EA_SA_TE_TempEnrolamento = (
    1  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_SA_EA_SA_TE_TempOleo = (
    0  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_SA_ED_SA_Reserva180 = 0  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_Reserva181 = 1  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_SEL787_Trip = 2  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_SEL787_FalhaInterna = 3  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_SEL311_Trip = 4  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_SEL311_Falha = 5  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_MRU3_Trip = 6  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_MRU3_Falha = 7  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_MRL1_Trip = 8  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_CTE_Falta125Vcc = 9  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_CTE_Secc89TE_Fechada = 10  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_CTE_Secc89TE_Aberta = 11  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_Disj52G1_Aberto = 12  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_Disj52G2_Aberto = 13  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_Disj52G3_Aberto = 14  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_DisjDJ1_Fechado = 15  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_DisjDJ1_Aberto = 16  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_DisjDJ1_AlPressBaixa = 17  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_DisjDJ1_BloqPressBaixa = (
    18  # Op02 (Read Discrete Inputs)
)
REG_SA_ED_SA_DisjDJ1_Local = 19  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_DisjDJ1_MolaDescarregada = (
    20  # Op02 (Read Discrete Inputs)
)
REG_SA_ED_SA_DisjDJ1_Super125VccCiCom = (
    21  # Op02 (Read Discrete Inputs)
)
REG_SA_ED_SA_DisjDJ1_Super125VccCiMot = (
    22  # Op02 (Read Discrete Inputs)
)
REG_SA_ED_SA_DisjDJ1_SuperBobFecham = (
    23  # Op02 (Read Discrete Inputs)
)
REG_SA_ED_SA_DisjDJ1_SuperBobAbert1 = (
    24  # Op02 (Read Discrete Inputs)
)
REG_SA_ED_SA_DisjDJ1_SuperBobAbert2 = (
    25  # Op02 (Read Discrete Inputs)
)
REG_SA_ED_SA_DisjDJ1_Sup125VccBoFeAb1 = (
    26  # Op02 (Read Discrete Inputs)
)
REG_SA_ED_SA_DisjDJ1_Sup125VccBoFeAb2 = (
    27  # Op02 (Read Discrete Inputs)
)
REG_SA_ED_SA_Secc1_Fechada = 28  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_Secc1_Aberta = 29  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_Secc2_Fechada = 30  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_Secc2_Aberta = 31  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_Secc3_Fechada = 32  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_Secc3_Aberta = 33  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_Secc1_Remoto = 34  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_Secc2_Remoto = 35  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_Secc3_Remoto = 36  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_TE_AlarmeDetectorGas = 37  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_TE_AlarmeNivelMaxOleo = 38  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_TE_AlarmeAlivioPressao = (
    39  # Op02 (Read Discrete Inputs)
)
REG_SA_ED_SA_TE_AlarmeTempOleo = 40  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_TE_AlarmeTempEnrolamento = (
    41  # Op02 (Read Discrete Inputs)
)
REG_SA_ED_SA_TE_AlarmeDesligamento = 42  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_TE_Falha = 43  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_TE_VentilacaoLig = 44  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_TE_VentilacaoDeslig = 45  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_TE_VentilacaoDef = 46  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_FalhaDisjTPsProt = 47  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_FalhaDisjTPsSincr = 48  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_FalhaDisjTPsSincrG1 = 49  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_FalhaDisjTPsSincrG2 = 50  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_FalhaDisjTPsSincrG3 = 51  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_Disj52G1Selecionado = 52  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_Disj52G2Selecionado = 53  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_Disj52G3Selecionado = 54  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_Disj52G1Sincronizado = 55  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_Disj52G2Sincronizado = 56  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_Disj52G3Sincronizado = 57  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_Reserva252 = 58  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_Reserva253 = 59  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_Reserva254 = 60  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_Reserva255 = 61  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_Reserva256 = 62  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_Reserva257 = 63  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_CSA1_Secc_Fechada = 64  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_CSA1_Secc_Aberta = 65  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_CSA1_FusivelQueimado = 66  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_CSA1_FaltaTensao125Vcc = (
    67  # Op02 (Read Discrete Inputs)
)
REG_SA_ED_SA_QCADE_BombasDng_Desliga = (
    68  # Op02 (Read Discrete Inputs)
)
REG_SA_ED_SA_QCADE_Nivel2 = 69  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_QCADE_Nivel3 = 70  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_QCADE_Nivel4 = 71  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_QCADE_NivelMuitoAlto = 72  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_QCADE_Disj52E1Fechado = 73  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_QCADE_Disj52E1Trip = 74  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_QCADE_Falha220VCA = 75  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_QCADE_BombaDng1_Falha = 76  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_QCADE_BombaDng2_Falha = 77  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_QCADE_BombaDng3_Falha = 78  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_QCADE_BombaDng1_Ligada = (
    79  # Op02 (Read Discrete Inputs)
)
REG_SA_ED_SA_QCADE_BombaDng2_Ligada = (
    80  # Op02 (Read Discrete Inputs)
)
REG_SA_ED_SA_QCADE_BombaDng3_Ligada = (
    81  # Op02 (Read Discrete Inputs)
)
REG_SA_ED_SA_QCADE_BombasDng_Auto = 82  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_Reserva283 = 83  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_QLCF_Disj52EFechado = 84  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_QLCF_Disj52ETrip = 85  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_QLCF_TripDisjAgrup = 86  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_Reserva287 = 87  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_QCCP_Disj72EFechado = 88  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_QCCP_Disj72ETrip = 89  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_QCCP_Falta125Vcc = 90  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_QCCP_TripDisjAgrup = 91  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_MSS_EmergAtuada = 92  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_MSS_FalhaSwitch = 93  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_MSS_FalhaConvCACCEntr = 94  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_MSS_FalhaConvCACCRedeCA = (
    95  # Op02 (Read Discrete Inputs)
)
REG_SA_ED_SA_MSS_FalhaConvCACCSaidaCA = (
    96  # Op02 (Read Discrete Inputs)
)
REG_SA_ED_SA_QCAP_Falta125Vcc = 97  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_QCAP_TripDisjAgrup = 98  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_QCAP_Disj52A1Fechado = 99  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_QCAP_Disj52A1Falha = 100  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_QCAP_Disj52EFechado = 101  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_QCAP_Disj52EFalha = 102  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_QCAP_TensaoPresenteGE = (
    103  # Op02 (Read Discrete Inputs)
)
REG_SA_ED_SA_QCAP_TensaoPresenteTSA = (
    104  # Op02 (Read Discrete Inputs)
)
REG_SA_ED_SA_QCAP_Automatico = 105  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_QCAP_SubtensaoBarraGeral = (
    106  # Op02 (Read Discrete Inputs)
)
REG_SA_ED_SA_Reserva313 = 107  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_Reserva314 = 108  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_Reserva315 = 109  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_Reserva316 = 110  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_Reserva317 = 111  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_GMG_Alarme = 112  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_GMG_Trip = 113  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_GMG_Operacao = 114  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_GMG_BaixoComb = 115  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_GMG_Automatico = 116  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_GMG_DisjFechado = 117  # Op02 (Read Discrete Inputs)
REG_SA_CD_ResetGeral = 0  # Scale - Op15 (Write multiple coils)
REG_SA_CD_Liga_Secc1 = 1  # Scale - Op15 (Write multiple coils)
REG_SA_CD_Desliga_Secc1 = 2  # Scale - Op15 (Write multiple coils)
REG_SA_CD_Liga_Secc2 = 3  # Scale - Op15 (Write multiple coils)
REG_SA_CD_Desliga_Secc2 = 4  # Scale - Op15 (Write multiple coils)
REG_SA_CD_Liga_Secc3 = 5  # Scale - Op15 (Write multiple coils)
REG_SA_CD_Desliga_Secc3 = 6  # Scale - Op15 (Write multiple coils)
REG_SA_CD_Liga_BbaDren1 = 7  # Scale - Op15 (Write multiple coils)
REG_SA_CD_Desliga_BbaDren1 = 8  # Scale - Op15 (Write multiple coils)
REG_SA_CD_Liga_BbaDren2 = 9  # Scale - Op15 (Write multiple coils)
REG_SA_CD_Desliga_BbaDren2 = 10  # Scale - Op15 (Write multiple coils)
REG_SA_CD_Liga_BbaDren3 = 11  # Scale - Op15 (Write multiple coils)
REG_SA_CD_Desliga_BbaDren3 = 12  # Scale - Op15 (Write multiple coils)
REG_SA_CD_ResetRele787 = 13  # Scale - Op15 (Write multiple coils)
REG_SA_CD_ResetRele59N = 14  # Scale - Op15 (Write multiple coils)
REG_SA_CD_ResetRele311 = 15  # Scale - Op15 (Write multiple coils)
REG_SA_CD_ResetReleMRL1 = 16  # Scale - Op15 (Write multiple coils)
REG_SA_CD_Liga_DJ1 = 17  # Scale - Op15 (Write multiple coils)
REG_SA_CD_Desliga_DJ1 = 18  # Scale - Op15 (Write multiple coils)
REG_SA_CD_Liga_Disj52A1 = 19  # Scale - Op15 (Write multiple coils)
REG_SA_CD_Desliga_Disj52A1 = 20  # Scale - Op15 (Write multiple coils)
REG_SA_CD_Liga_Disj52E = 21  # Scale - Op15 (Write multiple coils)
REG_SA_CD_Desliga_Disj52E = 22  # Scale - Op15 (Write multiple coils)
REG_SA_CD_GMG_Liga = 23  # Scale - Op15 (Write multiple coils)
REG_SA_CD_GMG_Desl = 24  # Scale - Op15 (Write multiple coils)
REG_SA_CD_QCAP_Autom = 25  # Scale - Op15 (Write multiple coils)
REG_SA_CD_QCAP_Manual = 26  # Scale - Op15 (Write multiple coils)
REG_SA_CD_Cala_Sirene = 27  # Scale - Op15 (Write multiple coils)
REG_SA_RA_PM_810_Tensao_AB = (
    16  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_SA_RA_PM_810_Tensao_BC = (
    17  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_SA_RA_PM_810_Tensao_CA = (
    18  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_SA_RA_PM_810_Corrente_A = (
    19  # Scale 0.01 - Op04 (Read Input Regs - 3x)
)
REG_SA_RA_PM_810_Corrente_B = (
    20  # Scale 0.01 - Op04 (Read Input Regs - 3x)
)
REG_SA_RA_PM_810_Corrente_C = (
    21  # Scale 0.01 - Op04 (Read Input Regs - 3x)
)
REG_SA_RA_PM_810_Frequencia = (
    22  # Scale 0.001 - Op04 (Read Input Regs - 3x)
)
REG_SA_RA_PM_810_Fator_Potencia = (
    23  # Scale 0.001 - Op04 (Read Input Regs - 3x)
)
REG_SA_RA_PM_810_Potencia_Aparente = (
    24  # Op04 (Read Input Regs - 3x)
)
REG_SA_RA_PM_810_Potencia_Reativa = (
    25  # Op04 (Read Input Regs - 3x)
)
REG_SA_RA_PM_810_Potencia_Ativa = 26  # Op04 (Read Input Regs - 3x)
REG_SA_RA_PM1_710_Tensao_AB = (
    27  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_SA_RA_PM1_710_Tensao_BC = (
    28  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_SA_RA_PM1_710_Tensao_CA = (
    29  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_SA_RA_PM1_710_Corrente_A = (
    30  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_SA_RA_PM1_710_Corrente_B = (
    31  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_SA_RA_PM1_710_Corrente_C = (
    32  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_SA_RA_PM1_710_Frequencia = (
    33  # Scale 0.001 - Op04 (Read Input Regs - 3x)
)
REG_SA_RA_PM1_710_Fator_Potencia = (
    34  # Scale 0.001 - Op04 (Read Input Regs - 3x)
)
REG_SA_RA_PM1_710_Potencia_Aparente = (
    35  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_SA_RA_PM1_710_Potencia_Reativa = (
    36  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_SA_RA_PM1_710_Potencia_Ativa = (
    37  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_SA_RA_Reserva43 = 38  # Op04 (Read Input Regs - 3x)
REG_SA_RA_Reserva44 = 39  # Op04 (Read Input Regs - 3x)
REG_SA_RA_Reserva45 = 40  # Op04 (Read Input Regs - 3x)
REG_SA_RA_PM2_710_Tensao_AB = (
    41  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_SA_RA_PM2_710_Tensao_BC = (
    42  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_SA_RA_PM2_710_Tensao_CA = (
    43  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_SA_RA_PM2_710_Corrente_A = (
    44  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_SA_RA_PM2_710_Corrente_B = (
    45  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_SA_RA_PM2_710_Corrente_C = (
    46  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_SA_RA_PM2_710_Frequencia = (
    47  # Scale 0.001 - Op04 (Read Input Regs - 3x)
)
REG_SA_RA_PM2_710_Fator_Potencia = 48  # Op04 (Read Input Regs - 3x)
REG_SA_RA_PM2_710_Potencia_Aparente = (
    49  # Op04 (Read Input Regs - 3x)
)
REG_SA_RA_PM2_710_Potencia_Reativa = (
    50  # Op04 (Read Input Regs - 3x)
)
REG_SA_RA_PM2_710_Potencia_Ativa = 51  # Op04 (Read Input Regs - 3x)
REG_SA_RA_Reserva61 = 52  # Op04 (Read Input Regs - 3x)
REG_SA_RA_Reserva62 = 53  # Op04 (Read Input Regs - 3x)
REG_SA_RA_Reserva63 = 54  # Op04 (Read Input Regs - 3x)
REG_SA_RA_CorrenteBaixa1 = (
    55  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_SA_RA_CorrenteBaixa2 = (
    56  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_SA_RA_CorrenteBaixa3 = (
    57  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_SA_RA_CorrenteAlta1 = (
    58  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_SA_RA_CorrenteAlta2 = (
    59  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_SA_RA_CorrenteAlta3 = (
    60  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_SA_RA_CorrenteNeutro = (
    61  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_SA_RA_SEL787_Targets = 62  # Op04 (Read Input Regs - 3x)
REG_SA_RA_SEL787_Targets_Links_Bit00 = (
    63  # Op04 (Read Input Regs - 3x)
)
REG_SA_RA_SEL787_Targets_Links_Bit01 = (
    64  # Op04 (Read Input Regs - 3x)
)
REG_SA_RA_SEL787_Targets_Links_Bit02 = (
    65  # Op04 (Read Input Regs - 3x)
)
REG_SA_RA_SEL787_Targets_Links_Bit03 = (
    66  # Op04 (Read Input Regs - 3x)
)
REG_SA_RA_SEL787_Targets_Links_Bit04 = (
    67  # Op04 (Read Input Regs - 3x)
)
REG_SA_RA_SEL787_Targets_Links_Bit05 = (
    68  # Op04 (Read Input Regs - 3x)
)
REG_SA_RA_SEL787_Targets_Links_Bit06 = (
    69  # Op04 (Read Input Regs - 3x)
)
REG_SA_RA_SEL787_Targets_Links_Bit07 = (
    70  # Op04 (Read Input Regs - 3x)
)
REG_SA_RD_BbaDren1_FalhaAcion = 168  # Op02 (Read Input Status - 1x)
REG_SA_RD_BbaDren2_FalhaAcion = 169  # Op02 (Read Input Status - 1x)
REG_SA_RD_BbaDren3_FalhaAcion = 170  # Op02 (Read Input Status - 1x)
REG_SA_RD_Timeout_Sincronismo = 171  # Op02 (Read Input Status - 1x)
REG_SA_RD_DJ1_FalhaInt = 172  # Op02 (Read Input Status - 1x)
REG_SA_RD_CLP_Falha = 173  # Op02 (Read Input Status - 1x)
REG_SA_RD_Remota_Falha = 174  # Op02 (Read Input Status - 1x)
REG_SA_RD_SA_GMG_FalhaAcion = 175  # Op02 (Read Input Status - 1x)
REG_SA_RD_SA_QCAP_Autom = 176  # Op02 (Read Input Status - 1x)
REG_SA_RD_FalhaComunSETDA = 177  # Op02 (Read Input Status - 1x)
REG_SA_SA_TempoLigar = 0  # Op03 Read Holding Regs - 4x
REG_SA_RA_Float_PM_810_Energia_Reativa_Consumida = (
    149  # Op04 (Read Input Regs - 3x)
)
REG_SA_RA_Float_PM_810_Energia_Ativa_Consumida = (
    151  # Op04 (Read Input Regs - 3x)
)
REG_SA_RA_Float_PM_810_Energia_Reativa_Fornecida = (
    153  # Op04 (Read Input Regs - 3x)
)
REG_SA_RA_Float_PM_810_Energia_Ativa_Fornecida = (
    155  # Op04 (Read Input Regs - 3x)
)
REG_SA_RA_Float_PM1_710_Energia_Reativa_Consumida = (
    157  # Op04 (Read Input Regs - 3x)
)
REG_SA_RA_Float_PM1_710_Energia_Ativa_Consumida = (
    159  # Op04 (Read Input Regs - 3x)
)
REG_SA_RA_Float_PM1_710_Energia_Reativa_Fornecida = (
    161  # Op04 (Read Input Regs - 3x)
)
REG_SA_RA_Float_PM1_710_Energia_Ativa_Fornecida = (
    163  # Op04 (Read Input Regs - 3x)
)
REG_SA_RA_Float_PM2_710_Energia_Reativa_Consumida = (
    165  # Op04 (Read Input Regs - 3x)
)
REG_SA_RA_Float_PM2_710_Energia_Ativa_Consumida = (
    167  # Op04 (Read Input Regs - 3x)
)
REG_SA_RA_Float_PM2_710_Energia_Reativa_Fornecida = (
    169  # Op04 (Read Input Regs - 3x)
)
REG_SA_RA_Float_PM2_710_Energia_Ativa_Fornecida = (
    171  # Op04 (Read Input Regs - 3x)
)
REG_TDA_ED_QcataDisj52EAberto = 0  # Op02 (Read Discrete Inputs)
REG_TDA_ED_QcataDisj52ETrip = 1  # Op02 (Read Discrete Inputs)
REG_TDA_ED_QcataDisj52ETripDisjSai = 2  # Op02 (Read Discrete Inputs)
REG_TDA_ED_QcataDisj52EFalha380VCA = 3  # Op02 (Read Discrete Inputs)
REG_TDA_ED_DefeitoLimpaGrades = 4  # Op02 (Read Discrete Inputs)
REG_TDA_ED_Reserva65 = 5  # Op02 (Read Discrete Inputs)
REG_TDA_ED_Reserva66 = 6  # Op02 (Read Discrete Inputs)
REG_TDA_ED_Reserva67 = 7  # Op02 (Read Discrete Inputs)
REG_TDA_ED_Reserva70 = 8  # Op02 (Read Discrete Inputs)
REG_TDA_ED_Reserva71 = 9  # Op02 (Read Discrete Inputs)
REG_TDA_ED_Reserva72 = 10  # Op02 (Read Discrete Inputs)
REG_TDA_ED_Reserva73 = 11  # Op02 (Read Discrete Inputs)
REG_TDA_ED_Reserva74 = 12  # Op02 (Read Discrete Inputs)
REG_TDA_ED_Reserva75 = 13  # Op02 (Read Discrete Inputs)
REG_TDA_ED_Reserva76 = 14  # Op02 (Read Discrete Inputs)
REG_TDA_ED_Reserva77 = 15  # Op02 (Read Discrete Inputs)
REG_TDA_ED_Reserva80 = 16  # Op02 (Read Discrete Inputs)
REG_TDA_ED_Reserva81 = 17  # Op02 (Read Discrete Inputs)
REG_TDA_ED_Reserva82 = 18  # Op02 (Read Discrete Inputs)
REG_TDA_ED_Reserva83 = 19  # Op02 (Read Discrete Inputs)
REG_TDA_ED_Reserva84 = 20  # Op02 (Read Discrete Inputs)
REG_TDA_ED_Reserva85 = 21  # Op02 (Read Discrete Inputs)
REG_TDA_ED_Reserva86 = 22  # Op02 (Read Discrete Inputs)
REG_TDA_ED_Reserva87 = 23  # Op02 (Read Discrete Inputs)
REG_TDA_ED_Reserva90 = 24  # Op02 (Read Discrete Inputs)
REG_TDA_ED_Reserva91 = 25  # Op02 (Read Discrete Inputs)
REG_TDA_ED_Reserva92 = 26  # Op02 (Read Discrete Inputs)
REG_TDA_ED_Reserva93 = 27  # Op02 (Read Discrete Inputs)
REG_TDA_ED_Reserva94 = 28  # Op02 (Read Discrete Inputs)
REG_TDA_ED_Reserva95 = 29  # Op02 (Read Discrete Inputs)
REG_TDA_ED_Reserva96 = 30  # Op02 (Read Discrete Inputs)
REG_TDA_ED_Reserva97 = 31  # Op02 (Read Discrete Inputs)
REG_TDA_ED_1_AlmNivelBaixo = 32  # Op02 (Read Discrete Inputs)
REG_TDA_ED_1_TripNivelBaixo = 33  # Op02 (Read Discrete Inputs)
REG_TDA_ED_1_TripNivelCritico = 34  # Op02 (Read Discrete Inputs)
REG_TDA_ED_2_AlmNivelBaixo = 35  # Op02 (Read Discrete Inputs)
REG_TDA_ED_2_TripNivelBaixo = 36  # Op02 (Read Discrete Inputs)
REG_TDA_ED_2_TripNivelCritico = 37  # Op02 (Read Discrete Inputs)
REG_TDA_ED_3_AlmNivelBaixo = 38  # Op02 (Read Discrete Inputs)
REG_TDA_ED_3_TripNivelBaixo = 39  # Op02 (Read Discrete Inputs)
REG_TDA_ED_3_TripNivelCritico = 40  # Op02 (Read Discrete Inputs)
REG_TDA_ED_VertendoAlm = 41  # Op02 (Read Discrete Inputs)
REG_TDA_EA_NivelAntesGrade = (
    0  # Scale 0.01 - Op04 (Read Input Regs - 3x)
)
REG_TDA_EA_NivelDepoisGrade = (
    1  # Scale 0.01 - Op04 (Read Input Regs - 3x)
)
REG_TDA_EA_Reserva01 = 2  # Op04 (Read Input Regs - 3x)
REG_TDA_EA_Reserva02 = 3  # Op04 (Read Input Regs - 3x)
REG_TDA_EA_Reserva03 = 4  # Op04 (Read Input Regs - 3x)
REG_TDA_EA_Reserva04 = 5  # Op04 (Read Input Regs - 3x)
REG_TDA_EA_Reserva05 = 6  # Op04 (Read Input Regs - 3x)
REG_TDA_EA_Reserva06 = 7  # Op04 (Read Input Regs - 3x)
REG_TDA_EA_NivelAntesGradeFiltrado = (
    8  # Scale 0.01 - Op04 (Read Input Regs - 3x)
)
REG_TDA_EA_NumUGTabela1 = 9  # Op04 (Read Input Regs - 3x)
REG_TDA_EA_NumUGTabela2 = 10  # Op04 (Read Input Regs - 3x)
REG_TDA_EA_NumUGTabela3 = 11  # Op04 (Read Input Regs - 3x)
REG_TDA_RD_FalhaParametroNivel = 42  # Op02 (Read Discrete Inputs)
REG_TDA_RD_UG1_ContNivelHabilitado = 43  # Op02 (Read Discrete Inputs)
REG_TDA_RD_UG1_CmdResetAutoNivel = 44  # Op02 (Read Discrete Inputs)
REG_TDA_RD_UG1_CmdPartidaAutoNivel = 45  # Op02 (Read Discrete Inputs)
REG_TDA_RD_UG2_ContNivelHabilitado = 46  # Op02 (Read Discrete Inputs)
REG_TDA_RD_UG2_CmdResetAutoNivel = 47  # Op02 (Read Discrete Inputs)
REG_TDA_RD_UG2_CmdPartidaAutoNivel = 48  # Op02 (Read Discrete Inputs)
REG_TDA_RD_UG3_ContNivelHabilitado = 49  # Op02 (Read Discrete Inputs)
REG_TDA_RD_UG3_CmdResetAutoNivel = 50  # Op02 (Read Discrete Inputs)
REG_TDA_RD_UG3_CmdPartidaAutoNivel = 51  # Op02 (Read Discrete Inputs)
REG_TDA_RD_ExcedidoReligUG1 = 52  # Op02 (Read Discrete Inputs)
REG_TDA_RD_ExcedidoReligUG2 = 53  # Op02 (Read Discrete Inputs)
REG_TDA_RD_ExcedidoReligUG3 = 54  # Op02 (Read Discrete Inputs)
REG_TDA_RD_ExcedidoReligSE = 55  # Op02 (Read Discrete Inputs)
REG_TDA_RD_StatusControleNivel = 56  # Op02 (Read Discrete Inputs)
REG_TDA_RD_StatusRelig52L = 57  # Op02 (Read Discrete Inputs)
REG_TDA_CD_ResetGeral = (
    0  # Escrita de Word Simples (Preset Single Register - 4x)
)
REG_TDA_CD_Hab_Nivel = (
    1  # Escrita de Word Simples (Preset Single Register - 4x)
)
REG_TDA_CD_Desab_Nivel = (
    2  # Escrita de Word Simples (Preset Single Register - 4x)
)
REG_TDA_CD_Hab_Religamento52L = (
    3  # Escrita de Word Simples (Preset Single Register - 4x)
)
REG_TDA_CD_Desab_Religamento52L = (
    4  # Escrita de Word Simples (Preset Single Register - 4x)
)
REG_TDA_SA_Nivel_1_Religamento = (
    0  # Scale 0.01 - OpLeitura de Words (Read Holding Regs - 4x)
)
REG_TDA_SA_Nivel_1_Alto = (
    1  # Scale 0.01 - OpLeitura de Words (Read Holding Regs - 4x)
)
REG_TDA_SA_Nivel_1_Medio = (
    2  # Scale 0.01 - OpLeitura de Words (Read Holding Regs - 4x)
)
REG_TDA_SA_Nivel_1_Baixo = (
    3  # Scale 0.01 - OpLeitura de Words (Read Holding Regs - 4x)
)
REG_TDA_SA_Nivel_2_Religamento = (
    4  # Scale 0.01 - OpLeitura de Words (Read Holding Regs - 4x)
)
REG_TDA_SA_Nivel_2_Alto = (
    5  # Scale 0.01 - OpLeitura de Words (Read Holding Regs - 4x)
)
REG_TDA_SA_Nivel_2_Medio = (
    6  # Scale 0.01 - OpLeitura de Words (Read Holding Regs - 4x)
)
REG_TDA_SA_Nivel_2_Baixo = (
    7  # Scale 0.01 - OpLeitura de Words (Read Holding Regs - 4x)
)
REG_TDA_SA_Nivel_3_Religamento = (
    8  # Scale 0.01 - OpLeitura de Words (Read Holding Regs - 4x)
)
REG_TDA_SA_Nivel_3_Alto = (
    9  # Scale 0.01 - OpLeitura de Words (Read Holding Regs - 4x)
)
REG_TDA_SA_Nivel_3_Medio = (
    10  # Scale 0.01 - OpLeitura de Words (Read Holding Regs - 4x)
)
REG_TDA_SA_Nivel_3_Baixo = (
    11  # Scale 0.01 - OpLeitura de Words (Read Holding Regs - 4x)
)
REG_TDA_SA_Potencia_1_Alta = (
    12  # OpLeitura de Words (Read Holding Regs - 4x)
)
REG_TDA_SA_Potencia_1_Media = (
    13  # OpLeitura de Words (Read Holding Regs - 4x)
)
REG_TDA_SA_Potencia_1_Baixa = (
    14  # OpLeitura de Words (Read Holding Regs - 4x)
)
REG_TDA_SA_Potencia_2_Alta = (
    15  # OpLeitura de Words (Read Holding Regs - 4x)
)
REG_TDA_SA_Potencia_2_Media = (
    16  # OpLeitura de Words (Read Holding Regs - 4x)
)
REG_TDA_SA_Potencia_2_Baixa = (
    17  # OpLeitura de Words (Read Holding Regs - 4x)
)
REG_TDA_SA_Potencia_3_Alta = (
    18  # OpLeitura de Words (Read Holding Regs - 4x)
)
REG_TDA_SA_Potencia_3_Media = (
    19  # OpLeitura de Words (Read Holding Regs - 4x)
)
REG_TDA_SA_Potencia_3_Baixa = (
    20  # OpLeitura de Words (Read Holding Regs - 4x)
)
REG_TDA_NivelMaisCasasAntes = 12  # Scale 400 + 0.0001 X - Op04 (Read Input Regs - 3x)
REG_TDA_NivelMaisCasasDepois = 13  # Scale 400 + 0.0001 X - Op04 (Read Input Regs - 3x)




"""
#--------------------------------------------------------------------------------------------------------------------------------------#
#Registradores utilizados na simulação, para voltar aos valores antigos, deletar os comentarios de linha "#antigo->" e manter o número.
REG_UG1_RetornosDigitais_EtapaAux_Sim = 34901
REG_UG1_RetrornosAnalogicos_AUX_Condicionadores = 34902
REG_UG1_CD_EmergenciaViaSuper = 32295 #antigo -> 4  # Op15 (Write multiple coils)
REG_UG1_CD_IniciaPartida = 32294 #antigo -> 45  # Op15 (Write multiple coils)
REG_UG1_CD_IniciaParada = 32290 #antigo -> 46  # Op15 (Write multiple coils)
REG_UG1_RD_TripEletrico = 34904 #antigo -> 134  # Op02 (Read Input Status)
REG_UG1_RD_TripMecanico = 34198 #antigo -> 135  # Op02 (Read Input Status)
REG_UG1_RA_Temperatura_01 = 32871 #antigo -> 24  # Op04 (Read Input Regs - 3x)
REG_UG1_RA_Temperatura_02 = 32872 #antigo -> 25  # Op04 (Read Input Regs - 3x)
REG_UG1_RA_Temperatura_03 = 32873 #antigo -> 26  # Op04 (Read Input Regs - 3x)
REG_UG1_RA_Temperatura_04 = 32874 #antigo -> 27  # Op04 (Read Input Regs - 3x)
REG_UG1_RA_Temperatura_05 = 32875 #antigo -> 28  # Op04 (Read Input Regs - 3x)
REG_UG1_RA_Temperatura_06 = 32876 #antigo -> 29  # Op04 (Read Input Regs - 3x)
REG_UG1_RA_Temperatura_07 = 32877 #antigo -> 30  # Op04 (Read Input Regs - 3x)
REG_UG1_RA_Temperatura_08 = 32878 #antigo -> 31  # Op04 (Read Input Regs - 3x)
REG_UG1_RA_Temperatura_09 = 32879 #antigo -> 32  # Op04 (Read Input Regs - 3x)
REG_UG1_RA_PM_710_Potencia_Ativa = 32836 #antigo->45  # Op04 (Read Input Regs - 3x)
REG_UG1_SA_SPPotAtiva = 33585 #antigo -> 1  # Scale - Op16 (Preset Multiple Regs - 4x)
REG_UG1_EA_PressK1CaixaExpiral = (
    34903  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)

REG_UG2_RetornosDigitais_EtapaAux_Sim = 44901
REG_UG2_RetrornosAnalogicos_AUX_Condicionadores = 44902
REG_UG2_CD_EmergenciaViaSuper = 42295 #antigo -> 4  # Op15 (Write multiple coils)
REG_UG2_CD_IniciaPartida = 42294 #antigo -> 45  # Op15 (Write multiple coils)
REG_UG2_CD_IniciaParada = 42290 #antigo -> 46  # Op15 (Write multiple coils)
REG_UG2_RD_TripEletrico = 44904  #antigo -> 134# Op02 (Read Input Status)
REG_UG2_RD_TripMecanico = 44198  #antigo -> 135 # Op02 (Read Input Status)
REG_UG2_RA_Temperatura_01 = 42871 #antigo -> 24  # Op04 (Read Input Regs - 3x)
REG_UG2_RA_Temperatura_02 = 42872 #antigo -> 25  # Op04 (Read Input Regs - 3x)
REG_UG2_RA_Temperatura_03 = 42873 #antigo -> 26  # Op04 (Read Input Regs - 3x)
REG_UG2_RA_Temperatura_04 = 42874 #antigo -> 27  # Op04 (Read Input Regs - 3x)
REG_UG2_RA_Temperatura_05 = 42875 #antigo -> 28  # Op04 (Read Input Regs - 3x)
REG_UG2_RA_Temperatura_06 = 42876 #antigo -> 29  # Op04 (Read Input Regs - 3x)
REG_UG2_RA_Temperatura_07 = 42877 #antigo -> 30  # Op04 (Read Input Regs - 3x)
REG_UG2_RA_Temperatura_08 = 42878 #antigo -> 31  # Op04 (Read Input Regs - 3x)
REG_UG2_RA_Temperatura_09 = 42879 #antigo -> 32  # Op04 (Read Input Regs - 3x)
REG_UG2_RA_PM_710_Potencia_Ativa = 42836 #antigo ->45  # Op04 (Read Input Regs - 3x)
REG_UG2_SA_SPPotAtiva = 43585 #antigo -> 1  # Scale - Op16 (Preset Multiple Regs - 4x)
REG_UG2_EA_PressK1CaixaExpiral = (
    44903  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)

REG_UG3_RetornosDigitais_EtapaAux_Sim = 54901

REG_UG3_RetrornosAnalogicos_AUX_Condicionadores = 54902

REG_UG3_CD_EmergenciaViaSuper = 52295 #antigo -> 4  # Op15 (Write multiple coils)
REG_UG3_CD_IniciaPartida = 52294 #antigo -> 45  # Op15 (Write multiple coils)
REG_UG3_CD_IniciaParada = 52290 #antigo -> 46  # Op15 (Write multiple coils)
REG_UG3_RD_TripEletrico = 54904 #antigo -> 134  # Op02 (Read Input Status)
REG_UG3_RD_TripMecanico = 54198 #antigo -> 135  # Op02 (Read Input Status)
REG_UG3_RA_Temperatura_01 = 52871 #antigo -> 24  # Op04 (Read Input Regs - 3x)
REG_UG3_RA_Temperatura_02 = 52872 #antigo -> 25  # Op04 (Read Input Regs - 3x)
REG_UG3_RA_Temperatura_03 = 52873 #antigo -> 26  # Op04 (Read Input Regs - 3x)
REG_UG3_RA_Temperatura_04 = 52874 #antigo -> 27  # Op04 (Read Input Regs - 3x)
REG_UG3_RA_Temperatura_05 = 52875 #antigo -> 28  # Op04 (Read Input Regs - 3x)
REG_UG3_RA_Temperatura_06 = 52876 #antigo -> 29  # Op04 (Read Input Regs - 3x)
REG_UG3_RA_Temperatura_07 = 52877 #antigo -> 30  # Op04 (Read Input Regs - 3x)
REG_UG3_RA_Temperatura_08 = 52878 #antigo -> 31  # Op04 (Read Input Regs - 3x)
REG_UG3_RA_Temperatura_09 = 52879 #antigo -> 32  # Op04 (Read Input Regs - 3x)
REG_UG3_RA_PM_710_Potencia_Ativa = 52836 #antigo->45  # Op04 (Read Input Regs - 3x)
REG_UG3_SA_SPPotAtiva = 53585 #antigo -> 1  # Scale - Op16 (Preset Multiple Regs - 4x)
REG_UG3_EA_PressK1CaixaExpiral = (
    54903  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)

REG_SA_CD_ResetGeral = 22288 #antigo -> 0  # Scale - Op15 (Write multiple coils)
REG_SA_CD_Liga_DJ1 = 22293 #antigo -> 17  # Scale - Op15 (Write multiple coils)
REG_SA_RetornosAnalogicos_Medidor_potencia_kw_mp = (
    24900 # Op04 (Read Input Regs - 3x)
)
REG_SA_RA_PM_810_Tensao_AB = (
    22789 #antigo -> 16  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_SA_RA_PM_810_Tensao_BC = (
    22790 #antigo -> 17  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)
REG_SA_RA_PM_810_Tensao_CA = (
    22791 #antigo -> 18  # Scale 0.1 - Op04 (Read Input Regs - 3x)
)

REG_TDA_NivelMaisCasasAntes = 22766 #antigo -> 12  # Scale 400 + 0.0001 X - Op04 (Read Input Regs - 3x)
REG_TDA_EA_NivelDepoisGrade = (
    22767 # antgo -> 1  # Scale 0.01 - Op04 (Read Input Regs - 3x)
)


REG_UG1_ED_FreioPastilhaGasta = 30000 # antigo -> 24  # Op02 (Read Input Status)
REG_UG2_ED_FreioPastilhaGasta = 40000 # antigo -> 24  # Op02 (Read Input Status)
REG_UG3_ED_FreioPastilhaGasta = 50000 # antigo -> 24  # Op02 (Read Input Status)

REG_UG1_ED_FiltroPresSujo75Troc = 30001 # antigo -> 37  # Op02 (Read Input Status)
REG_UG2_ED_FiltroPresSujo75Troc = 40001 # antigo -> 37  # Op02 (Read Input Status)
REG_UG3_ED_FiltroPresSujo75Troc = 50001 # antigo -> 37  # Op02 (Read Input Status)

REG_UG1_ED_FiltroRetSujo75Troc = 30002 # antigo -> 39  # Op02 (Read Input Status)
REG_UG2_ED_FiltroRetSujo75Troc = 40002 # antigo -> 39  # Op02 (Read Input Status)
REG_UG3_ED_FiltroRetSujo75Troc = 50002 # antigo -> 39  # Op02 (Read Input Status)

REG_UG1_ED_UHLM_Filt1PresSujo75Troc = 30003 # antigo -> 59  # Op02 (Read Input Status)
REG_UG2_ED_UHLM_Filt1PresSujo75Troc = 40003 # antigo -> 59  # Op02 (Read Input Status)
REG_UG3_ED_UHLM_Filt1PresSujo75Troc = 50003 # antigo -> 59  # Op02 (Read Input Status)

REG_UG1_ED_UHLM_Filt2PresSujo75Troc = 30004 # antigo -> 61  # Op02 (Read Input Status)
REG_UG2_ED_UHLM_Filt2PresSujo75Troc = 40004 # antigo -> 61  # Op02 (Read Input Status)
REG_UG3_ED_UHLM_Filt2PresSujo75Troc = 50004 # antigo -> 61  # Op02 (Read Input Status)

REG_UG1_ED_FiltroPressaoBbaMecSj75 = 30005 # antigo -> 65  # Op02 (Read Input Status)
REG_UG2_ED_FiltroPressaoBbaMecSj75 = 40005 # antigo -> 65  # Op02 (Read Input Status)
REG_UG3_ED_FiltroPressaoBbaMecSj75 = 50005 # antigo -> 65  # Op02 (Read Input Status)

REG_UG1_ED_TripPartRes = 30006 # antigo -> 82  # Op02 (Read Input Status)
REG_UG2_ED_TripPartRes = 40006 # antigo -> 82  # Op02 (Read Input Status)
REG_UG3_ED_TripPartRes = 50006 # antigo -> 82  # Op02 (Read Input Status)

REG_UG1_RD_FalhaComunG1TDA = 30007 # antigo -> 212  # Op02 (Read Input Status)
REG_UG2_RD_FalhaComunG2TDA = 40007 # antigo -> 210  # Op02 (Read Input Status)
REG_UG3_RD_FalhaComunG3TDA = 50007 # antigo -> 210  # Op02 (Read Input Status)

REG_SA_ED_SA_QLCF_Disj52EFechado = 20000 # antigo -> 84  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_QLCF_Disj52ETrip = 20001 # antigo -> 85  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_QLCF_TripDisjAgrup = 20002 # antigo -> 86  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_QCAP_Disj52EFechado = 20003 # antigo -> 101  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_QCAP_SubtensaoBarraGeral = 20004 # antigo -> 106  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_GMG_Alarme = 20005 # antigo -> 112  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_GMG_Trip = 20006 # antigo -> 113  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_GMG_Operacao = 20007 # antigo -> 114  # Op02 (Read Discrete Inputs)
REG_SA_ED_SA_GMG_BaixoComb = 20008 # antigo -> 115  # Op02 (Read Discrete Inputs)
REG_SA_RD_BbaDren1_FalhaAcion = 20009 # antigo -> 168  # Op02 (Read Input Status - 1x)
REG_SA_RD_BbaDren2_FalhaAcion = 20010 # antigo -> 169  # Op02 (Read Input Status - 1x)
REG_SA_RD_BbaDren3_FalhaAcion = 20011 # antigo -> 170  # Op02 (Read Input Status - 1x)
REG_SA_RD_SA_GMG_FalhaAcion = 20012 # antigo -> 175  # Op02 (Read Input Status - 1x)
REG_SA_RD_FalhaComunSETDA = 20013 # antigo -> 177  # Op02 (Read Input Status - 1x)
"""