# Generated by Django 3.1.5 on 2021-02-18 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametros_moa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('descricao', models.TextField()),
                ('comando', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros_moa.comando')),
            ],
        ),
    ]
