# Generated by Django 3.2.6 on 2022-10-14 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametros_moa', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.DateTimeField()),
                ('observacao', models.TextField()),
                ('comando', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros_moa.comando')),
                ('executado', models.IntegerField(default=0)),
                ('campo_auxiliar', models.TextField()),
                ('criado_por', models.CharField(max_length=255)),
                ('modificado_por', models.CharField(max_length=255)),
                ('ts_criado', models.DateTimeField()),
                ('ts_modificado', models.DateTimeField()),
            ],
        ),
    ]
