# Generated by Django 3.1.5 on 2021-02-18 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agendamento",
            old_name="descricao",
            new_name="observacao",
        ),
    ]
