# Generated by Django 3.2.12 on 2023-04-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_alter_agendamento_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
