USINA_NV_VERTEDOURO = 462.37
USINA_VAZAO_SANITARIA_COTA = 461.00
USINA_NV_MINIMO_OPERACAO = 461.37
USINA_TENSAO_MINIMA = 21945
USINA_TENSAO_MAXIMA = 24255

POT_MAX = 3037.5
POT_MIN = 0.3 * POT_MAX

ETAPA_UP = 0
ETAPA_UPGM = 1
ETAPA_UVD = 3
ETAPA_UPS = 4
ETAPA_US = 5

UNIDADE_SINCRONIZADA = 1
UNIDADE_PARANDO = 2
UNIDADE_PARADA = 5
UNIDADE_SINCRONIZANDO = 9

TEMPO_TRANS_UP_UPGM = 5
TEMPO_TRANS_UPGM_UVD = 5
TEMPO_TRANS_UVD_UPS = 5
TEMPO_TRANS_UPS_US = 5

TEMPO_TRANS_US_UPS = 5
TEMPO_TRANS_UPS_UVD = 5
TEMPO_TRANS_UVD_UPGM = 5
TEMPO_TRANS_UPGM_UP = 5

TEMPO_ABERTURA_COMPORTA = 193
TEMPO_FECHAMENTO_COMPORTA = 1
TEMPO_CRACKING_COMPORTA = 106