compartilhado = {
    "GLB": {
        "tempo_simul": 0,

        "stop_sim": False,
        "stop_gui": False
    },

    "USN": {
        "q_liquida": 0,
        "q_alfuente": 0,
        "q_sanitaria": 0,
        "q_vertimento": 0,
        "nv_montante": 461.9,
        "nv_jusante_grade": 0,

        "potencia_kw_se": 0,
        "potencia_kw_mp": 0,
        "potencia_kw_mr": 0,
        "tensao_na_linha": 23100,

        "trip_condic_usina": False,
        "reset_geral_condic": False,

        "aux_borda1": 0,
        "aux_borda2": 0,
        "aux_borda3": 0,
        "aux_borda4": 0,
        "aux_borda5": 0,
        "aux_borda6": 0,
        "aux_borda7": 0,
        "aux_borda8": 0,
        "aux_borda9": 0,
        "aux_borda10": 0,
        "aux_borda11": 0,
        "aux_borda12": 0,
    },

    "DJ": {
        "dj52L_trip": False,
        "dj52L_aberto": False,
        "dj52L_fechado": True,
        "dj52L_falta_vcc": False,
        "dj52L_inconsistente": False,
        "dj52L_mola_carregada": True,
        "dj52L_falha_fechamento": False,
        "dj52L_condicao_de_fechamento": False,

        "debug_dj52L_abrir": False,
        "debug_dj52L_fechar": False,
        "debug_dj52L_reconhece_reset": False
    },

    "UG": {
        "q_ug1": 1,
        "flags_ug1": 0,
        "etapa_aux_ug1": 5,
        "progresso_ug1": 0,
        "etapa_alvo_ug1": 0,
        "etapa_atual_ug1": 0,
        "potencia_kw_ug1": 0,
        "setpoint_kw_ug1": 0,
        "temperatura_ug1_fase_r": 25,
        "temperatura_ug1_fase_s": 25,
        "temperatura_ug1_fase_t": 25,
        "temperatura_ug1_mancal_guia": 25,
        "temperatura_ug1_mancal_casq_comb": 25,
        "temperatura_ug1_nucleo_gerador_1": 25,
        "temperatura_ug1_patins_mancal_comb_1": 25,
        "temperatura_ug1_patins_mancal_comb_2": 25,
        "temperatura_ug1_mancal_guia_interno_1": 25,
        "temperatura_ug1_mancal_guia_interno_2": 25,
        "temperatura_ug1_mancal_contra_esc_comb": 25,
        "pressao_turbina_ug1": 16.2,
        "aux_comp_a_ug1": 0,
        "aux_comp_c_ug1": 0,
        "aux_comp_f_ug1": 0,

        "q_ug2": 0,
        "flags_ug2": 0,
        "etapa_aux_ug2": 5,
        "progresso_ug2": 0,
        "etapa_alvo_ug2": 0,
        "etapa_atual_ug2": 0,
        "potencia_kw_ug2": 0,
        "setpoint_kw_ug2": 0,
        "temperatura_ug2_fase_r": 25,
        "temperatura_ug2_fase_s": 25,
        "temperatura_ug2_fase_t": 25,
        "temperatura_ug2_mancal_guia": 25,
        "temperatura_ug2_mancal_casq_comb": 25,
        "temperatura_ug2_nucleo_gerador_1": 25,
        "temperatura_ug2_patins_mancal_comb_1": 25,
        "temperatura_ug2_patins_mancal_comb_2": 25,
        "temperatura_ug2_mancal_guia_interno_1": 25,
        "temperatura_ug2_mancal_guia_interno_2": 25,
        "temperatura_ug2_mancal_contra_esc_comb": 25,
        "pressao_turbina_ug2": 16.2,
        "aux_comp_a_ug2": 0,
        "aux_comp_c_ug2": 0,
        "aux_comp_f_ug2": 0,

        "trip_ug1": False,
        "trip_ug2": False,
        "equalizar_ug1": False,
        "equalizar_ug2": False,
        "trip_condic_ug1": False,
        "trip_condic_ug2": False,
        "reconhece_reset_ug1": False,
        "reconhece_reset_ug2": False,
        "set_press_cx_espiral_ug1": False,
        "set_press_cx_espiral_ug2": False,
        "limpa_grades_operando": False,

        "comporta_aberta_ug1": False,
        "comporta_aberta_ug2": False,
        "comporta_fechada_ug1": True,
        "comporta_fechada_ug2": True,
        "comporta_cracking_ug1": False,
        "comporta_cracking_ug2": False,
        "comporta_operando_ug1": False,
        "comporta_operando_ug2": False,
        "set_press_turbina_ug1": False,
        "set_press_turbina_ug2": False,
        "thread_comp_aberta_ug1": False,
        "thread_comp_aberta_ug2": False,
        "thread_comp_fechada_ug1": False,
        "thread_comp_fechada_ug2": False,
        "thread_comp_cracking_ug1": False,
        "thread_comp_cracking_ug2": False,
        "condicao_falha_cracking_ug1": False,
        "condicao_falha_cracking_ug2": False,
        "permissao_abrir_comporta_ug1": False,
        "permissao_abrir_comporta_ug2": False,

        "debug_setpoint_kw_ug1": 0,
        "debug_setpoint_kw_ug2": 0,

        "debug_parar_ug1": False,
        "debug_partir_ug1": False,
        "debug_parar_ug2": False,
        "debug_partir_ug2": False
    },

    "BORDA": {
        "usn_condic": False,
        "ug1_condic": False,
        "ug2_condic": False
    }
}